WIP [CONSVC-2064] test: add integration tests for the providers endpoint
mozilla-services/merino-py pull request #103
Opened 2022-11-02 21:50 UTC by Trinaa

🚧 WIP 🚧 

##Description
Add integration test coverage to the `providers` endpoint

##Issue(s)
[CONSVC-2064](https://mozilla-hub.atlassian.net/browse/CONSVC-2064)

2022-11-02 21:55 UTC, Trinaa commented on tests/integration/api/v1/providers/test_providers.py
> +                {"id": "hidden-provider", "availability": "hidden"},
@ncloudioj or @quiiver 

Could you confirm this expected behaviour?

In the case where `hidden()` returns True in a Provider. A response from the `providers` endpoint will include the provider name and "hidden" availability value.

2022-11-03 01:28 UTC, ncloudioj commented on tests/integration/api/v1/providers/test_providers.py
> +                {"id": "hidden-provider", "availability": "hidden"},
Correct, that's exactly what the [API doc](https://mozilla-services.github.io/merino-py/api.html#response-1) specifies.

Note that this `availability` field is made for Firefox, indicating that Firefox shouldn't expose hidden providers to Firefox users, but they can still be used by other consumers for other purposes.

2022-11-09 11:33 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

I have one suggestion for test item IDs.

2022-11-09 11:33 UTC, hackebrot commented on tests/integration/api/v1/providers/test_providers.py
> +@pytest.mark.parametrize(
You did a great job defining the test cases in [CONSVC-2064](https://mozilla-hub.atlassian.net/browse/CONSVC-2064), @Trinaa! 👍🏻 

I suggest we codify this here by explicitly setting IDs for test items rather than letting pytest auto-generate them from the fixture parameters. This will change the log output from:

```text
test_providers.py::test_providers[expected_response0-providers0] PASSED                  [ 63%]
test_providers.py::test_providers[expected_response1-providers1] PASSED                  [ 64%]
test_providers.py::test_providers[expected_response3-providers3] PASSED                  [ 66%]
test_providers.py::test_providers[expected_response4-providers4] PASSED                  [ 66%]
```

to 

```text
test_providers.py::test_providers[no-providers] PASSED                                 [ 63%]
test_providers.py::test_providers[one-provider-enabled_by_default] PASSED              [ 64%]
test_providers.py::test_providers[one-provider-disabled_by_default] PASSED             [ 65%]
test_providers.py::test_providers[one-provider-hidden] PASSED                          [ 66%]
test_providers.py::test_providers[three-providers-all-availabilities] PASSED           [ 66%]
```

I think that the additional context both in code and the log output improves comprehensibility.

The suggestion below is for adding the IDs above. Feel free to rename the them or change as you see fit.

2022-11-09 11:33 UTC, hackebrot commented on tests/integration/api/v1/providers/test_providers.py
> +)
```suggestion
    ids=[
        "no-providers",
        "one-provider-enabled_by_default",
        "one-provider-disabled_by_default",
        "one-provider-hidden",
        "three-providers-all-availabilities",
    ],
)
```

2022-11-09 14:24 UTC, Trinaa commented on tests/integration/api/v1/providers/test_providers.py
> +)
Change applied [21748ad](https://github.com/mozilla-services/merino-py/pull/103/commits/21748ad2e4d308c4e6c9352d7967b77b4a574448)

2022-11-09 14:41 UTC, hackebrot commented on tests/integration/api/v1/providers/test_providers.py
> +@pytest.mark.parametrize(
Awesome! 😸

2022-11-09 14:43 UTC, hackebrot approved these changes
LGTM! 🚀

2022-11-09 15:58 UTC, merged

2022-11-09 17:34 UTC, taddes commented
Good stuff @Trinaa ! I didn't approve before Raphael, but I give a huge 👍 to this. Thanks for pointing out this endpoint to me again, was good to remember it exists and good to provide testing for it.