[CONSVC-2065] Set minimum coverage for combined unit and integration tests
mozilla-services/merino-py pull request #118
Opened 2022-11-21 20:44 UTC by Trinaa

# Description
- Add a minimum combined unit and integration test coverage check for 95%
    - In the case of failure, Circle CI reports as follows:
    <img width="488" alt="image" src="https://user-images.githubusercontent.com/3422688/203152818-d56af71d-3832-486e-8ee2-4558e0fbfaeb.png">
    <img width="427" alt="image" src="https://user-images.githubusercontent.com/3422688/203152742-76e377fa-ecc1-416f-aa4e-91640d081928.png">
- Output test results to file format compatible with CircleCI in order to take advantage of test insights
    - ref: [Collecting test data](https://circleci.com/docs/collect-test-data/)
- Add `test-results` directory to `.gitignore`
- Update documentation
# Issue(s)
#87 | [CONSVC-2065](https://mozilla-hub.atlassian.net/browse/CONSVC-2065)

2022-11-22 09:38 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

This is great! I tested it out locally and it worked! 🚀 

I've added a few inline comments for your consideration.

2022-11-22 09:38 UTC, hackebrot commented on pyproject.toml
> +data_file = "workspace/test-results/.coverage"
What does this do?

2022-11-22 09:38 UTC, hackebrot commented on .gitignore
> +test-results/
Running `make test` generated this new directory for me locally:

```text
workspace
└── test-results
    ├── integration_results.xml
    └── unit_results.xml
```

Does it make sense to ignore `workspace/` and its subdirectories?

2022-11-22 09:38 UTC, hackebrot commented on .circleci/config.yml
> +          path: workspace/test-results
* in `Create Workspace` above we hardcode the path to the workspace: `workspace`
* the `Unit tests` step doesn't specify the test results dir: 🤔 
* the `store_test_results` step hardcodes the path to the test results dir: `workspace/test-results`

For this sequence of steps to work, `TEST_RESULT_DIR` in the `Makefile` **must** be set to `workspace/test-results`. Any changes to the default will cause the CI job to fail.

I recommend we hand over control over this path to the CircleCI config completely and set `TEST_RESULT_DIR` explicitly by setting an environment variable for the `Unit tests` and the `Integration tests` steps or for the entire job.

For reference: https://circleci.com/docs/env-vars/#environment-variable-usage-options

2022-11-22 09:38 UTC, hackebrot commented on Makefile
> +TEST_RESULT_DIR := "workspace/test-results"
```suggestion
TEST_RESULTS_DIR := "workspace/test-results"
```

2022-11-22 19:06 UTC, Trinaa commented on pyproject.toml
> +data_file = "workspace/test-results/.coverage"
In the _coverage_ module, the `data_file` option specifies the coverage file name and output location. By default, it's value is `.coverage`. The _pytest_ and _coverage_ modules will reference the pyproject.toml configurations by default.
Source: https://coverage.readthedocs.io/en/6.5.0/cmd.html#combining-data-files-coverage-combine

2022-11-22 19:06 UTC, Trinaa commented on .gitignore
> +test-results/
Change applied: [825f6a6](https://github.com/mozilla-services/merino-py/pull/118/commits/825f6a603c093d8f8b12a6dd3c3ffdf7807f2cee)

2022-11-22 19:34 UTC, Trinaa commented on Makefile
> +TEST_RESULT_DIR := "workspace/test-results"
Change applied: [c3ab97b](https://github.com/mozilla-services/merino-py/pull/118/commits/c3ab97b79d49efba9311cfe7db23da7e9d9f2216)

2022-11-22 20:24 UTC, ncloudioj commented on .gitignore
> +test-results/
This can be dropped as the root dir `workspace` is already ignored.

2022-11-22 20:24 UTC, ncloudioj commented on .dockerignore
> +test-results/
This can be dropped as the root dir `workspace` is already ignored.

2022-11-22 20:26 UTC, ncloudioj commented on .circleci/config.yml
> +          command: make unit-tests TEST_RESULTS_DIR=$TEST_RESULTS_DIR
```suggestion
          command: make unit-tests
          environment:
            TEST_RESULTS_DIR: $TEST_RESULTS_DIR
```

2022-11-22 20:27 UTC, ncloudioj commented on .circleci/config.yml
> +          command: make integration-tests TEST_RESULTS_DIR=$TEST_RESULTS_DIR
```suggestion
          command: make integration-tests
          environment:
            TEST_RESULTS_DIR: $TEST_RESULTS_DIR
```

2022-11-22 20:29 UTC, ncloudioj approved these changes
Looks great, r+ wc.

2022-11-22 20:31 UTC, Trinaa commented on .dockerignore
> +test-results/
Change applied: [a23c9aa](https://github.com/mozilla-services/merino-py/pull/118/commits/a23c9aa39851599af311e9e8583eb1e97292e95c)

2022-11-22 20:31 UTC, Trinaa commented on .gitignore
> +test-results/
Change applied: [a23c9aa](https://github.com/mozilla-services/merino-py/pull/118/commits/a23c9aa39851599af311e9e8583eb1e97292e95c)

2022-11-22 21:11 UTC, Trinaa commented on .circleci/config.yml
> +          command: make unit-tests TEST_RESULTS_DIR=$TEST_RESULTS_DIR
In an experiment, I wasn't able to make this change work. I think the environment variable isn't considered by the Makefile or perhaps the Makefile definition is overriding. As discussed offline, I'll leave the command as is.

2022-11-22 21:11 UTC, Trinaa commented on .circleci/config.yml
> +          command: make integration-tests TEST_RESULTS_DIR=$TEST_RESULTS_DIR
See above [response](https://github.com/mozilla-services/merino-py/pull/118#discussion_r1029823112)

2022-11-22 21:12 UTC, Trinaa commented on .circleci/config.yml
> +          path: workspace/test-results
Please confirm if I applied the change as expected.
Change applied: [47d0549](https://github.com/mozilla-services/merino-py/pull/118/commits/47d05495508861d5d92657e587b448282e44352c)

2022-11-23 09:26 UTC, hackebrot commented on .circleci/config.yml
> +          command: make unit-tests TEST_RESULTS_DIR=$TEST_RESULTS_DIR
We probably need to use a Conditional Variable Assignment in `Makefile` in this case:
https://www.gnu.org/software/make/manual/make.html#Conditional-Assignment

```bash
TEST_RESULTS_DIR ?= "workspace/test-results"
```

2022-11-23 17:11 UTC, Trinaa commented on .circleci/config.yml
> +          command: make unit-tests TEST_RESULTS_DIR=$TEST_RESULTS_DIR
Change applied: [33b89b4](https://github.com/mozilla-services/merino-py/pull/118/commits/33b89b408eb093fb76cf580cdb61537d4354d0d2)

Note. I changed the 'store_test_results' path back to a literal. Not sure if it's possible to pass an environment variable.

2022-11-23 18:35 UTC, hackebrot approved these changes
LGTM! 🤖 📈 🚀

2022-11-23 19:10 UTC, merged