refactor: simplify timeout handling for providers
mozilla-services/merino-py pull request #140
Opened 2022-12-05 20:28 UTC by ncloudioj

This is a follow-up for #137, in which I missed @hackebrot's review comments.

2022-12-06 03:19 UTC, mtbottle commented on tests/integration/api/v1/suggest/test_timeout_handling.py
> +def test_with_provider_customized_timeout(
It feels like this test can be parameterized with the test above with a bit of a refactor. In particular, if we add and `expected_timeout_log` and `expected_metrics` (and modify the test itself to use those lists/sets), then we should be able to reuse the test above to add this case.

Short POC:

```
@pytest.mark.parametrize(
    ["providers", "expected_logs", "expected_metrics"],
    [
        (
            {
                "sponsored": SponsoredProvider(enabled_by_default=True),
                "timedout-sponsored": TimeoutSponsoredProvider(enabled_by_default=True),
            },
            [
                "Timeout triggered in the task runner",
                "Cancelling the task: timedout-sponsored due to timeout",
            ],
            {
                "providers.timedout-sponsored.query.timeout",
                "response.status_codes.200",
            },
        ),
    ],
    ids=["timeout_with_provider"],
)
def test_with_timedout_provider(
    mocker: MockerFixture,
    client: TestClient,
    caplog: LogCaptureFixture,
    filter_caplog: FilterCaplogFixture,
    expected_logs: list[str],
    expected_metrics: set[str],
) -> None:

    ...

    # Check logs for the timed out query
    records = filter_caplog(caplog.records, "merino.utils.task_runner")
    logs = [r.__dict__["msg"] for r in records]
    assert logs == expected_logs

    # Check metrics for the timed out query
    metric_keys: list[str] = {call.args[0] for call in report.call_args_list}
    assert expected_metrics.issubset(metric_keys)
```

2022-12-06 03:19 UTC, mtbottle commented on merino/config.py
> +    ),
Hmm... I'm wondering if we will be missing a potential production performance issue if dev or testing environments are consistently going over 200ms? I am also somewhat tempted to make validation simpler by _not_ adding this unless we're actually seeing lots of performance issues with development.

2022-12-06 15:16 UTC, hackebrot requested changes

2022-12-06 15:16 UTC, hackebrot commented on tests/integration/api/v1/suggest/test_timeout_handling.py
> +def test_with_provider_customized_timeout(
I like that idea, @mtbottle! +1 🚀

2022-12-07 01:54 UTC, ncloudioj commented on merino/config.py
> +    ),
> I'm wondering if we will be missing a potential production performance issue if dev or testing environments are consistently going over 200ms?

FWIW, we use a larger timeout in the testing environment (not including contract tests) to avoid potential intermittent test failures in CI due to its instability in computing resources. As for development, I think using a relaxed timeout would actually allow us to understand the real query duration, otherwise, the task runner will time out the request before it gets a chance to finish it.

In addition, since we use the same timeout for stage & production and CI (i.e. contract tests), I believe it's very unlikely to get performance issues sneaked into production. Even if that ever happens somehow, the timeout metrics would capture those right away.

Does that make sense?

2022-12-07 03:20 UTC, mtbottle commented on merino/config.py
> +    ),
> we use a larger timeout in the testing environment (not including contract tests) to avoid potential intermittent test failures in CI due to its instability in computing resources.

Oh interesting. Did we have a history of test instability in CI? I think unit tests and integration tests run on 4CPU/8Gb Docker containers on CircleCI, which _feels_ like it would stable enough (and also these tests have the network calls all mocked out, which reduces instability even more). 

I think the points make sense 👍 . I just wanted to make sure that we're not starting to differentiate the configurations unnecessarily (YAGNI), as maintaining 2 validation code paths, although not super complex, is still introducing complexity to the system.

2022-12-07 03:56 UTC, ncloudioj commented on merino/config.py
> +    ),
Yes, we did run into that several times in CI or even running locally inside the container, and we ended up introducing a couple of delays to avoid the flaky test failures (see [here](https://github.com/mozilla-services/merino-py/blob/main/tests/contract/volumes/client/scenarios.yml#L157)).

> I just wanted to make sure that we're not starting to differentiate the configurations unnecessarily (YAGNI), as maintaining 2 validation code paths, although not super complex, is still introducing complexity to the system.

Agreed. I am also fine with dropping this treatment until the problem arises in the future.

2022-12-07 15:20 UTC, mtbottle commented on tests/integration/api/v1/suggest/test_timeout_handling.py
> +def test_with_provider_customized_timeout(
I have a preference for the parameterized version for a few reasons:

1. Consistency of tests. We can be sure that the same things are checked, which increases confidence in correctness.
2. Maintainability. Tests tend to share a lot of similarities, like how the testee function is invoked, or having similar assert statements. If we make a change to how the provider is invoked (for example), then this will require changes to all the tests. This parameterized version will only need the change in one place. 

>  Though, the downside of doing so is that it might hurt the readability of those two test cases. For example, it may take some time for the readers to figure out the following parameters are used to test

Ya, it's a bit more indirect and requires a bit more time to read and understand.

2022-12-12 17:42 UTC, ncloudioj commented on tests/integration/api/v1/suggest/test_timeout_handling.py
> +def test_with_provider_customized_timeout(
Yeah, I agree with you about the benefits of parametrization, I will refactor this to it perhaps with more parameters to cover some other cases.

One thing that I found awkward about the parametrization is that for the 1st case, we wanted to ensure `providers.timedout-sponsored.query.timeout` was recorded in metrics, whereas for the 2nd case, we wanted to verify `providers.timedout-tolerant-sponsored.query.timeout` should *not* be recorded. Since we can't do `expected_metrics.issubset()` and `not expected_metrics.issubset()`, we will have to list all the metrics for each case.

2022-12-13 10:49 UTC, hackebrot commented
Looks like CI failed for the most recent push due to an issue around dependencies:

```
make: *** [Makefile:19: .install.stamp] Error 1
```

2022-12-13 14:54 UTC, ncloudioj commented on tests/integration/api/v1/fake_providers.py
> +class TimeoutTolerantSponsoredProvider(TimeoutSponsoredProvider):
@hackebrot Thanks for the insights! I understand what your concerns are now, and yeah, I for sure trust your judgment and look forward to seeing the fix :)

2022-12-14 20:04 UTC, hackebrot commented on tests/integration/api/v1/suggest/test_timeout_handling.py
> +@pytest.mark.parametrize(
We could probably increase the readability of this by using a `collections.namedtuple`:

```python
Scenario = namedtuple(
    "Scenario",
    [
        "providers",
        "expected_suggestion_count",
        "expected_logs_on_task_runner",
        "expected_metric_keys",
    ],
)
```

Then define a dict (order should be guaranteed since Python 3.7) for the scenarios:

```python

SCENARIOS: dict[str, Scenario] = {
    # Case I: Only one provider that will time out.
    #
    #   - Expects:
    #     - No suggestions
    #     - Timeout logs recorded in the task runner
    #     - Timeout metrics recorded in the task runner
    "A-timed-out-provider": Scenario(
        providers={
            "timedout-sponsored": TimeoutSponsoredProvider(enabled_by_default=True),
        },
        expected_suggestion_count=0,
        expected_logs_on_task_runner={
            "Timeout triggered in the task runner",
            "Cancelling the task: timedout-sponsored due to timeout",
        },
        expected_metric_keys={
            "providers.timedout-sponsored.query",
            "providers.timedout-sponsored.query.timeout",
            "suggestions-per.request",
            "suggestions-per.provider.timedout-sponsored",
            "get.api.v1.suggest.timing",
            "get.api.v1.suggest.status_codes.200",
            "response.status_codes.200",
        },
    ),
}
```

The decorator would change to:

```python
@pytest.mark.parametrize(
    argnames=[
        "providers",
        "expected_suggestion_count",
        "expected_logs_on_task_runner",
        "expected_metric_keys",
    ],
    ids=SCENARIOS.keys(),
    argvalues=SCENARIOS.values(),
)
```

The benefit of using namedtuples for this is that it's easier to spot what the values for each test parameter for a given test scenario because. What do you think @ncloudioj?

2022-12-15 01:28 UTC, ncloudioj commented on tests/integration/api/v1/suggest/test_timeout_handling.py
> +@pytest.mark.parametrize(
Fancy 👖. TIL💡, thanks!

2022-12-15 10:16 UTC, hackebrot approved these changes
LGTM! 🚀

2022-12-15 14:47 UTC, merged

2022-12-15 14:48 UTC, ncloudioj commented
Thank you both for the review!