[DISCO-2044] Put the log metadata fields into their own objects
mozilla-services/merino-py pull request #141
Opened 2022-12-05 21:08 UTC by mtbottle

This will make it easier to do data validation on fields we send to logger and also encapsulates the logging metadata into extendable objects.

Fixes DISCO-2044

2022-12-05 21:09 UTC, mtbottle commented on merino/utils/log_data_creators.py
> +        return d
Not a fan of this, but I wanted to preserve the `time` as a `datetime` rather than `str`, but it doesn't export nicely. Any suggestions on more elegant ways to do this instead will be appreciated.

2022-12-07 04:54 UTC, Trinaa requested changes
Thank you for picking up this task @mtbottle!

There are a couple more integration tests where we can use these models:
test_error.py::test_error_request_log_data
test_heartbeat.py::test_heartbeat_request_log_data
test_version.py::test_version_request_log_data
test_unsupported::test_unsupported_endpoint_request_log_data
test_providers.py::test_providers_request_log_data

**Note** merging with `main` may be helpful, since it will add unit tests to the mypy scope.

2022-12-07 04:54 UTC, Trinaa commented on tests/unit/utils/test_log_data_creator.py
> +    assert log_data == expected_log_data.dict()
The type of `log_data` should be `RequestSummaryLogDataModel` now I believe and I think then we can keep the assert as is.

```
log_data: RequestSummaryLogDataModel = create_request_summary_log_data(request, message, dt)

assert log_data == expected_log_data
```

2022-12-07 04:54 UTC, Trinaa commented on tests/unit/utils/test_log_data_creator.py
> +    assert log_data == expected_log_data.dict()
Similar to above, I think `log_data` is now type `SuggestLogDataModel`

```
log_data: SuggestLogDataModel = create_suggest_log_data(request, message, dt)

assert log_data == expected_log_data
```

2022-12-07 04:59 UTC, Trinaa commented on merino/utils/log_data_creators.py
> +        return d
Being Devil's advocate... Why preserve the `datetime` type if it creates this overhead?

2022-12-07 12:50 UTC, mtbottle commented on merino/utils/log_data_creators.py
> +        return d
Good question! I wanted to keep the `time` as `datetime` for type checking (ie. ensuring that we don't accept any random string that's not `datetime` formatted when passed into the object). I _think_ it's worth keeping.

2022-12-07 12:59 UTC, hackebrot commented on merino/utils/log_data_creators.py
> +        return d
We can enforce valid datetime `str` values on the pydantic model, I think:
https://docs.pydantic.dev/usage/types/#datetime-types

Attempts to create a new model instance with a `str` value for `time` that doesn't validate against the format should result in an exception.

2022-12-08 16:47 UTC, Trinaa approved these changes

2022-12-08 20:16 UTC, merged

2022-12-09 10:50 UTC, hackebrot commented on merino/utils/log_data_creators.py
> +        return d
Hi @mtbottle! 👋🏻 

Just wanted to check if you've seen my above comment. From what I can tell we can rely on pydantic to validate input parameters for model fields on model instance creation. We can use a `datetime` model field for `time` and then use `.json()` rather than `.dict()` when attaching that to the log message.

See https://docs.pydantic.dev/usage/exporting_models/#modeljson

2022-12-09 14:16 UTC, mtbottle commented on merino/utils/log_data_creators.py
> +        return d
Oh sorry! I saw your comment and thought it was just adding context to my comment. 

> We can use a datetime model field for time and then use .json() rather than .dict() when attaching that to the log message.

Ah ya, this works and is much nicer! I'll update this change to use `.json` instead. Thanks for following up on this!

2022-12-09 14:24 UTC, hackebrot commented on merino/utils/log_data_creators.py
> +        return d
No worries! Thank you, @mtbottle! 🚀