Logging Object to use Separate `datetime` and `str` fields for timestamps
mozilla-services/merino-py pull request #149
Opened 2022-12-13 16:02 UTC by mtbottle

As discussed over Slack with @hackebrot , I think it's worth being explicit about having separate fields for `datetime` object and `str` representation. This will make it clearer in the `dict()` export that we care about the `str` object, but also preserves the implicit validation of the `datetime` Pydantic object.

2022-12-14 14:10 UTC, hackebrot requested changes
Thank you for submitting a pull request for this @mtbottle!

I've added one comment inline. 📝

2022-12-14 14:10 UTC, hackebrot commented on merino/utils/log_data_creators.py
> +        return values["time_input"].isoformat()
There are a few cases that we need to guard against:
1. `time_input` is required but not provided and the `str` value for `time` is provided but not a valid datetime representation
2. `time_input` is provided as a `str` value that is not a valid datetime representation
3. `time_input` is provided, but so is `time`. However we need to infer `time` from `time_obj`

Example code:
1. `LogDataModel(errno=0, time="nope", path="/hello", method="GET")`
2. `LogDataModel(errno=0, time_input="nope", path="/hello", method="GET")`
3. `LogDataModel(errno=0, time_input=datetime.now(), time="nope", path="/hello", method="GET")`

The current implementation:
1. fails with a `KeyError: 'time_input'` rather than the regular `field required (type=value_error.missing)` validation error and `invalid datetime format (type=value_error.datetime)` validation error
2. fails with a `KeyError: 'time_input'` rather than the regular `invalid datetime format (type=value_error.datetime)` validation error
3. does not raise an exception, but ignores the value for `time` that was provided

Note on 1: From what I can tell pydantic doesn't expose the specific datetime validation functionality, but we can use `parse_obj_as(datetime, v)` to attempt to load the provided value into a temporary model and that will run validation.

The code below covered all of these cases when I tested it locally:

```python
@validator("time", always=True, pre=False)
def set_time(cls, v, values, **kwargs):
    """Set the value for the time field based on the value of time_obj."""
    if time_input := values.get("time_input"):
        # A value for `time_input` was provided and pydantic validated and
        # parsed that value into a datetime object.

        if v is not None:
            raise ValueError("time and time_input both specified")

        # Set the value for `time` based on `time_input`
        return time_input.isoformat()

    if v is not None:
        # Attempt to parse the provided value for `time` into a datetime
        # model which will check that the value is a valid representation.
        parse_obj_as(datetime, v)

    return v
```

2022-12-18 19:57 UTC, mtbottle commented on merino/utils/log_data_creators.py
> +        return dt.isoformat()
@hackebrot The last conditional clause of your last comment inspired me to simplify this more. We never _really_ need to use the object, so I think using it as an object only during the validation is sufficient. This avoids the complexity of keeping around an unused `datetime` object, as well as ensuring that both string and object are in sync. When I add `pre=True`, the field doesn't actually gets string validated yet, which makes it easier to treat as if it's a `datetime` field type. I've added some tests below to make sure that we get a `ValidationError` for incorrect times, but also parse the `datetime.isoformat` from the date specified by the input. Let me know what you think!

2022-12-19 19:06 UTC, hackebrot requested changes

2022-12-19 20:37 UTC, mtbottle commented on merino/utils/log_data_creators.py
> +        return dt.isoformat()
Ah, good catch! We don't need `always=True`, so removing it!

2022-12-20 17:02 UTC, hackebrot requested changes
Hi @mtbottle! 👋🏻 

I've added suggestions for the tests. Let me know what you think!

Aside from that this is good to go!

2022-12-20 18:46 UTC, hackebrot approved these changes
Great work, @mtbottle! 🚀

2022-12-20 19:04 UTC, merged