[DISCO-2174] Refactor Merino AdM Protocol and Backends
mozilla-services/merino-py pull request #179
Opened 2023-01-16 21:28 UTC by Trinaa

# Description
* move AdM protocol from `...\adm\provider.py` to `...\adm\backends\protocol.py`
* move `TestBackend` from `...\adm\provider.py` to `...\adm\backends\test_backend.py`
* rename `RemoteSettingsBackend` to `AdmBackend`
* rename `LiveBackend` to `RemoteSettingsBackend`
* inject `merino.config.settings` into AdM `Provider` and `RemoteSettingsBackend`
* add unit tests for `RemoteSettingsBackend` 

**Note**
* Overall test coverage has increased from 97% to 98%

# Issue(s)
#167 | [DISCO-2166](https://mozilla-hub.atlassian.net/browse/DISCO-2174)

2023-01-16 21:29 UTC, Trinaa commented on merino/providers/adm/backends/protocol.py
> +        ...
Note: I changed the protocol, so that Remote Settings `collection` and `bucket` values are passed directly to the backend object

2023-01-17 13:14 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

Thank you for tackling this!

I think this is a step in the right direction, but I encourage you to take it one step further and change how the adMarketplace provider retrieves suggestion content from backends, such as for example Remote Settings.

**Note**: I created [DISCO-2206] to document my proposed high-level architecture for providers-backends-clients in Merino.

For now, here are my observations and what I have in mind for the adM provider:

1. The provider's `query()` method accepts a `q` query parameter with the search term and checks pre-fetched suggestion content stored on `self.suggestions` for a matching result. It does not call the API of the underlying backend directly.
2. We create a `cron.Job` in `initialize()` that periodically calls `_fetch()`, which checks for new suggestion content and updates the provider instance's `self.suggestions`, `self.results`, `self.full_keywords`, and `self.icons` attributes.
3. The `_fetch()` method is what's calling various API methods of the backend: `get()`, `fetch_attachment()`, `get_icon_url()`.

I would argue, that the adMarketplace provider should not have any knowledge of *records*, *attachments*, and *icon URLs*. That's an implementation detail of Remote Settings. Other sources might not have a concept of records and attachments but use other structures to store suggestion content.

Instead the provider needs to call an API that fetches content and returns an object that it can store and use later when querying for a matching suggestion.

```python
"""Protocol for the AdM provider backends."""

from typing import Any, Protocol
from pydantic import BaseModel


class Content(BaseModel):
    """Class that holds the result from a fetch operation."""

    suggestions: dict[str, tuple[int, int]]
    full_keywords: list[str]
    results: list[dict[str, Any]]
    icons: dict[int, str]


class AdmBackend(Protocol):
    """Protocol for a backend that the AdM provider depends on.

    Note: This only defines the methods used by the provider. The actual backend
    might define additional methods and attributes which this provider doesn't
    directly depend on.
    """

    async def fetch(self) -> Content:
        ...
```

An implementation of this would be a Remote Settings backend (omitted code for the sake of readability):

```python
class RemoteSettingsBackend:
    """Backend that connects to a live Remote Settings server."""

    attachment_host: str = ""
    bucket: str
    client: kinto_http.AsyncClient
    collection: str

    def __init__(self, server: str, collection: str, bucket: str) -> None:
        """Init Remote Settings Client."""

    async def fetch_attachment_host(self) -> str:
        """Fetch the attachment host from the Remote Settings server."""

    async def get(self) -> list[dict[str, Any]]:
        """Get records from Remote Settings server."""

    async def fetch_attachment(self, attachment_uri: str) -> httpx.Response:
        """Fetch an attachment from Remote Settings server for a given URI."""

    def get_icon_url(self, icon_uri: str) -> str:
        """Get the URL for an icon."""

    async def fetch(self) -> Content:
        """Fetch suggestion content from Remote Settings."""
        suggestions: dict[str, tuple[int, int]] = {}
        # A list of full keywords
        full_keywords: list[str] = []
        # A list of suggestion results.
        results: list[dict[str, Any]] = []
        # A dictionary of icon IDs to icon URLs.
        icons: dict[int, str] = {}

        # Code that was formerly implemented in the provider's _fetch() method.
        # This calls the other methods defined on the RemoteSettingsBackend.

        return Content(
            suggestions=suggestions,
            full_keywords=full_keywords,
            results=results,
            icons=icons,
            fetched_at=time.time(),
        )
```

Technically, `Content` could have two attributes: `fetched_at` and a single `dict` mapping from a query to a single suggestion. That suggestion dict could hold all relevant information such as the icon URL, the full keyword etc. rather than storing this information in separate lists and dicts. But this probably out-of-scope of this pull request and is something we can address later.

The important piece here is that the architecture enables us to easily swap out the backend for the adM provider without changing the provider itself.

I'd be happy to jump on a call to discuss any questions or concerns you have about this.

[DISCO-2206]: https://mozilla-hub.atlassian.net/browse/DISCO-2206

2023-01-19 00:07 UTC, Trinaa commented
@hackebrot 

I've made the changes to the AdM Protocol as suggested. Please have another look.

Should I create a task for the proposed follow-up changes to `Content` or is there already a task?

2023-01-19 13:01 UTC, hackebrot requested changes

2023-01-19 13:01 UTC, hackebrot commented on tests/unit/providers/adm/conftest.py
> +def fixture_backend_mock(mocker: MockerFixture, adm_suggestion_content: Content) -> Any:
Is there a need for using a mock here rather than defining custom backends that implement the protocol and then raise an exception (instead of `backend_mock.fetch.side_effect = Exception(error_message)`) or return a canned response (rather than `backend_mock.fetch.return_value = adm_suggestion_content`)?

We do that for Wikipedia in `merino/providers/wikipedia/backends/test_backends.py`.

2023-01-19 14:45 UTC, ncloudioj approved these changes
r=nanj. Neat, yet another nice refactor ;)

Also, kudos to @hackebrot for those insightful comments!

2023-01-19 16:57 UTC, Trinaa commented on merino/providers/adm/provider.py
> +            self.content is not None
Change applied: [d45177a](https://github.com/mozilla-services/merino-py/pull/179/commits/d45177a18c2b25109719f09f10acd09d22aa0943)

2023-01-19 16:57 UTC, Trinaa commented on merino/providers/__init__.py
> +                    resync_interval_sec=setting.resync_interval_sec,
Sorry can you clarify what action needs to take place here?
My understanding is that `setting.resync_interval_sec` should map to `settings.providers.adm.resync_interval_sec` in this context...

2023-01-19 16:57 UTC, Trinaa commented on merino/providers/adm/backends/remotesettings.py
> +        """Init Remote Settings Client
Change applied: [d45177a](https://github.com/mozilla-services/merino-py/pull/179/commits/d45177a18c2b25109719f09f10acd09d22aa0943)

2023-01-19 16:58 UTC, Trinaa commented on tests/unit/providers/adm/backends/test_remotesettings.py
> +    ids=["attachment_host_defined", "attachment_host_undefined"],
Change applied: [d45177a](https://github.com/mozilla-services/merino-py/pull/179/commits/d45177a18c2b25109719f09f10acd09d22aa0943)

2023-01-19 16:58 UTC, Trinaa commented on tests/unit/providers/adm/backends/test_remotesettings.py
> +    return httpx.Response(200, text=json.dumps([attachment]))
Yes! Change applied: [d45177a](https://github.com/mozilla-services/merino-py/pull/179/commits/d45177a18c2b25109719f09f10acd09d22aa0943)

2023-01-19 16:58 UTC, Trinaa commented on tests/unit/providers/adm/conftest.py
> +def fixture_backend_mock(mocker: MockerFixture, adm_suggestion_content: Content) -> Any:
I prefer mocking over custom backends, or fakes, here primarily because there is less boilerplate code to create and maintain. It also allows the response to be re-used for verification in this case.

2023-01-19 16:58 UTC, Trinaa commented on merino/providers/adm/backends/protocol.py
> +class Content(BaseModel):
How about SuggestionContent?
Change applied: [d45177a](https://github.com/mozilla-services/merino-py/pull/179/commits/d45177a18c2b25109719f09f10acd09d22aa0943)

2023-01-19 17:44 UTC, hackebrot commented on merino/providers/__init__.py
> +                    resync_interval_sec=setting.resync_interval_sec,
You're right! My bad, sorry. Nevermind. 😁

2023-01-19 18:32 UTC, Trinaa commented on merino/providers/adm/backends/testbackend.py
> +"""Test backend for the AdM provider."""
I re-categorized as fakes. What do you think?
Change applied: [bf2b17b](https://github.com/mozilla-services/merino-py/pull/179/commits/bf2b17bbc316b4b9524dcdc1745925bc6da52c02)

2023-01-19 20:50 UTC, Trinaa commented
Hi @hackebrot! 🤖

> Please create a new task in Jira if you don't mind.

I created the following task [DISCO-2209](https://mozilla-hub.atlassian.net/browse/DISCO-2209). Please modify as you see fit.

2023-01-20 11:17 UTC, hackebrot commented
> Also, kudos to @hackebrot for those insightful comments!

Thank you, @ncloudioj! 😁

2023-01-20 13:45 UTC, Trinaa commented on tests/unit/providers/adm/backends/test_remotesettings.py
> +def fixture_rs_server_info_response() -> dict[str, Any]:
Yes that's right.

2023-01-20 13:59 UTC, merged