WIP: [DISCO-2084] Restructure Top Pick Provider with Backend
mozilla-services/merino-py pull request #187
Opened 2023-01-27 23:17 UTC by taddes

Refactor of Top Picks provider to confirm to new architectural format, with separate 'backend' that handles indexing of local json file.

Summary

- Refactor of Top Pick Provider to segment out logic to an injectable backend
- Restructure static methods into callable module functions
- Refactor unit tests
- Refactor integration tests

2023-02-02 14:13 UTC, taddes commented
Have to make some minor modifications to the integration testing suite as the parametrized version of some previous tests doesn't fit the new architecture.

2023-02-02 15:31 UTC, Trinaa commented on merino/providers/top_picks/backends/top_picks.py
> +            raise e
I notice this PR is still in draft, so please forgive this comment if it's premature. I'd like to visit the Exception handling with an example, following our conversation on Monday.

1. The backends are not responsible for logging. Instead exceptions can be used to propagate messages to the loggers in providers. 

2. In the method `read_domain_list` 
     * When the file doesn't exist, raise the TopPicksError immediately, this will be more efficient than invoking the try/catch context
     * Instead of catching the highest level `Exception`, we can be more specific. According to documentation the [open()](https://docs.python.org/3/library/functions.html#open) method should raise an `OSError` and the [json.load()](https://docs.python.org/3/library/json.html#json.load) method should raise a `JSONDecodeError`. 

3. In the method `fetch`, the try/catch will be catching Exceptions we raised in downstream methods and will be re-raising them, nesting information further in the chain. In this case better to let the exceptions bubble.
     
**Example**
```suggestion
    async def fetch(self) -> TopPicksData:
        """Fetch Top Picks suggestions from domain list."""
        return await asyncio.to_thread(self.build_indices)

    @staticmethod
    def read_domain_list(file: str) -> dict[str, Any]:
        """Read local domain list file"""
        if not os.path.exists(file):
            raise TopPicksError("Local file does not exist")

        try:
            with open(file, "r") as readfile:
                domain_list: dict = json.load(readfile)
                return domain_list
        except OSError as os_error:
            raise TopPicksError(f"Cannot open file '{file}'") from os_error
        except JSONDecodeError as json_error:
            raise TopPicksError(f"Cannot decode file '{file}'") from json_error
```

2023-02-02 17:36 UTC, taddes commented
Hey @Trinaa , no not premature at all, was going to continue that discussion with you regarding the exception handling. I'll add what you provided and we'll get a time to discuss it further. Meanwhile, I can at least make these changes.

2023-02-06 16:48 UTC, ncloudioj commented on merino/configs/default.toml
> +firefox_char_limit = 2
Just noticed that we didn't document those settings for this provider, could you add those to this [section](https://mozilla-services.github.io/merino-py/ops.html#provider-configuration)?

2023-02-06 16:51 UTC, ncloudioj commented on merino/configs/default.toml
> +firefox_char_limit = 2
Another ask for you :), while you're here, can you also add validations for those settings? You can reference existing validators [here](https://github.com/mozilla-services/merino-py/blob/main/merino/config.py#L12-L33). Thanks!

2023-02-06 16:58 UTC, ncloudioj commented on merino/providers/top_picks/backends/protocol.py
> +    results: list[dict]
Nit: I think we can now help the type analyzer (and the readers) with more detailed annotations.
```suggestion
    primary_index: defaultdict[str, list[int]]
    secondary_index: defaultdict[str, list[int]]
    short_domain_index: defaultdict[str, list[int]]
    results: list[dict[str, Any]]
```

2023-02-06 17:04 UTC, ncloudioj commented on merino/providers/top_picks/backends/top_picks.py
> +        self, top_picks_file_path, query_char_limit, firefox_char_limit, score
This could save the following check on `top_picks_file_path` if it wanted to ensure the path is always specified.  
```suggestion
        self, top_picks_file_path: str, query_char_limit: int, firefox_char_limit: int, score: float
```

2023-02-06 17:05 UTC, ncloudioj commented on merino/providers/top_picks/backends/top_picks.py
> +        return top_picks_data
Nit:
```suggestion
        return await asyncio.to_thread(self.build_indices)
```

2023-02-06 17:07 UTC, ncloudioj commented on merino/providers/top_picks/backends/top_picks.py
> +            if not os.path.exists(file):
`open(file, "r")` will throw if the requested file is missing, so maybe we don't need to check its existence here?

2023-02-06 17:13 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +    short_domain_index: defaultdict = defaultdict(list)
Hmm, why do we duplicate those here? Can we just use those indices from `top_picks_data` instead?

2023-02-06 17:16 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +            self.results: list[Suggestion] = [
This duplication also seems a little wasteful to me as now we will keep them both in memory. Is it possible to do the conversion at the index building phase? If not, I think we can also consider dropping `top_picks_data.results` once the conversion is done here.

2023-02-06 17:20 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +        except Exception as e:
Since `backend.fetch()` will only raise `TopPicksError` errors, let's capture those here instead. Also, apart from logging, we might also want to re-throw the exception to let provider initializer handle it rather than silencing it.

2023-02-06 18:18 UTC, ncloudioj commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +    assert Suggestion(**result["suggestions"][0]) == expected_suggestion[0]
```suggestion
    assert [Suggestion(**suggestion) for suggestion in result["suggestions"]] == expected_suggestion
```

2023-02-06 18:31 UTC, Trinaa commented on merino/providers/top_picks/backends/top_picks.py
> +            if not os.path.exists(file):
This or maybe the check can be part of the initialization as part of the value check?

For sure the subsequent action of raising TopPicksError within the try-catch loop is not desirable, as it will trigger the loop context unnecessarily.

2023-02-06 18:35 UTC, ncloudioj commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +    backend_mock: Any = mocker.AsyncMock(spec=TopPicksBackend)
Why not use a dedicated JSON file for this rather than mocking this with those hardcoded variables? Looks like we already have one in `tests/data/top_picks.json`, we can just add another one for integration tests.

2023-02-06 18:37 UTC, ncloudioj commented on tests/unit/providers/top_picks/conftest.py
> +    backend_mock.fetch.return_value = top_picks_data
Ditto: https://github.com/mozilla-services/merino-py/pull/187/files#r1097776152

2023-02-06 19:15 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +            return [res]
I feel like this block is getting harder to follow and take a crack at refactoring it:
```py
ids: Optional[int]
query: str = srequest.query

match len(query):
    case qlen if self.firefox_char_limit <= qlen <= (self.query_char_limit - 1):
        ids = self.short_domain_index.get(query)
    case qlen if self.query_char_limit <= qlen <= self.query_max:
        ids = self.primary_index.get(query) or self.secondary_index.get(query)
    case _:
        ids = None 

return [self.results[ids[0]]] if ids else []
```
Let me know what do you think?

2023-02-06 19:53 UTC, Trinaa requested changes
Hey Taddes, thank you for tackling this refactor!
Send me a ping if you'd like to follow-up on any of the comments I left.

2023-02-06 19:53 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +config = settings.providers.top_picks
I suggest not to set config as a global value, but to set it within a test fixture. Globals can break test isolation. Furthermore, you may consider setting these values outright in the test, as opposed to using the configs.

_\* This also applies to `unit/providers/top_picks/conftest.py`_

2023-02-06 19:53 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +def fixture_top_picks_data() -> TopPicksData:
Is this fixture a duplication of the one in `unit/providers/top_picks/conftest.py`? If yes, then it's declaration can be moved to a `conftest.py` with visibility to both unit and integration tests, for better re-usability.

2023-02-06 19:53 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +    assert Suggestion(**result["suggestions"][0]) == expected_suggestion[0]
Good call Nan, to take it further and avoid the assertion loop, you could do:
```suggestion
    actual_suggestions: list[Suggestion] = [
        Suggestion(**suggestion) for suggestion in result["suggestions"]
    ]
    assert actual_suggestions == expected_suggestion
```

2023-02-06 19:53 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
>  """Integration tests for the Merino v1 suggest API endpoint configured with the
I suggest to add a test to cover the unhappy path case, where the `TopPicksBackend` raises a `TopPicksError`. What should the API return? Status 200 with no suggestions?

2023-02-06 19:53 UTC, Trinaa commented on merino/providers/top_picks/backends/top_picks.py
> +            raise TopPicksError(f"Cannot decode file '{file}'") from json_error
Lines 52 and 54 are not covered by testing. Please add a unit test.

2023-02-06 19:53 UTC, Trinaa commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +    assert not os.path.exists(settings.providers.top_picks.top_picks_file_path)
I suggest to remove `test_local_file_exists` and `test_local_file_not_found`, since they do not test the logic within the `TopPicksBackend` module.

2023-02-06 19:53 UTC, Trinaa commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +    assert result == top_picks_data
Nit: missing types
```suggestion
async def test_fetch(top_picks: TopPicksBackend, top_picks_data: TopPicksData) -> None:
    """Test the fetch method returns TopPickData."""
    result: TopPicksData = await top_picks.fetch()
    assert result == top_picks_data
```

2023-02-06 19:53 UTC, Trinaa commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +    assert len(domain_list["domains"][1]["similars"]) == 5
In the interest of avoiding IO in unit tests. Consider mocking the behaviour of `open`.
Also pytest is good about comparing dictionaries, so you can probably reduce to a single assertion.

2023-02-06 20:28 UTC, taddes commented on merino/configs/default.toml
> +firefox_char_limit = 2
Yah, great call! Adding validators for all and documenting them.

2023-02-06 21:01 UTC, taddes commented on merino/providers/top_picks/provider.py
> +    short_domain_index: defaultdict = defaultdict(list)
I'm keeping naming consistency between the two and while it is repeated between the two, it makes accessing the attribute locally simpler. It avoids the awkwardness of longer lines that result clean statements like this:
```python
       if (
            len(srequest.query) < self.firefox_char_limit
            or len(srequest.query) > self.query_max
        ):
            return []
        if ids := self.primary_index.get(srequest.query):
            res = self.results[ids[0]]
            return [res]
```
Turning into:
```python
       if (
            len(srequest.query) < self.top_picks_data.firefox_char_limit
            or len(srequest.query) > self.top_picks_data.query_max
        ):
            return []
        if ids := self.top_picks_data.primary_index.get(srequest.query):
            res = self.top_picks_data.results[ids[0]]
            return [res]

```
which I find more annoying to read. I can change it if you prefer, I just thought it's more explicit this way.

2023-02-06 21:13 UTC, taddes commented on merino/providers/top_picks/provider.py
> +            self.results: list[Suggestion] = [
Gotcha, only thing is we'd create an anti-pattern because the Backend does not have access to `Suggestion` and it shouldn't, right, given the separation of responsibilities? The construction of Suggestions in other providers happens at the provider level after the 'raw' (in this case, indexed but not Suggestion-ified) data is given to the provider. The alternative is to convert to a suggestion during the query call, what do you think? Is the memory impact sizable? I was going for efficiency in that I wanted to value to be clear and easily referenced in the class so that there's no question what it is, but also that it's ready to provide the suggestion with no conversion like it was in the initial spec.

2023-02-07 14:35 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +    short_domain_index: defaultdict = defaultdict(list)
I see your point, though the duplication still seems unnecessary to me. I think you can either split `top_picks_data` into pieces and store them as instance variables (like what you do here but without storing `top_picks_data` as an instance variable) or just use `top_picks_data`, which I'd prefer, with simplified code paths like I proposed [here](https://github.com/mozilla-services/merino-py/pull/187/files#r1097816817).

2023-02-07 14:48 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +        except Exception as e:
Good call. Actually, I was wondering about the motivation of `TopPicksError`, it doesn't seem to have any specific exceptional behaviors for this backend. Should we just use `BackendError` instead?

2023-02-07 14:57 UTC, ncloudioj commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +def fixture_top_picks_data() -> TopPicksData:
Let's not hardcode the test dataset this way. Any new change to be made in the future would require lots of manual updates. If the existing test dataset is not sufficient for integration tests, feel free to add a new one as I mentioned [here](https://github.com/mozilla-services/merino-py/pull/187/files#r1097776152).

2023-02-07 15:00 UTC, ncloudioj commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +            score=0.25,
If we update the score later, all those tests with `0.25` will break. Let's use the configuration value instead. Please update all other hardcoded scores in this PR as well.

2023-02-07 17:05 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +            score=0.25,
That's sensible, I'll catch anything that seems like a simple change like this. There are instances already in our other provider tests where there are hard-coded values that could break if changes are made, so we'll just have to look out overall. I'll change whatever I see that seems applicable.

2023-02-07 17:15 UTC, taddes commented on merino/providers/top_picks/backends/top_picks.py
> +        self, top_picks_file_path, query_char_limit, firefox_char_limit, score
Yup, got it, just slightly altered assertion and called `del` on the `top_picks_file_path` property in the params fixture to make the `__init__` call still break. Saves a few lines, thanks for the idea!

2023-02-07 19:12 UTC, taddes commented on merino/providers/top_picks/provider.py
> +            self.results: list[Suggestion] = [
Yeah, solid points. I'll just access all properties off `top_picks_data` then so we only need one `await` call for the main data, should be clear enough. I just changed the schema for `TopPicksData` so the query min and max are separate attributes instead of a tuple, so we're not doing weird index checking that could confuse a reader. Coversion taking place when recommendation returned now.

2023-02-07 20:02 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +            self.results: list[Suggestion] = [
Sounds good.

Since now we do conversion at the query time. I think we can drop the `score` field from the raw dict to solve this [review commeint](https://github.com/mozilla-services/merino-py/pull/187/files#r1097775373).

2023-02-09 21:19 UTC, Trinaa commented on merino/providers/top_picks/provider.py
> +        except Exception as e:
You could also do that. I think the name/type of the error brings clarity 'TopPicksError', you know exactly which backend raised that, but it's not essential.

2023-02-09 22:43 UTC, taddes commented on merino/providers/top_picks/backends/top_picks.py
> +            if not os.path.exists(file):
Yeah, I will remove the check since the init will fail if the file is not present. If that's ok with you both. The actual reading of the domain file would throw the TopPicksError anyways, meaning this is probably overkill. We have big problems if the configs point to no file or the wrong file anyway!

2023-02-09 22:45 UTC, taddes commented on merino/providers/top_picks/provider.py
> +        except Exception as e:
Ok, I will catch the `BackendError here then raise the Error. Will update.

2023-02-09 22:54 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +    assert Suggestion(**result["suggestions"][0]) == expected_suggestion[0]
👍 makes sense, the 0th index is the only piece of data anyway but this is indeed easier to read.

2023-02-10 14:50 UTC, taddes commented on merino/providers/top_picks/backends/top_picks.py
> +    score: float
Sure, I know we talked about the merits of this and while it wasn't a big problem to have it in the backend, I've moved it out to provider.

2023-02-10 14:52 UTC, taddes commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +    assert not os.path.exists(settings.providers.top_picks.top_picks_file_path)
I know there isn't a specific block that this tests, but in the case the test file gets removed or something happens with structure, I don't think it actively hurts anything. Ok if I leave it?

2023-02-10 20:24 UTC, taddes commented on merino/providers/top_picks/backends/top_picks.py
> +        """Initialize Top Picks backend."""
👍

2023-02-10 20:29 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
>  """Integration tests for the Merino v1 suggest API endpoint configured with the
As we discussed, realized we don't query on demand like the accuweather provider, so no need. Thanks for the discussion on this one!

2023-02-10 20:30 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +config = settings.providers.top_picks
Definitely makes sense, pulled this out and referenced `settings` instead. Good call!

2023-02-10 21:10 UTC, taddes commented
@Trinaa Thanks a million again for discussing the pending test questions I had, glad we got to resolve them! As for the idea of putting all the shared fixtures in `conftest.py` at the root of the `tests` dir, I can definitely do it, though I do see the benefit to leaving them be in their own scopes. I know I'd have to change `backend_mock`, which is the fixture name within each provider, and in this case it would be `top_picks_mock`. Maybe easier to leave each scoped to its own context because otherwise I'm really filling up that shared conftest file purely for the benefit of the top picks provider.  I'm ok either way with this, but this just occurred to me after we talked.

2023-02-10 21:33 UTC, taddes commented on merino/providers/top_picks/provider.py
> +            return [res]
Hey @ncloudioj . This is a very slick solution, nicely done. I was also playing around with something I thought could be equally readable yet more concise, which is arguably tricky. 

I'm not opposed to changing it to this at all, and though there are a few drawbacks to the existing method at present, it is relatively readable. I have to say given I've now pulled `score` out of the backend and am passing it in after destructuring the TopPicksData, the solution you propose gets a little but more unwieldy. For the sake of accomplishing this refactor, are you comfortable with us tabling this and I can think about it some more? Then we can just change it to this or if I find a solution that is a variation on this theme.  I can make a note and gist of this so we actually revisit this. That or if you think this is the time and place, given you put some serious thought and work into this, we can do it, it just needs a little more tweaking. LMK!

2023-02-10 21:43 UTC, taddes commented on tests/unit/providers/top_picks/conftest.py
> +    backend_mock.fetch.return_value = top_picks_data
Kat and I discussed this and since we are using mock data objects throughout the other providers, we're opting to not use the file, as it's also nice to avoid the I/O calls. However, what's more important is that it's not so much constructing the mock, but rather having the comparison data to verify validity. We spent a good time on this and think it's probably wisest to keep the test data to compare against segmented in the tests, if you're ok with it.

2023-02-10 21:43 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +    backend_mock: Any = mocker.AsyncMock(spec=TopPicksBackend)
See comment below:

2023-02-10 22:12 UTC, ncloudioj commented on tests/unit/providers/top_picks/conftest.py
> +    backend_mock.fetch.return_value = top_picks_data
I am not against using mock objects in general, though I do think this particular mock object would be really hard to maintain if we want to update it in the future. Imagine how many fields we need to manually update if we want to add a new site to it. Let's not do that.

2023-02-10 22:18 UTC, taddes commented on tests/unit/providers/top_picks/conftest.py
> +    backend_mock.fetch.return_value = top_picks_data
Totally, I get that, but for consistency we'd then need to open a ticket to do this for the other providers that create the same mocks, as they manually too set values to compare against in the same way. Also, Kat and I spent a long time trying to debug when converting the mock backend into one that was read by the file to no avail. I know more time could resolve the issue, but I just want to get this refactor over the finish line and optimize after in subsequent tasks. I'm just concerned about over-optimizing at this point and would rather change this in a task after this is done, if that's ok.

2023-02-10 22:33 UTC, taddes commented on tests/unit/providers/top_picks/conftest.py
> +    backend_mock.fetch.return_value = top_picks_data
Ach! @ncloudioj ! I forgot to mention - and I feel this is important so sorry I forgot it - when testing this, I wanted the mocking of objects to emulate how the testing is done across all providers for one. Secondly, I didn't want the 'read' source data from the JSON file to be indexed only to then be compared against itself (the data file), which is why I originally didn't go for reading the file to create the objects. It created a tight coupling as I am both instantiating and testing the same thing, which I felt defeated the purpose of the test.

2023-02-14 17:37 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +def fixture_top_picks_data() -> TopPicksData:
I think this data is needed to verify the `top_picks.fetch()` method at unit test level. It is the 'expected' value.
Once it's there... I don't see harm in re-use (we are already stuck maintaining it)?

It is still duplicated though... Why not move it to top level conftest.py?

2023-02-14 18:13 UTC, Trinaa reviewed
It's a bit lost in the above comments, but the `fixture_top_picks_data()` is still duplicated
[ref](https://github.com/mozilla-services/merino-py/pull/187#discussion_r1106145793)

2023-02-14 18:13 UTC, Trinaa commented on merino/providers/top_picks/backends/top_picks.py
> +            raise TopPicksError(f"Cannot decode file '{file}'") from json_error
This case is showing as uncovered in test metrics. Is it possible you removed a test by accident?

2023-02-14 18:13 UTC, Trinaa commented on tests/unit/providers/top_picks/test_provider.py
>          await top_picks.initialize()
Remove test.
This test is validating a mock, not the Provider.

2023-02-14 19:10 UTC, taddes commented on tests/unit/providers/top_picks/test_provider.py
>          await top_picks.initialize()
Got it! Thx!

2023-02-14 19:14 UTC, taddes commented on merino/providers/top_picks/backends/top_picks.py
> +            raise TopPicksError(f"Cannot decode file '{file}'") from json_error
Yeah, I easily added back the `JSONDecodeError` test, thx! Must have removed it during the refactor.

2023-02-15 02:35 UTC, taddes commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +) -> TopPicksBackend:
Just ended up removing that data entirely. @ncloudioj made great points about just building data from test json file.

2023-02-15 02:36 UTC, taddes commented
Ok @ncloudioj @Trinaa , thanks for all the refactor feedback, excited to be nearly done with this! We should now be good to go. I removed the mock test data, the mocked backends and based everything off of the real backend reading the test data. There were more than enough ways to verify the data and suggestions given what is produced by provider and backend instantiation. Removes a lot of needless bloat.

2023-02-15 14:38 UTC, Trinaa approved these changes
LGTM 🚀 ! (two small things I leave to you)

2023-02-15 14:38 UTC, Trinaa commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +    """Test that the read function fails, raising TopPicksError when OSError captured."""
```suggestion
    """Test that the read function fails, raising TopPicksError when a JSONDecodeError is captured."""
```

2023-02-15 14:38 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +def fixture_providers(backend: Any, top_picks_parameters: dict[str, Any]) -> Providers:
```suggestion
def fixture_providers(
    backend: TopPicksBackend, top_picks_parameters: dict[str, Any]
) -> Providers:
```

2023-02-15 14:45 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> +def fixture_providers(backend: Any, top_picks_parameters: dict[str, Any]) -> Providers:
👍

2023-02-15 14:45 UTC, taddes commented on tests/unit/providers/top_picks/backends/test_top_picks.py
> +    """Test that the read function fails, raising TopPicksError when OSError captured."""
👍

2023-02-15 14:46 UTC, taddes commented
Awesome, thanks @Trinaa ! If there's nothing more @ncloudioj , I will merge after those small changes Kat mentioned.

2023-02-15 15:31 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +
```suggestion
```

2023-02-15 15:41 UTC, ncloudioj requested changes
One more thing we need to handle, other than that, it looks great!

2023-02-15 15:41 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +            logger.warning(
If a `BackendError` gets raised, this will leave `self.top_picks_data` undefined. We need to how to handle it.
- We can propagate the exception and let the application fail to start
- Or we can ignore it and retry `backend.fetch()` later, though we need to set an empty value for `this.top_picks_data`, otherwise, the subsequent calls on `query()` will fail

Since we're using a local file now, retrying is perhaps not gonna help that much. I think we can go with the first option. If the fetch fails, let's just crash the app.

Does that make sense?

2023-02-15 16:34 UTC, taddes commented on merino/providers/top_picks/provider.py
> +            logger.warning(
Gotcha. Yeah, so shall I simply raise an exception (re raise) within the except block to crash the app? Conversely, I suppose having an empty list of suggestions instantiated,  should the backend data return noting seems decent too, we'd still get the log, but not crash.

2023-02-15 20:21 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +            logger.warning(
Yeah, re-raise the exception and crash sounds reasonable in this case. If the JSON file is problematic, we should let it fail fast and hopefully we can capture it before it hits production. If this somehow happens in production, the crash is also fine as another merino instance will be spawned later.

2023-02-15 21:37 UTC, taddes commented on merino/providers/top_picks/provider.py
> +            logger.warning(
Done @ncloudioj . Re -aises and passes context of `backend_error`, traceback very clear:

``` 
 File "/Users/taddeskorris/Documents/code/mozilla/merino-py/merino/providers/top_picks/provider.py", line 51, in initialize
    raise BackendError(
merino.exceptions.BackendError: Failed to fetch data from Top Picks Backend. Cannot decode file 'dev/top_picks.json'
```

2023-02-15 21:50 UTC, ncloudioj commented on merino/providers/top_picks/provider.py
> +            raise BackendError(
Nit: you can just do `raise backend_error`.

2023-02-15 21:52 UTC, ncloudioj approved these changes
Looks great! Just two minor nits.

Thanks! :shipit:

2023-02-15 22:21 UTC, merged