DISCO-2205 fix: decouple accuweather and weather settings
mozilla-services/merino-py pull request #191
Opened 2023-02-09 01:23 UTC by tiftran

2023-02-09 14:24 UTC, mtbottle approved these changes
LGTM!

2023-02-09 14:25 UTC, Trinaa commented on docs/ops.md
>      or not this provider is enabled by default.
We should add a `backend` entry

```
  - `backend` (`MERINO_PROVIDERS__ACCUWEATHER__backend`) - The backend of the provider.
    Either `accuweather` or `test`.
```

2023-02-09 14:25 UTC, Trinaa commented on docs/ops.md
>  - Accuweather - Providers weather suggestions & forecasts from Accuweather.
Nit
```suggestion
- AccuWeather - Provides weather suggestions & forecasts.
```

2023-02-09 14:25 UTC, Trinaa commented on docs/ops.md
>      for weather forecasts. This will override the default query timeout
Nit
```suggestion
  - `query_timeout_sec` (`MERINO_PROVIDERS__WEATHER__QUERY_TIMEOUT_SEC`) - A floating
    point (in seconds) indicating the maximum waiting period when Merino queries
    for weather forecasts. This will override the default query timeout.
```

2023-02-09 14:25 UTC, Trinaa commented on merino/providers/__init__.py
> +    WEATHER = "weather"
I think this may change the query path that Firefox has to use... 
Running locally I had to change the `provider` to equal "weather" instead of "accuweather" in the URL. Maybe a good idea to coordinate on this.

2023-02-09 14:27 UTC, Trinaa requested changes
I detect a breaking change with the URL, just want to make sure that's checked on.
Thank you for doing this work Tif, the settings make more sense now.

2023-02-09 14:46 UTC, ncloudioj commented on merino/providers/__init__.py
> +    WEATHER = "weather"
Let's keep the provider ID unchanged for now as this feature is still under foxfooding.

2023-02-09 15:49 UTC, Trinaa commented on merino/providers/__init__.py
> +    WEATHER = "weather"
Yes true, we would still have to remove 'ACCUWEATHER' from Merino, when/if the change is made in Firefox. Leaving it for another day is probably easier. Sry @tiftran Code by Committee...

2023-02-09 19:38 UTC, ncloudioj commented on merino/providers/__init__.py
> +                providers["weather"] = WeatherProvider(
Looks like we have two options here:

- Option A: make a duplicate record to cover both cases, and then drop the "accuweather" one once Firefox is done using it. I guess this duplication will break some unit tests, so we will have to handle those as well.
```
provider = WeatherProvider(...)
providers["weather"] = provider
providers["accuweather"] = provider
``` 

- Option B. Just name it "accuweather" (i.e. `providers["accuweather"] = WeatherProvider(...)`) for now and rename it to "weather" later once Firefox changes that provider name.

I'd prefer B, what do you think? @tiftran @Trinaa

2023-02-09 19:39 UTC, ncloudioj approved these changes
LGTM, just one comment to be resolved.

2023-02-09 19:58 UTC, tiftran commented on merino/providers/__init__.py
> +    WEATHER = "weather"
sooo given that we want to keep "accuweather" as the provider name.
Then we would need to call the configs settings something else? (or i can be completely wrong about this...." `*.providers.accuweather` and `*.accuweather_backend`, how does that sound? @Trinaa @ncloudioj

2023-02-09 20:14 UTC, ncloudioj commented on merino/providers/__init__.py
> +    WEATHER = "weather"
I think we can leave those two config sections as is, we can name them whatever we want, only the keys (i.e. the actual provider name) of the `merino.providers.providers` dict matter.

2023-02-09 20:47 UTC, ncloudioj commented on merino/configs/testing.toml
> +[test.providers.accuweather]
```suggestion
[testing.providers.accuweather]
```

2023-02-09 20:50 UTC, ncloudioj commented on merino/configs/default.toml
> +[default.accuweather_be]
Noticed that you didn't update those in `docs/op.md`, maybe we just call it `default.accuweather`?

2023-02-09 20:58 UTC, tiftran commented on merino/configs/default.toml
> +[default.accuweather_be]
eek you're right

2023-02-09 21:11 UTC, Trinaa commented on merino/providers/__init__.py
> +                providers["weather"] = WeatherProvider(
I'll leave it up to @tiftran ;)

2023-02-09 21:12 UTC, Trinaa approved these changes

2023-02-10 03:53 UTC, ncloudioj commented
@tiftran It just occurred to me that before we merge this change, we will need to update the environment variable [here](https://github.com/mozilla-services/cloudops-infra/blob/master/projects/merino/k8s/charts/merinopy/templates/secret.yaml#L15).

2023-02-13 15:53 UTC, merged