DISCO-2175 Optimize fetching current conditions and forecast data
mozilla-services/merino-py pull request #198
Opened 2023-02-15 07:39 UTC by tiftran

2023-02-15 15:25 UTC, Trinaa requested changes

2023-02-15 15:25 UTC, Trinaa commented on merino/providers/weather/backends/accuweather.py
> +                forecast = tg.create_task(self.get_forecast(client, location.key))
**1. Weak References**
In the [documentation](https://docs.python.org/3/library/asyncio-task.html#creating-tasks) there is a warning about task assignments using _weakref_. I'm not sure if that applies here? Do we need to save references to these tasks because we use the result?

**2. Exception Groups**
In the [documentation](https://docs.python.org/3/library/asyncio-task.html#task-groups) it indicates that multiple exceptions will be combined in an ExceptionGroup. When I force `get_current_conditions` and `get_forecast` to both raise exceptions I get an "Internal Server Error". I think we need to handle this specifically and I think adding a unit test to cover this case would be a good idea.

Pic of my console blowing up 😆 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/3422688/219071604-cdbc4660-1abc-46a4-add5-33a7ecdc1c88.png">

2023-02-15 16:14 UTC, tiftran commented on merino/providers/weather/backends/accuweather.py
> +                forecast = tg.create_task(self.get_forecast(client, location.key))
🙈

2023-02-15 16:35 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +                forecast = tg.create_task(self.get_forecast(client, location.key))
No worries, `except*` comes to the rescue to handle exception groups.

```py
try:
    async with asyncio.TaskGroup() as tg:
    task_current = tg.create_task(self.get_current_conditions(client, location.key))
    task_forecast = tg.create_task(self.get_forecast(client, location.key))
except* AccuweatherError as ae:  # looks like this is the only error we need to handle
    # some error handling
else:
    # happy path, let's grab the results
    current = await current
    forecast = await forecast 
```
Per its doc, if any exception happened to a task, TG will cancel all the ongoing tasks in the group, which is exactly what we

2023-02-15 16:38 UTC, ncloudioj commented on pyproject.toml
> +asyncio = "^3.4.3"
`asyncio` is part of python's standard library, no need to install separately.

2023-02-15 17:38 UTC, Trinaa commented on merino/providers/weather/backends/accuweather.py
> +                forecast = tg.create_task(self.get_forecast(client, location.key))
No worries @tiftran. I'm learning here along with you and it's great stuff!

2023-02-16 05:48 UTC, tiftran commented on merino/providers/weather/backends/accuweather.py
> +                forecast = tg.create_task(self.get_forecast(client, location.key))
okie doke, this has been fun. I don't think we want `except* AccuweatherError`, since we're handling an AccuweatherError to raise an AccuweatherError? It also doesn't "disolve"(?) the ExceptionGroup either.
```
>>> 
>>> def f():
...     raise BaseExceptionGroup("unhandled errors in a TaskGroup", [KeyError(), KeyError()])
... 
>>> try:
...     f()
... except* KeyError as e:
...     raise KeyError("hello")
... 
  | ExceptionGroup:  (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<stdin>", line 2, in <module>
    |   File "<stdin>", line 2, in f
    | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
    +-+---------------- 1 ----------------
      | KeyError
      +---------------- 2 ----------------
      | KeyError
      +------------------------------------
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "<stdin>", line 4, in <module>
    | KeyError: 'hello'
    +------------------------------------

```

2023-02-16 14:05 UTC, Trinaa commented on merino/providers/weather/backends/accuweather.py
> +            if current and forecast:
Is this allowed?
```suggestion
if (current := await task_current) and (forecast := await task_forecast):
```

What was the verdict on _weakref_? Does it apply?

2023-02-16 14:13 UTC, Trinaa commented on merino/providers/weather/backends/accuweather.py
> +                forecast = tg.create_task(self.get_forecast(client, location.key))
My console doesn't blow up anymore! 🚀 
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/3422688/219388201-06f029bb-85f0-4434-87a9-a15c4157235f.png">

2023-02-16 14:14 UTC, Trinaa approved these changes
I don't want to block. Please update the test before merge.

2023-02-16 15:15 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +            except BaseExceptionGroup as e:
`ExceptionGroup` should be sufficient here.
```suggestion
            except ExceptionGroup as e:
```

2023-02-16 15:17 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +                raise AccuweatherError(f"err:{e.exceptions}")
```suggestion
                raise AccuweatherError(f"Failed to fetch weather report: {e.exceptions}")
```

2023-02-16 15:25 UTC, ncloudioj commented on tests/unit/providers/weather/backends/test_accuweather.py
> +from builtins import BaseExceptionGroup
s/BaseExceptionGroup/ExceptionGroup/. Also, not need to import it.

2023-02-16 15:31 UTC, taddes commented on merino/providers/weather/backends/accuweather.py
> +            if current and forecast:
Very snazzy Pythonic approach @Trinaa 👏

2023-02-16 15:32 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +            if current and forecast:
I think it is. We can do:
```py
    return (
        WeatherReport(
            city_name=location.localized_name,
            current_conditions=current,
            forecast=forecast,
        )
        if (current := await task_current) and (forecast := await task_forecast)
        else None
    )
```

2023-02-16 17:22 UTC, tiftran commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    assert expected_error_value in str(accuweather_error.value)
okie doke

2023-02-16 17:22 UTC, tiftran commented on tests/unit/providers/weather/backends/test_accuweather.py
> +from builtins import BaseExceptionGroup
oh pycharm lol

2023-02-16 23:12 UTC, merged