Feature Flags using Dynaconf
mozilla-services/merino-py pull request #22
Opened 2022-08-19 17:37 UTC by quiiver

As a little bit of a side quest, I wrote a basic implementation of featureflags using dynaconf as the configuration system. It is a simple implementation that supports two bucketing schemes `random` and `session`. Random does what it says on the tin. It generates a random bucketing id for every flag check. Session bucketing uses the session id of the request as the bucketing key so that feature checks within a given search session would be consistent. Each flag has a very simple configuration:

```
[default.flags.<flag_name>]
scheme = 'session'
enabled = 0.5 
```
`scheme` - This is the bucketing scheme for the flag. Allowed values are 'random' and 'session'
`enabled` - This represents the % enabled for the flag and must be a float between 0 and 1

2022-08-22 17:19 UTC, ncloudioj commented on merino/featureflags.py
> +        if enabled <= 0.0 or enabled > 1.0:
I guess that the passed-in `flags` argument in `__init__` and this check here is mainly for testing, correct? For other scenarios, feature flags will be defined by `flags.toml` or env vars. Either way, this can also be checked and enforced by Dynaconf's validator like what we've done [here](https://github.com/mozilla-services/merino-py/blob/main/merino/config.py#L4-L10). Can you add a validator for this?

2022-08-22 18:56 UTC, ncloudioj commented on merino/featureflags.py
> +class FeatureFlags:
Do you mind adding some documents here, like the PR summary?

2022-08-22 18:58 UTC, ncloudioj commented on merino/featureflags.py
> +        if enabled <= 0.0 or enabled > 1.0:
The `scheme` field can be validated by an enum of `["random", "session"]` as well.

2022-08-22 21:07 UTC, quiiver commented on merino/featureflags.py
> +        if enabled <= 0.0 or enabled > 1.0:
I added validators but i'm not entirely sure the appropriate way to test them.

2022-08-22 21:08 UTC, quiiver commented on merino/featureflags.py
> +        if enabled <= 0.0 or enabled > 1.0:
Also, I switched to using a `testing` environment instead of passing in the flags

2022-08-23 00:10 UTC, ncloudioj commented on merino/middleware/featureflags.py
> +    Sets the a ContextVar for session_id so that it can be used
```suggestion
    Sets a ContextVar for session_id so that it can be used
```

2022-08-23 00:13 UTC, ncloudioj commented on merino/featureflags.py
> +    def is_enabled(self, flag: str, bucket_for: str | bytes | None = None) -> bool:
Since this is the main method of `FeatureFlags`, can you add a few descriptions for the arguments of this function?

2022-08-23 00:14 UTC, ncloudioj commented on merino/featureflags.py
> +        As a principal it fails closed as quickly as possible.
```suggestion
        As a principal, it fails as quickly as possible.
```

2022-08-23 00:23 UTC, ncloudioj commented on merino/configs/flags/default.toml
> +# scheme="random"
Nit: let's add some brief comments here for each configuration, e.g. what possible values (range) it could take. This allows folks to make quick changes with enough context without further looking into the more detailed doc in `FeatureFlags.py`.

2022-08-23 00:43 UTC, ncloudioj commented on merino/featureflags.py
> +        if enabled <= 0.0 or enabled > 1.0:
Using the testing environment is a good idea. Alternatively, I think we can also mock out `_config.flags` by using the `mocker` fixture.

```py
import merino.featureflags import _flags

def test_foo(mocker):
    mocker.patch.object(_config, 'flags', {"test-enabled": { "enabled": 1, "scheme": "random" }})

    flags = FeatureFlags()
    assert flags.is_enabled("test-missing") is False    
```

2022-08-23 00:48 UTC, ncloudioj commented on merino/featureflags.py
> +        self, scheme: str, bucket_for: str | bytes | None
Nit: let's change `_get_bucketing_id()`, `_get_random()`, `_get_digest()`, and `_bytes_to_interval()` to static methods as none of them need `self`.

2022-08-23 01:04 UTC, ncloudioj commented on merino/featureflags.py
> +                return cast(bytes, bucket_for)
Shall we throw over here when seeing an invalid `bucket_for` type rather than return `None` implicitly? If we expect it to be either str or bytes if present, having other types sounds like a bug to me, and I think we should fail loud.

2022-08-23 01:18 UTC, ncloudioj commented on merino/featureflags.py
> +        max = 1 << len(bucketing_id)  # this should always be 32 bytes long
If `bucketing_id` is guaranteed (enforced by `_get_bucketing_id()`) to be 32 bytes long, why not use a constant here?

2022-08-23 02:46 UTC, ncloudioj commented on merino/featureflags.py
> +        for i in bucketing_id:
Out of curiosity, is this a known algorithm? It's kinda fascinating.

I thought that perhaps some bit shifting could be a little faster than an if statement, though the benchmark didn't suggest so. Actually, it was always 5-10% slower 😂

```py
def branch_free(bs):
    out = 0
    for i, b in enumerate(bs):
        out |= (b >> 7) << i   # (31 - i) would yield the same result as the original 
    return out / (1 << 32)
```

2022-08-23 02:52 UTC, ncloudioj commented on tests/test_featureflags.py
> +    assert flags.is_enabled("test-missing") is False
Usually, we'd just do `assert [!]predicate` if the `predicate` is of type boolean. Any particular reason for using `is True/False` here?

2022-08-23 02:56 UTC, ncloudioj commented on tests/test_featureflags.py
> +    for bid, test in assertions.items():
Nit: you can also do [`@pytest.mark.parameterize`](https://docs.pytest.org/en/6.2.x/parametrize.html) for this. It pretty much does the same thing with less boilerplate and it will display all test combinations in the test results.

2022-08-23 02:57 UTC, ncloudioj requested changes
Sorry for the delay, got distracted earlier.

It looks good, just had a few comments and nits for your consideration.

2022-08-23 13:18 UTC, hackebrot requested changes
Hi @quiiver! 👋🏻 

Thank you for tagging me on this. I added my comments inline.

2022-08-23 14:04 UTC, quiiver commented on merino/featureflags.py
> +                return cast(bytes, bucket_for)
We could throw here but I wouldn't want those exceptions to bubble up past `is_enabled`. I don't want `is_enabled` checks to ever throw. They should fail to False to prevent extra branching around catching exceptions for every flag check. I would be down with adding logging or metrics in situations like this. that would allow us to have visibility into issues

2022-08-23 14:06 UTC, quiiver commented on tests/test_featureflags.py
> +    assert flags.is_enabled("test-missing") is False
I'm just not terribly familiar with the correct patterns so i usually default to the most explicit :D

2022-08-23 14:07 UTC, quiiver commented on tests/test_featureflags.py
> +    for bid, test in assertions.items():
parameterize sounds great, thanks for the heads up

2022-08-23 14:25 UTC, quiiver commented on Makefile
> +	MERINO_ENV=testing $(POETRY) run pytest -v $(TEST_DIR) --cov $(APP_DIR)
Yeah I waffled a bit on that and eventually landed on setting it via the environment variable. since we will be defining production environments with env variables it felt like a good opportunity to 'test' that out. The other reason was that directly calling functions on the `settings` module generated a deprecation warning about not modifying the settings module directly

2022-08-23 14:27 UTC, quiiver commented on merino/featureflags.py
> +        max = 1 << len(bucketing_id)  # this should always be 32 bytes long
I should change that comment but the reason for the length check is because with adhoc bucketing ids we don't enforce a length.

2022-08-24 17:12 UTC, quiiver commented on merino/featureflags.py
> +        if (bucketing_id := self._get_bucketing_id(bucket_scheme, bucket_for)) is None:
scheme is not optional and defaults to 'session'

2022-08-24 17:18 UTC, quiiver commented on merino/featureflags.py
> +    validators=[
I want to continue using dynaconf and not add another configuration system but I agree with you on the validation. I can try to spend some more time looking at how to use pydantic with dynaconf for additionally structure / schema

2022-08-24 19:15 UTC, ncloudioj commented on merino/featureflags.py
> +                    raise RuntimeError(
Maybe this is a `TypeError`?

2022-08-24 19:19 UTC, ncloudioj commented on merino/featureflags.py
> +                    raise RuntimeError(
It sounds like a `ValueError` to me. Actually, maybe we can define an Enum for `scheme`.

2022-08-24 19:35 UTC, ncloudioj commented on merino/middleware/featureflags.py
> +        session_id_context.set(str(session_id))
```suggestion
        session_id_context.set(session_id)
```

`request_params.get("sid")` is already a str if present.  If `sid` is not set in `request.query_params`, `str(session_id)` will produce a string `"None"` which is probably not what we want to set for `session_id_context`.

2022-08-24 19:37 UTC, ncloudioj approved these changes
LGTM. r+ with a few more comments.

2022-08-24 20:14 UTC, quiiver commented on merino/featureflags.py
> +    validators=[
Updated to use BaseModel for both `FeatureFlag` and `FeatureFlagConfig`.

2022-08-24 20:22 UTC, quiiver commented on merino/featureflags.py
> +            RuntimeError
```suggestion
            TypeError, ValueError
```

2022-08-25 16:58 UTC, hackebrot requested changes
Hi @quiiver! 👋🏻 

This is great! I have added one suggestion for the `scheme` default value, but then is good to go from my side.

2022-08-25 16:58 UTC, hackebrot commented on merino/featureflags.py
> +                return True
Interesting! The GitHub syntax highlighting for this seems to be broken, but I don't see any syntactical errors here.

2022-08-25 16:58 UTC, hackebrot commented on merino/featureflags.py
> +        Takes an arbitrarily long bytearray and maps it to a float between [0,1)
```suggestion
        Takes an arbitrarily long bytearray and maps it to a float between [0, 1].
```

2022-08-25 16:58 UTC, hackebrot commented on merino/featureflags.py
> +    default_scheme: BucketingScheme = BucketingScheme.session
See comment above.

2022-08-25 16:58 UTC, hackebrot commented on merino/featureflags.py
> +    validators=[
Looks good! Thanks! 👍🏻

2022-08-25 18:11 UTC, quiiver commented on merino/featureflags.py
> +        Takes an arbitrarily long bytearray and maps it to a float between [0,1)
that's not a typo its how you noteate an interval range that includes the upper boundary https://en.wikipedia.org/wiki/Interval_(mathematics)#Notations_for_intervals

2022-08-25 18:12 UTC, quiiver commented on merino/featureflags.py
> +    scheme: Optional[BucketingScheme]
I'll check but i believe mypy doesn't understand that it will never have a None value so it complains when you use `Flag.scheme` directly

2022-08-26 11:13 UTC, hackebrot commented on merino/featureflags.py
> +        Takes an arbitrarily long bytearray and maps it to a float between [0,1)
TIL! 💡

2022-08-26 11:19 UTC, hackebrot commented on merino/featureflags.py
> +    scheme: Optional[BucketingScheme]
Right, we can drop `Optional` and make it:

```python
scheme: BucketingScheme = BucketingScheme.session
```

2022-08-26 12:53 UTC, quiiver commented on merino/featureflags.py
> +    scheme: Optional[BucketingScheme]
done

2022-08-26 12:55 UTC, hackebrot approved these changes
LGTM! 🚀

2022-08-26 14:47 UTC, merged