[DISCO-2231] Expand Merino-py load test to include Top-Picks
mozilla-services/merino-py pull request #221
Opened 2023-03-02 23:45 UTC by Trinaa

**THIS STACKS ON https://github.com/mozilla-services/merino-py/pull/214**

# Description
* Add support for load testing the Top Picks provider

# Issue(s)
#207 | [DISCO-2231](https://mozilla-hub.atlassian.net/browse/DISCO-2231)

2023-03-03 16:37 UTC, taddes requested changes
Looks good @Trinaa , excellent work! I have a few suggestions on how we construct the query terms as I don't think we need to fuss with the indexes, along with that a few small changes. Thanks for implementing this for Top Picks! 🥇

2023-03-03 16:37 UTC, taddes commented on tests/load/locust_tests/locustfile.py
> +    "MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH"
Just as above, we could avoid the `os.environ` calls by accessing the `settings` object returned from importing `merino.config`. Again, not a huge issue. May I ask why we're using the Dynaconf-style access of these config vars? Likely a good reason and I'd like to know!

2023-03-03 16:37 UTC, taddes commented on tests/load/locust_tests/locustfile.py
> +    return list(query_dict.values())
I just feel that defining the key within the dict iteration as `query` a bit harder to follow, since we're then appending it to `queries` which sits outside the iteration. Just a nit, I think it makes it a bit easier to read.

On the other hand, if with these load tests we are only concerned with terms that will return a valid suggestion, since it looks like at the end you're just getting the values from `query_dict`, why not just construct a list in the first place? It doesn't look like we're accessing the full suggestion term from `results`, which would be the only reason why we need to reference the list of integers. The list of integers point to the result, which we fetch the 0th index of.  Correct me if I'm wrong and made a bad assumption here, but I don't think we need to deal with the result ids to get the terms.

```suggestion
    def add_queries(index: dict[str, list[int]], query_terms: list[str]):
        for search_term in index.keys():
                query_terms.append(search_term)

    query_list: list[str] = []
    add_queries(data.short_domain_index, query_list)
    add_queries(data.primary_index, query_list)
    add_queries(data.secondary_index, query_list)
  
    return query_list
```
=================
If we opt not to do the above, I'd just ask we change some of the variable names.

I think the use of `query` and `queries` here is a tiny bit confusing.  These do indeed become queries, but in the process of constructing the data, I think it's better to be clear that they are search terms. Given the data set we are accessing is the strings that eventually become the queries and their numeric indexes which point to the original term, I'd recommend `search_term` or `keyword`:
```suggestion
    def add_queries(index: dict[str, list[int]], query_terms: dict[int, list[str]]):
        for search_term, result_ids in index.items():
            for result_id in result_ids:
                query_terms.setdefault(result_id, []).append(search_term)

    query_dict: dict[int, list[str]] = {}
    add_queries(data.short_domain_index, query_dict)
    add_queries(data.primary_index, query_dict)
    add_queries(data.secondary_index, query_dict)

    return list(query_dict.values())
```

2023-03-03 21:15 UTC, Trinaa commented on tests/load/kubernetes-config/locust-master-controller.yml
> +              value: [MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH]
No it doesn't, but I see your attention to derail 😸 

The value of `MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH` is consistently a string, which is the supported type between shell scripts, kubernetes yaml files and python code. However `MERINO_PROVIDERS__TOP_PICKS__QUERY_CHAR_LIMIT` and `MERINO_PROVIDERS__TOP_PICKS__FIREFOX_CHAR_LIMIT` are ints and we have to pass them along as string explicitly, hence the quotes, until we can explicitly cast them in the python code.

2023-03-03 21:16 UTC, Trinaa commented on tests/load/kubernetes-config/locust-worker-controller.yml
> +              value: [MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH]
No it doesn't. See [comment](https://github.com/mozilla-services/merino-py/pull/221#discussion_r1125017229).

2023-03-03 21:16 UTC, Trinaa commented on tests/load/locust_tests/locustfile.py
> +        providers: str = "top_picks"
The load tests are an independent solution and configurations are managed differently. Re-using the .toml files is not readily available at the moment, but could be a explored in the future.

2023-03-03 21:17 UTC, Trinaa commented on tests/load/locust_tests/locustfile.py
>  )
See [comment](https://github.com/mozilla-services/merino-py/pull/221#discussion_r1125018185) about configs.

2023-03-03 21:17 UTC, Trinaa commented on tests/load/kubernetes-config/locust-master-controller.yml
>                value: merino
See [comment](https://github.com/mozilla-services/merino-py/pull/221#discussion_r1125018185) about configs.

2023-03-03 21:18 UTC, Trinaa commented on tests/load/locust_tests/locustfile.py
> +    return list(query_dict.values())
Ultimately, I would like to keep `query` and `queries` as the terminology, because it conveys the link between these values and the `query` parameter in the request_suggestions method.

This value is used throughout the module and I think there is value in keeping the consistency.

2023-03-03 21:20 UTC, Trinaa commented
@taddes Ready for your re-review. Let me know if I didn't address all your concerns.

Something to remember in contract-tests and load-tests, is that while we are attempting to re-use things from the `merino`, that these are in-fact independent solutions. They have different configuration mechanisms.

2023-03-03 22:18 UTC, taddes commented on tests/load/kubernetes-config/locust-master-controller.yml
> +              value: [MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH]
Ah, I had a feeling it might be something like that!

2023-03-03 22:18 UTC, taddes commented on tests/load/locust_tests/locustfile.py
> +        providers: str = "top_picks"
Ok, sounds good! Not the biggest deal anyway, but I thought to suggest it in case it were desired at this point. LGTM!

2023-03-03 22:24 UTC, taddes commented on tests/load/locust_tests/locustfile.py
> +    return list(query_dict.values())
Sure, that's fine, I was thinking more from the perspective of the operator and keeping that consistent but I'm ok with queries then!

As for the use of a list and only iterating through the strings provided in the indexes, what were your thoughts? That's the first suggestion above this one that just suggested the terminology change. I know those multiple possible indexes would show overlap in some search terms (say ama being for 'ama' and 'amazon') and we would possibly miss a few, but it's marginal at best. Do we need the above method using the dict if we're only accessing the values in the end? Since we use choice to just pick them, we don't necessarily need all of those overlapping keywords.

2023-03-03 22:26 UTC, taddes approved these changes
All looks good and I have approved as is, but I did land a comment regarding the method that collects possible queries from the suggestion keys. More context in that comment, but I just don't know if we need the extra iteration and use of dicts if all we care in the end are the query strings. I don't want to block, so I am approving, but if you could let me know your thoughts on that, that'd be great. Good work!

2023-03-06 15:57 UTC, Trinaa commented on tests/load/locust_tests/locustfile.py
> +    return list(query_dict.values())
> As for the use of a list and only iterating through the strings provided in the indexes, what were your thoughts? 

A flat list of query terms would not work with the current load test design, which requires a QueryList, essentially a list[list[str]]. The load test groups related query strings together and submits them subsequently, in increasing length, to better simulate real world scenarios, where we get 1 keystroke at a time.

2023-03-06 16:00 UTC, Trinaa commented
@taddes thank you for the review 😸. Please see the above [explanation](https://github.com/mozilla-services/merino-py/pull/221#discussion_r1126661220) regarding query collection.

2023-03-06 16:01 UTC, merged