[DISCO-2254] Add keyword to Docker image tag for running load tests
mozilla-services/merino-py pull request #223
Opened 2023-03-04 00:11 UTC by taddes

# Description
* Add tagging functionality to trigger load tests.
The tag should take the form [load test: (abort|warn)]. 
The abort flag will prevent a stage deployment should the load test fail. 
The warn flag will output a Slack warning should the load test fail, but still allow for the stage deployment.

# Changes
* Added shell script commands
* Annotated commands with comments
* Updated contributing docs
* Updated release-process.md docs

# Issue(s)
#222 | [DISCO-2254](https://mozilla-hub.atlassian.net/browse/DISCO-2254)

2023-03-06 18:37 UTC, taddes commented on .circleci/config.yml
> +          name: Push to Docker Hub & check for Load Test flag
If it's ok with you, I'd like to leave it as it points out what the below operation is doing. Technically it does just push to Docker Hub, but given this is a step that's triggered by reading the commit string details, I think it makes it clearer.

2023-03-06 18:42 UTC, taddes commented on tests/load/README.md
> +`^(?P<environment>stage|prod)(?:-(?P<task>\w+)-(?P<onfailure>warn|abort))?-(?P<commit>[a-z0-9]+)$`
What do you say about leaving this here in the load test README, and I remove the comments in config.yml and remove a few references in the release-process doc? I do sometimes wish some docs in our repos had more relevant info being pointed to or referenced, even if it's simply a summary and then a pointer to a more detailed reference.  There are cases where relevant info overlaps, so this way it's not really duplicated but relevant. I do reference the docs in the load testing in CONTRIBUTING and release-process so a dev knows where to go a lot without repeating that content. I'll tighten it up and let me know what you think.

2023-03-06 18:43 UTC, taddes commented
Thanks @Trinaa ! Just reference the Jira ticket for the discussion regarding testing. Dustin has a PR ready to merge and test, so we can coordinate running this change with his branch that supports the `stage-` prefix.  I'll make those small changes you requested and added responses to a few re: docs.

2023-03-06 23:38 UTC, taddes commented on .circleci/config.yml
> +
1. Sensible concern, but are there ever situations where we would possibly want to trigger load tests while not on main, say triggering them prior to a publishing to the Docker image?
2. I could totally condense the grep to limit the if blocks, however we'd get into the same issue as I am trying to echo useful info depending on what option is selected. I see the other steps echo useful output regarding what is happening, so if we want to not have that info based on the load test option, I can remove the echos entirely and reduce the blocks, but as it is shouldn't be causing needless overhead.

2023-03-07 10:41 UTC, hackebrot requested changes
Thank you for working on this, @taddes!

I've added my comments inline.

2023-03-07 10:41 UTC, hackebrot commented on docs/dev/release-process.md
> +## Load Testing Opt-In [load test: (abort|warn)]
- I think it's important to be clear that load testing locally does not require any keywords in commit messages
- The CircleCI configuration uses `git log -1` which means only the most recent commit's message is checked for the keywords, which will be the merge commit on the `main` branch
- The Jenkins deployment workflow first deploys to `stage`, then runs load tests if requested via the keywords in the commit message, and then sends a warning or abort the `prod` deployment on load test failure

2023-03-07 10:41 UTC, hackebrot commented on CONTRIBUTING.md
> +- If making documentation changes or minor revisions, you may wish to avoid deployment. Please see the [Preventing deployment via [do not deploy]][release-process] documentation.
All changes should be deployed even minor changes since `main` should reflect the application code running in the production environment.

```suggestion
- If you're solely updating documentation, you may wish to avoid deployment. Please see the [Preventing deployment via [do not deploy]][release-process] documentation.
```

2023-03-07 10:41 UTC, hackebrot commented on tests/load/README.md
> +a signal tag in your git commit. This tag is in the form of: `[load test: (abort|warn)]`. Take careful note
I suggest we agree on one term for the `[load test: (abort|warn)]` and always use that in documentation rather than `signal`, `tag`, `flag` etc. to avoid ambiguity.

Considering that `tag` and `flag` are common terms in deployment-related documentation (Docker image tag and feature flag), I suggest we use keyword or keywords.

2023-03-07 10:41 UTC, hackebrot commented on tests/load/README.md
> +The abort flag will prevent a stage deployment should the load test fail.
```suggestion
The abort flag will prevent a `prod` deployment should the load test fail.
```

2023-03-07 12:35 UTC, Trinaa commented
The mixup between stage and prod deployment instructions is my fault. I will fix the description in DISCO-2254. Sorry about this @taddes.

2023-03-07 13:31 UTC, Trinaa commented on .circleci/config.yml
> +
It's as @hackebrot [explains](https://github.com/mozilla-services/merino-py/pull/223#discussion_r1127584254), you need a stage deployment in order to execute load tests. We don't want stage deployments triggered unless we are pushing to 'main'

2023-03-07 14:35 UTC, taddes commented on tests/load/README.md
> +a signal tag in your git commit. This tag is in the form of: `[load test: (abort|warn)]`. Take careful note
Absolutely, this was something I was going to ask about, since the ticket description uses `tag` and I saw word `signalization`, which I liked in this context.  Since `tag` and `flag` are indeed common terms used for interchangeable purposes, picking keyword does make it something different.  However, `tag` does sound more semantically appropriate in this context, given it's not just a keyword that is being added, as in it's more than one single word. Thoughts?

2023-03-08 20:01 UTC, Trinaa commented on .circleci/config.yml
> +              fi
We will need to add the `stage-` prefix to all stage Docker tags. So that line 207 becomes `DOCKER_TAG="stage-${CIRCLE_SHA1}"`.

Going one step further, we could improve evaluation time by using elif and else statements.

```suggestion
    if git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: warn\]'; then
        echo "Load test requested. Slack warning will be output if test fails and deployment workflow for prod will proceed."
        DOCKER_TAG="stage-loadtest-warn-${CIRCLE_SHA1}"
    elif git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: abort\]'; then
        echo "Load test requested. Deployment workflow for prod will abort if load test fails."
        DOCKER_TAG="stage-loadtest-abort-${CIRCLE_SHA1}"
    else
        DOCKER_TAG="stage-${CIRCLE_SHA1}"
    fi
```

2023-03-09 14:59 UTC, Trinaa commented on .circleci/config.yml
> +                DOCKER_TAG="stage-${CIRCLE_SHA1}"
There is a `fi` missing here I think.

2023-03-09 15:30 UTC, taddes commented on .circleci/config.yml
> +                DOCKER_TAG="stage-${CIRCLE_SHA1}"
Ack, good catch.... how much I depend on syntax highlighting... Shame on shell commands being so verbose. Thank you @Trinaa 🤣

2023-03-09 16:12 UTC, Trinaa approved these changes

2023-03-09 16:39 UTC, hackebrot requested changes

2023-03-09 17:08 UTC, taddes commented on tests/load/README.md
> +The commit tag signals load test instructions to Jenkins by modifying the Docker image tag. The Jenkins deployment workflow first deploys to `stage` and then runs load tests if requested. The Docker
@hackebrot minor diff here: the term label applies to the `[load test: abort|warn]` label, but tag here refers to the commit tag, which is constructed by the process upon label ingestion and passed on to Jenkins. I used the same language as in the [ticket](https://mozilla-hub.atlassian.net/browse/DISCO-2254), being "The commit tag signals load test instructions to Jenkins by modifying the Docker image tag name. The convention looks as follows:.." I wanted to make this a clear distinction, as calling both labels . Perhaps calling it the "Docker tag" opposed to "commit tag" is better, if you prefer, but I don't think this is intended to be called a label in this case.

2023-03-09 18:48 UTC, hackebrot commented on tests/load/README.md
> +The commit tag signals load test instructions to Jenkins by modifying the Docker image tag. The Jenkins deployment workflow first deploys to `stage` and then runs load tests if requested. The Docker
We've decided to use the term `label` when referring to `[load test: warn]` and `[load test: abort]` after the ticket was created. I suggested this change because we don't create Git tags for commits in merino-py (this is important since we're working on Continuous Deployment).

The Docker image tag contains:
- the target environment (`prod` or `stage`)
- optionally the load test label (with `warn` or `abort`, based on the Git commit's message)
- Git commit SHA1

I will go ahead an approve your pull request now.

2023-03-09 18:50 UTC, hackebrot approved these changes

2023-03-09 18:53 UTC, Trinaa commented
@dlactin this PR is ready for merge. We will wait for your signal.

2023-03-09 22:04 UTC, taddes commented on tests/load/README.md
> +The commit tag signals load test instructions to Jenkins by modifying the Docker image tag. The Jenkins deployment workflow first deploys to `stage` and then runs load tests if requested. The Docker
Thanks for approving @hackebrot ! Looking forward to testing this new feature.

2023-03-10 02:07 UTC, taddes commented on tests/load/README.md
> +The commit tag signals load test instructions to Jenkins by modifying the Docker image tag. The Jenkins deployment workflow first deploys to `stage` and then runs load tests if requested. The Docker
Based on your comment above @hackebrot , did you want me to alter the language prior to our merge or does it mean that it is ok to stay as-is? Happy to change it if you prefer, just let me know as I wasn't sure from the last message. You know these flows best and likely have the clearest idea of language, so happy to defer to what you think is most accurate. Thanks!

2023-03-22 16:05 UTC, merged