[CONSVC-1855] Migrate existing contract tests and integrate into CI
mozilla-services/merino-py pull request #27
Opened 2022-08-25 20:03 UTC by Trinaa

## Description
* migrate framework code from [merino](https://github.com/mozilla-services/merino/tree/main/test-engineering/contract-tests) project 
* create `make contract-test` and `make contract-test-clean` shortcuts to execute and cleanup contract-tests
* add contract tests to CI

**NOTE**
* Contract tests are currently failing. client_variants and WikiFruit provider are currently unsupported.
* Next step: [CONSVC-1947](https://mozilla-hub.atlassian.net/browse/CONSVC-1947) - Align contract test tech stack with application

## Issue(s)
[CONSVC-1855](https://mozilla-hub.atlassian.net/browse/CONSVC-1855)

2022-08-26 12:01 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

I've added comments inline.

We can discuss options for resolving the failures you've mentioned on Slack.

2022-08-26 15:23 UTC, Trinaa commented on Makefile
> +	docker-compose -f test-engineering/contract-tests/docker-compose.yml -p merino-py-contract-tests up --abort-on-container-exit --build
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 15:25 UTC, Trinaa commented on README.md
> +$ make contract-test
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 15:25 UTC, Trinaa commented on README.md
> +$ make contract-test-clean
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 15:25 UTC, Trinaa commented on test-engineering/contract-tests/README.md
> +docker-compose -f test-engineering/contract-tests/docker-compose.yml up --abort-on-container-exit --build
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 15:26 UTC, Trinaa commented on test-engineering/contract-tests/client/README.md
> +                 `..\contract-tests\volumes\kinto`.
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 15:26 UTC, Trinaa commented on test-engineering/contract-tests/client/tests/exceptions.py
> +    pass
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 15:26 UTC, Trinaa commented on test-engineering/contract-tests/kinto-setup/README.md
> +--config-file=test-engineering/contract-tests/kinto-setup/mypy.ini
change applied: [3bd00e0](https://github.com/mozilla-services/merino-py/pull/27/commits/3bd00e0f474dbf7f7590af14c6c32c6e78603a68)

2022-08-26 19:42 UTC, ncloudioj approved these changes
LGTM, thanks for setting up CT and migrating them over to here!

The broken tests should be fixed by #28. We can merge that onto this branch so CI will remain green.

2022-08-29 08:23 UTC, hackebrot approved these changes
Great work, @Trinaa! 🚀

2022-08-29 19:21 UTC, merged