Add the Addons Provider to Merino
mozilla-services/merino-py pull request #273
Opened 2023-04-25 20:11 UTC by mtbottle

## References

JIRA: [DISCO-2357](https://mozilla-hub.atlassian.net/browse/DISCO-2357)

## Description
This adds the Addons Provider to Merino. It currently has the `is_top_pick` flag to render it in the "top picks" format. However, we'll likely want to revert that once the _real_ UX is complete.

Here is how a sample Addon Suggestion look in the browser: 

![Screenshot 2023-04-24 at 19 24 01](https://user-images.githubusercontent.com/829597/234391654-402b4e62-b0a9-4344-93de-2472bae8062b.png)

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[do not deploy]` and `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-04-25 22:22 UTC, linabutler reviewed
This is tremendous work, @mtbottle, thank you so much for doing this! 🎉 🚀

I left some initial review comments, but they're nits and suggestions in the grand scheme of things; the overall shape of this look great!

Holding off on officially approving in case you had more changes planned, or wanted to get this up as a work-in-progress patch—but if you're aiming to get this landed directly, I'm happy to r+wc next time!

2023-04-25 22:22 UTC, linabutler commented on merino/providers/addons/provider.py
> +    def _reverse_and_expand_index_keywords(
suggestion: How would you feel about making this a `@staticmethod`, or a free function?

2023-04-25 22:22 UTC, linabutler commented on merino/providers/addons/provider.py
> +        addon: Addon = await self.backend.get_addon(matched_addon)
suggestion: Catch and log `Addon(API)BackendException` here?

2023-04-25 22:22 UTC, linabutler commented on merino/providers/addons/backends/api.py
> +class AddonAPIBackend:
suggestion: Maybe `DynamicBackend` would make a nicer name than `APIBackend`? Or `AMOBackend`?

2023-04-25 22:22 UTC, linabutler commented on merino/providers/custom_details.py
> +class CustomDetails(BaseModel):
Oooh, nice use of your custom details proposal! 🚀

2023-04-25 22:22 UTC, linabutler commented on merino/providers/base.py
> +    description: str | None = None
suggestion: Would this be good to put as a non-optional field in the `(Temporary)AddonSuggestion` model, instead of an optional field in the `BaseSuggestion` model?

2023-04-25 22:22 UTC, linabutler commented on tests/contract/volumes/client/scenarios.yml
> +                custom_details: null
suggestion: Let's set the `response_model_exclude_none=True` option (or at least `response_model_exclude_unset`; the [FastAPI docs](https://fastapi.tiangolo.com/tutorial/response-model/#use-the-response_model_exclude_unset-parameter) say it supports both of those options) on the `/suggest` endpoint, [here](https://github.com/mozilla-services/merino-py/blob/a70962823db7b62ae56067f500e5af8dbb212ee6/merino/web/api_v1.py#L43-L48), so that we're not including null fields in all our responses.

2023-04-25 22:24 UTC, linabutler commented
> Here is how a sample Addon Suggestion look in the browser:
> 
> ![Screenshot 2023-04-24 at 19 24 01](https://user-images.githubusercontent.com/829597/234391654-402b4e62-b0a9-4344-93de-2472bae8062b.png)

Terrific! 🤩

2023-04-26 01:12 UTC, ncloudioj commented on merino/providers/addons/provider.py
> +        self.addon_keywords = self._reverse_and_expand_index_keywords(keywords)
Let's move this call to `initialize()`, which is made exactly for tasks like this.

2023-04-26 01:20 UTC, ncloudioj commented on merino/providers/addons/provider.py
> +        addon: Addon = await self.backend.get_addon(matched_addon)
For the API backend, what do you think about pre-fetching all the addons from the AMO endpoint during initialization? We only have a small number of addons and I guess the addon data won't change that often. We can cache the results in memory so that Merino doesn't need to make network calls for every single keyword hit. If addon data get volatile in the future, we can spin a cron job to refresh them in the background just like what the `adm` provider does.

2023-04-26 01:22 UTC, ncloudioj commented on merino/providers/addons/provider.py
> +                is_sponsored=True,
We might want to confirm with Product regarding whether this belongs to sponsored or not.

2023-04-26 01:27 UTC, ncloudioj commented on merino/providers/addons/provider.py
> +            for word in list(kws):
```suggestion
            for word in kws:
```

2023-04-26 01:29 UTC, ncloudioj commented on merino/providers/addons/provider.py
> +        reverse_index = {}
nit: I think we usually use "inverted index" for structures like this.

2023-04-26 01:41 UTC, ncloudioj commented on merino/providers/addons/addons_data.py
> +        "Ad tracking",
Looks like "Ad tracking" is used by both this and `ublock-origin`, since the keyword index follows the "LIFO" semantics, shall we drop one to avoid confusion?

2023-04-26 01:42 UTC, ncloudioj commented on merino/providers/addons/addons_data.py
> +        "ad blocker",
```suggestion
        "Ad block",
        "Ad blocker",
```

2023-04-26 01:43 UTC, ncloudioj commented on merino/providers/addons/backends/api.py
> +class AddonAPIBackend:
Good point. Shall we also call this provider "amo" instead of `addon`?

2023-04-26 01:47 UTC, ncloudioj commented on merino/providers/addons/backends/api.py
> +        res = requests.get(f"{self.api_url}/{addon_key}")
Nice catch, Lina. Yup, we prefer async clients over the blocking counterparts for the Merino web app since it runs as a single-threaded app, whereas it's fine to use the latter for Merino jobs.

2023-04-26 01:55 UTC, ncloudioj commented on tests/unit/providers/addons/backends/test_static.py
> +from merino.providers.addons.addons_data import STATIC_DATA
Can you add a test to enforce those addon keys are consistent across `STATIC_DATA`, `KEYWORDS`, and `STATIC_RATING_AND_ICONS`? Because we're calling `STATIC_DATA[addon_key]` and `STATIC_RATING_AND_ICONS[addon_key]` throughout the code base, any typos or missing keys would hit the `KeyError`s.

2023-04-26 02:04 UTC, ncloudioj commented on merino/configs/default.toml
> +[default.providers.addons]
It's always a good idea to add config validations to `merino/config.py`. Also, let's add some docs to `docs/operations/configs.md` as it's still referenced by some folks.

2023-04-26 02:07 UTC, ncloudioj requested changes
Great stuff 🙌! Thanks for adding this new provider to Merino!

There are some review comments for further tweaking, otherwise, it looks great.

2023-04-26 02:10 UTC, ncloudioj commented on merino/providers/addons/provider.py
> +        for (addon_name, kws) in keywords.items():
```suggestion
        for addon_name, kws in keywords.items():
```

2023-04-26 18:25 UTC, mtbottle commented on merino/providers/addons/addons_data.py
> +"""Static Mapping for the Addon data, along with the associated keywords
Yes! I intentionally chose the Python module so we didn't have to read it! For small datasets that isn't shared with any other processing (i.e. aggregation job etc.), this is probably the most easily maintainable. Having it in code allows us to: 

1. Have format checking during runtime (ie. missing commas, brackets, or wrong indentation will not be an issue)
2. Be more efficient by avoiding extra IO processing steps
3. Skip the complexity of ensuring that we have the right filepaths to be used

2023-04-26 18:33 UTC, quiiver commented on merino/providers/addons/addons_data.py
> +"""Static Mapping for the Addon data, along with the associated keywords
i'm into it 😎

2023-04-27 15:14 UTC, mtbottle commented on merino/providers/addons/provider.py
> +        addon: Addon = await self.backend.get_addon(matched_addon)
> what do you think about pre-fetching all the addons from the AMO endpoint during initialization?

Ya! I think this might actually be a better idea than caching (especially since some calls take longer than 200ms). I'm going to try to initialize and store the Addons data in an object for now.

2023-04-27 20:25 UTC, mtbottle commented on merino/providers/addons/backends/api.py
> +        """Get Addons given the list of keys"""
Whoops! Thanks for the catch!

> But also, addon_key almost feels like it wants to be an enum or a [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum), with STATIC_DATA and KEYWORDS both using it as the key. WDYT?

This is a good idea! This will also ensure that the keys passed between provider and backend are valid.

2023-04-27 20:25 UTC, mtbottle commented on merino/providers/addons/provider.py
> +                is_sponsored=True,
I've confirmed with product that we don't want this to be sponsored. Will update this.

2023-04-28 01:13 UTC, mtbottle commented on tests/unit/providers/addons/backends/test_static.py
> +from merino.providers.addons.addons_data import STATIC_DATA
I've switched to using an enum for the keys, so we shouldn't have KeyErrors anymore.

2023-04-28 01:36 UTC, mtbottle commented on merino/providers/addons/backends/api.py
> +class AddonAPIBackend:
> Shall we also call this provider "amo" instead of addon?

I'm sticking with `addons` as I feel like it's clearer to me :p 

But I've renamed this backend `DynamicAddonsBackend`. It's actually _less_ dynamic right now (I load it once, and never update). I think we can use the next ticket to update the object in a cron so that it's _fresher_.

2023-05-02 01:29 UTC, linabutler approved these changes
r+wc, thanks @mtbottle! This is exciting! 🎊

2023-05-02 01:29 UTC, linabutler commented on merino/providers/base.py
> +    description: str | None = None
Gotcha, thanks!

2023-05-02 16:09 UTC, mtbottle commented on merino/providers/addons/backends/dynamic.py
> +                )
> If any error happens, this will terminate the entire initialization with a partial self.dynamic_data, do we want to fall back to the static data in that case?

No, I don't think we want to fall back on static, but have the partial data. I'm intending the cron job follow-up, so we can just leave this for now.

2023-05-02 16:34 UTC, mtbottle commented on merino/configs/default.toml
> +[default.providers.addons]
> we usually use the name of the suggestion source as the provider ID instead of the type of the suggestion

OK! I'll change it to `amo` instead of `addons`.

2023-05-02 19:32 UTC, ncloudioj commented on merino/providers/addons/backends/dynamic.py
> +                )
Sounds good, please disregard all my previous comments on fallback-on-static then.

2023-05-03 01:12 UTC, mtbottle commented on merino/providers/addons/backends/dynamic.py
> +        for addon_key in SupportedAddons:
> This might be a good place to use a TaskGroup, to issue all the requests to the API in parallel?

As mentioned in a different comment, I'm not going to parallelize this for now because there's not a lot of calls made and it's going to be done async.

2023-05-03 01:17 UTC, mtbottle commented on tests/contract/volumes/client/scenarios.yml
> +                custom_details: null
It looks like `response_model_exclude_unset` needs to work with the `response_model` (i.e. `BaseSuggestion`) but what we're currently returning is a `JSONResponse` casting of the Suggestion. However, once I remove extra `JSONResponse` casting and return the Suggestion directly, it looks like the extra fields in the extended `BaseSuggestion` models (i.e. like `SponsoredSuggestions` specific fields) are not recognized. So the fix for this looks to be non-trivial, so maybe it's worth exploring later (I can create a ticket for this)? What do you think @linabutler ?  There's also a part of me that feels like returning `null` is _ok_ because it's part of the API contract and returning them (even though they're null) gives more explicitness to the contract. However, we'll probably want to _not_ show all of the `custom_details` fields... so we'll likely want to fix this at some point.

Currently I've removed the configuration, as it's not working as expected.

2023-05-03 02:30 UTC, linabutler commented on tests/contract/volumes/client/scenarios.yml
> +                custom_details: null
> what we're currently returning is a `JSONResponse` casting of the Suggestion.

Oh, I'm so sorry I missed that! It looks like you can do `JSONResponse(content=jsonable_encoder(response, exclude_unset=True))`, but I'd be okay with doing this in a follow-up in case that's also messy!

> Currently I've removed the configuration, as it's not working as expected. 

Sounds good, thank you!

2023-05-03 18:19 UTC, merged