Cache Accuweather Responses with Expiry TTL
mozilla-services/merino-py pull request #320
Opened 2023-06-09 04:20 UTC by mtbottle

## References

JIRA: [DISCO-2418](https://mozilla-hub.atlassian.net/browse/DISCO-2418)

## Description
This adds some caching for the exact Accuweather request, rather than aggregating the response into a `WeatherReport` to put into the cache. This provides a few possible flexibilities:

1. We can be agnostic about the response type coming from Accuweather. So, this can open up the possibilities to also cache 4xx errors (currently not doing that in this PR), as retrying them in short successions will be a waste of API credit. (Redis mem graph [here](https://earthangel-b40313e5.influxcloud.net/explore?left=%7B%22datasource%22:%22Stackdriver%20-%20CloudOps%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22stackdriver%22,%22uid%22:%22o0Z_lCHMz%22%7D,%22refId%22:%22A%22,%22intervalMs%22:0,%22type%22:%22timeSeriesQuery%22,%22queryType%22:%22metrics%22,%22metricQuery%22:%7B%22aliasBy%22:%22Used%20Memory%22,%22alignmentPeriod%22:%22%2B1800s%22,%22crossSeriesReducer%22:%22REDUCE_MAX%22,%22editorMode%22:%22visual%22,%22filters%22:%5B%5D,%22groupBys%22:%5B%22resource.label.pod_name%22%5D,%22metricKind%22:%22GAUGE%22,%22metricType%22:%22redis.googleapis.com%2Fstats%2Fmemory%2Fusage%22,%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22preprocessor%22:%22none%22,%22projectName%22:%22moz-fx-merino-metrics-d487%22,%22query%22:%22%22,%22valueType%22:%22INT64%22,%22view%22:%22FULL%22%7D%7D,%7B%22datasource%22:%7B%22type%22:%22stackdriver%22,%22uid%22:%22o0Z_lCHMz%22%7D,%22refId%22:%22B%22,%22intervalMs%22:0,%22type%22:%22timeSeriesQuery%22,%22queryType%22:%22metrics%22,%22metricQuery%22:%7B%22aliasBy%22:%22Maximum%20Memory%22,%22alignmentPeriod%22:%22cloud-monitoring-auto%22,%22crossSeriesReducer%22:%22REDUCE_MEAN%22,%22editorMode%22:%22visual%22,%22filters%22:%5B%5D,%22groupBys%22:%5B%5D,%22metricKind%22:%22GAUGE%22,%22metricType%22:%22redis.googleapis.com%2Fstats%2Fmemory%2Fmaxmemory%22,%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22preprocessor%22:%22none%22,%22projectName%22:%22moz-fx-merino-metrics-d487%22,%22query%22:%22%22,%22valueType%22:%22INT64%22,%22view%22:%22FULL%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D&orgId=1))
2. We can treat each API differently based on our expected expiry for that data.

The potential area of concerns are:

1. We are storing a lot more data than we're using. However, checking the Redis disk usage, it _doesn't_ seem to be a concern. However, we should monitor this in case we use up too much disk space.
2. Data migration risks. 

To derisk some of these things, I've opted to open up this change to _add_ caching at the request level, while preserving the existing caching. The amount of space we have on our Redis instance makes me feel like this is an _ok_ strategy, as we're currently using about 12% of our maximum capacity (if my graph is correct). Once this is out and it looks like we're populating the cache properly, then I would remove the old caching code.

I am also considering compressing the responses when storing it in Redis. However, I want to have it run without compression to see how much space it actually takes up first. Adding compression might also affect the latency, so it would be useful to have some sort of comparison data.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-06-09 14:36 UTC, mtbottle commented
I've tested this locally with the local Redis docker container and it stores and retrieves values from Redis.

2023-06-12 19:47 UTC, linabutler requested changes
This looks lovely; I really like your approach of pushing the caching down into the backend, and totally agree that it gives us more flexibility, compared to caching the entire report at the provider level!

I'll do another pass once the jet lag wears off, but here's a first round of feedback 😄

2023-06-12 19:47 UTC, linabutler commented on merino/providers/manager.py
> +                    cache=RedisAdapter(
suggestion: Can we create one `RedisAdapter` instance, above line 53, then pass it here and on line 76 below?

2023-06-12 19:47 UTC, linabutler commented on merino/providers/weather/backends/accuweather.py
> +            del params["apikey"]
```suggestion
        params.pop(settings.accuweather.url_param_api_key, None)
```

nitpick: If it makes sense, let's use `settings.accuweather.url_param_api_key` here, instead of hard-coding `"apikey"`?

2023-06-12 19:47 UTC, linabutler commented on merino/providers/weather/backends/accuweather.py
> +            extra_identifiers = hashlib.blake2s(str(params).encode("utf-8")).hexdigest()
```suggestion
            hasher = hashlib.blake2s()
            for key, value in sorted(params.items()):
                hasher.update(key.encode("utf-8") + value.encode("utf-8"))
            extra_identifiers = hasher.hexdigest()
```

suggestion: I'm not sure if the dictionary string representation—or dictionary enumeration order—is guaranteed to be stable, so we might end up with spurious cache misses for the same set of `params`, depending on how exactly the dictionary is populated.

It's a bit more code, but for cases like this, I like to explicitly canonicalize the representation.

2023-06-12 23:53 UTC, linabutler commented on merino/providers/weather/backends/accuweather.py
> +                )
suggestion (non-blocking): The HTTP date format is a [variation of RFC 2822](https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.1.1), so I _think_ using [`email.utils.parsedate_to_datetime`](https://python.readthedocs.io/en/latest/library/email.util.html#email.utils.parsedate_to_datetime) here instead of `strptime` will also work!

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +        cache=redis_mock_cache_miss,
```suggestion
        cache=RedisAdapter(redis_mock_cache_miss),
```

nitpick: The test will still work, but I think this will match how the "real" code does it—IIUC, `cache` is a `CacheAdapter` (`from merino.cache.redis import RedisAdapter`), not the Redis client directly.

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +        AccuweatherBackend(cache=mocker.AsyncMock(spec=Redis), **accuweather_parameters)
```suggestion
        AccuweatherBackend(cache=RedisAdapter(mocker.AsyncMock(spec=Redis)), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +        cache=redis_mock_cache_miss,
```suggestion
        cache=RedisAdapter(redis_mock_cache_miss),
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +        AccuweatherBackend(cache=mocker.AsyncMock(spec=Redis), **accuweather_parameters)
```suggestion
        AccuweatherBackend(cache=RedisAdapter(mocker.AsyncMock(spec=Redis)), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    accuweather = AccuweatherBackend(cache=redis_mock, **accuweather_parameters)
```suggestion
    accuweather = AccuweatherBackend(cache=RedisAdapter(redis_mock), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    accuweather = AccuweatherBackend(cache=redis_mock, **accuweather_parameters)
```suggestion
    accuweather = AccuweatherBackend(cache=RedisAdapter(redis_mock), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    accuweather = AccuweatherBackend(cache=redis_mock, **accuweather_parameters)
```suggestion
    accuweather = AccuweatherBackend(cache=RedisAdapter(redis_mock), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    accuweather = AccuweatherBackend(cache=redis_mock, **accuweather_parameters)
```suggestion
    accuweather = AccuweatherBackend(cache=RedisAdapter(redis_mock), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    accuweather = AccuweatherBackend(cache=redis_mock, **accuweather_parameters)
```suggestion
    accuweather = AccuweatherBackend(cache=RedisAdapter(redis_mock), **accuweather_parameters)
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +def fixture_accuweather_parameter(statsd_mock: Any) -> dict[str, Any]:
Did you mean to drop the plural (`accuweather_parameters` => `accuweather_parameter`) here? It's okay either way; I was just curious, since the fixture name still has the plural! 👀

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    assert not mock_client.get.called
```suggestion
    mock_client.get.assert_not_called()
```

suggestion: `assert_not_called` has a nicer error message with details (mock name, number of times it was called) if the assertion fails.

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    assert not mock_client.get.called
```suggestion
    mock_client.get.assert_not_called()
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    assert not mock_client.get.called
```suggestion
    mock_client.get.assert_not_called()
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +    assert not mock_client.get.called
```suggestion
    mock_client.get.assert_not_called()
```

2023-06-12 23:53 UTC, linabutler commented on tests/unit/providers/weather/backends/test_accuweather.py
> +@pytest.mark.parametrize(
Fantastic new tests! 🏆 I'm always inspired to be more thorough in writing tests when I review your PRs!

2023-06-13 20:17 UTC, mtbottle commented on merino/providers/weather/backends/accuweather.py
> +            extra_identifiers = hashlib.blake2s(str(params).encode("utf-8")).hexdigest()
Oh good point! I think Python 3.7+ [has stable `dict` enumeration order](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) (which makes me presume that the string will be stable too). However, `dicts` should _not_ be assumed to be ordered, as that's not the intent of this type of data structure. So let's make this explicit!

2023-06-14 15:17 UTC, mtbottle commented on tests/unit/providers/weather/backends/test_accuweather.py
> +def fixture_accuweather_parameter(statsd_mock: Any) -> dict[str, Any]:
Nope, this is a typo! Thanks for the catch!

2023-06-14 19:39 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +            del params["apikey"]
Just a note that accessing a deeply nested property of the Dynaconf's settings object can be slow, in particular on the hot code paths as it will do multiple lookups. We've been bitten by that before. As a workaround, we often use a module constant or a class member to store its value for future reference.

```
URL_PARAM_API_KEY: str = settings.accuweather.url_param_api_key
```

2023-06-14 20:32 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +        self, client: AsyncClient, url: str, params: dict[str, str] = {}
Calling it `url` seems a bit misleading here, it's actually a path as we have set the base URL upon the creation of the client. I was confused when I saw `request_type: str = url.strip("/").split("/")[0]` down below cuz given a full URL that'll return `https:`.

2023-06-14 20:32 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +        request_type: str = url.strip("/").split("/")[0]
Since we only care about the 1st entry, no need to split the rest.
```suggestion
        request_type: str = url.strip("/").split("/", 1)[0]
```

2023-06-14 20:32 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +            extra_identifiers = hashlib.blake2s(str(params).encode("utf-8")).hexdigest()
On top of Lina's suggestion, we can do this to save a dict copy and a `dict.pop()` for all current condition and forecast requests.
```suggestion
           if len(params) > 1:  // "apikey" is included for all requests
                hasher = hashlib.blake2s()
                for key, value in sorted(params.items()):
                    if key != self.url_param_api_key:
                        hasher.update(key.encode("utf-8") + value.encode("utf-8"))
                extra_identifiers = hasher.hexdigest()
```

2023-06-14 20:36 UTC, ncloudioj commented
This looks great, r=nanj. Feel free to merge once Lina's ✅ is granted.

2023-06-15 00:19 UTC, mtbottle commented on merino/providers/weather/backends/accuweather.py
> +            extra_identifiers = hashlib.blake2s(str(params).encode("utf-8")).hexdigest()
> we can do this to save a dict copy and a dict.pop() for all current condition and forecast requests.

Oh! This is actually a much better idea. I'll do this instead, thanks!

2023-06-15 00:32 UTC, mtbottle commented on merino/providers/weather/backends/accuweather.py
> +        self, client: AsyncClient, url: str, params: dict[str, str] = {}
Ah ya, `url_path` is more accurate. I'll change it to that.

2023-06-15 08:16 UTC, linabutler approved these changes
Looks great, thanks! r+wc about the exceptions.

2023-06-20 13:30 UTC, merged