refactor: improve testability of business logic
mozilla-services/merino-py pull request #33
Opened 2022-08-30 13:39 UTC by hackebrot

This is work in progress. 🚧

The goal of this pull request is to demonstrate how composition and protocols can help us increase testability. I've added a unit test for the new cron job to show how we can test async functions.

2022-08-30 17:53 UTC, quiiver commented on merino/providers/cron.py
> +# This Source Code Form is subject to the terms of the Mozilla Public
Should we move this to the top level module since it's no longer specific to `providers` ?

2022-08-30 18:03 UTC, hackebrot commented on merino/providers/cron.py
> +# This Source Code Form is subject to the terms of the Mozilla Public
Yes, good idea! 👍🏻

2022-08-30 18:04 UTC, quiiver commented on pyproject.toml
> +pytest-asyncio = "^0.19.0"
`@pytest.mark.asyncio` works for me without having to include this dependency

2022-08-30 18:06 UTC, quiiver approved these changes
Nice, I like the testability and that this keeps the provider code specific to the purpose of providing suggestions.

2022-08-30 21:21 UTC, Trinaa approved these changes
Very Nice 🚀. I suggestion about time as discussed earlier.

2022-08-30 21:21 UTC, Trinaa commented on tests/providers/test_cron.py
> +    await asyncio.sleep(3)
Is it possible to have a shorter task run, in order to keep the suite running quickly?

2022-08-30 21:21 UTC, ncloudioj commented on merino/providers/adm.py
> +        asyncio.create_task(cron_job())
This task needs to be stored here otherwise it will get garbage collected because asyncio's runtime only holds a weak reference to it.

2022-08-30 21:30 UTC, ncloudioj commented on merino/providers/cron.py
> +class Task(Protocol):
Nit: this would collide with `asyncio.Task`, shall we consider renaming this to something like `CronTask`?

2022-08-30 21:34 UTC, ncloudioj requested changes
I like this refactor, thanks! @hackebrot 

Had a few review comments, otherwise, it looks great.

2022-08-31 07:05 UTC, hackebrot commented on pyproject.toml
> +pytest-asyncio = "^0.19.0"
Does pytest run the test for you without the marker? I can run the suite without failures without the plugin, but pytest skips the marked test and logs a message about the missing plugin.

2022-08-31 07:46 UTC, hackebrot commented on merino/providers/cron.py
> +class Task(Protocol):
That's a good question! @Trinaa and I recently had a similar conversation about `requests` in the scope of contract tests. My recommendation would be to not prefix our objects to accommodate for dependencies but refer to objects with conflicting names using their respective module name.

```python
import asyncio
from merino import cron

asyncio_task: asyncio.Task
cron_task: cron.Task
```

In this particular case `cron.Task` is a `Protocol` and is unlikely to be referenced outside of unit tests or the `cron.py` module itself. Objects that implement that protocol will be considered a `cron.Task` implicitly. I'll update `adm.py` to use `cron.Job`.

2022-08-31 08:25 UTC, hackebrot commented on tests/providers/test_cron.py
> +    await asyncio.sleep(3)
Yes! I changed `interval` to be a `float` and managed to get the tests working with `0.1` intervals and a shorter sleep.

2022-08-31 14:26 UTC, ncloudioj commented on merino/providers/cron.py
> +class Task(Protocol):
Sounds good to me. Tanks for sharing the context!

2022-08-31 14:28 UTC, ncloudioj approved these changes
:shipit:

2022-08-31 15:00 UTC, Trinaa commented on tests/providers/test_cron.py
> +    await asyncio.sleep(3)
Ran them locally. It's much faster now ty!

2022-08-31 15:11 UTC, merged

2022-08-31 15:11 UTC, hackebrot commented
Thanks for the reviews, team! 🥳