[DISCO-2533] fastapi pydantic uvicorn update
mozilla-services/merino-py pull request #375
Opened 2023-07-19 16:17 UTC by taddes

## References

JIRA: [DISCO-2533](https://mozilla-hub.atlassian.net/browse/DISCO-2533)
GitHub: [#TODO](https://github.com/mozilla-services/merino-py/issues/TODO)

## Description
Upgrade core dependencies and ensure Merino runs without error due to the upgrade. 

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-08-04 15:02 UTC, ncloudioj commented
Nice, good to see everything is green now.

I just did some test runs, looks like there are a few warnings (will comment in the patch).

Also the benchmark shows this branch regressed the performance by ~25% (against `main`) for both throughput and latency, which is interesting. Will take a closer look into it.

2023-08-04 17:43 UTC, ncloudioj reviewed
Looks good, a few warning fixes and a performance fix are needed.

2023-08-04 17:43 UTC, ncloudioj commented on merino/utils/log_data_creators.py
> +        dt: datetime = TypeAdapter(datetime).validate_python(v)
The profile result suggests this validation really requires lots of CPU cycles, dropping it yields a huge delta in performance gain. @Trinaa can you remind me why did we want to do this validation instead of passing in the ISO-formatted string directly [here](https://github.com/mozilla-services/merino-py/blob/main/merino/middleware/logging.py#L51C1-L56)? The validation seems unnecessary as the `datatime` object is created by Merino rather than by external producers.

2023-08-04 17:43 UTC, ncloudioj commented on pyproject.toml
> +fastapi = "^0.100.0"
Can you do a rebase against the main branch? Dependabot updated various things which might get downgraded by this patch.

2023-08-04 17:48 UTC, ncloudioj commented on merino/cache/none.py
> +        ttl: timedelta | None = None,
Is it really necessary? Neither `Union` nor `Optional` is deprecated in typing.py, I think we should allow folks to use either one instead of forcing them to use the `A | B`.

@taddes can you confirm?

2023-08-07 15:07 UTC, taddes commented on merino/cache/none.py
> +        ttl: timedelta | None = None,
Hey @ncloudioj  👋 The`|` operator for typing was added part of [PEP-604](https://peps.python.org/pep-0604/) and references `The new union syntax should be accepted for function, variable and parameter annotations.` This is intended for > Python 3.10, so while it is acceptable, the new modern standard is pointing to using the operator opposed to `Union` or `Optional`. I suppose we can let folks use either, but since it's part of an official PEP, it is gently recommended to abandon the old keywords.

2023-08-07 15:09 UTC, taddes commented on merino/utils/log_data_creators.py
> +        dt: datetime = TypeAdapter(datetime).validate_python(v)
Good call, it's likely some of the other validations could yield improvement. However, it's a little confusing as Pydantic marketed their V2 methods to be _faster_... Strange that `parse_obj_as` should be somehow faster than using the `TypeAdapter`. I will do a little profiling as well, but can chat with @Trinaa about this too!

2023-08-07 22:46 UTC, taddes commented on merino/providers/weather/backends/protocol.py
> +    def __init__(self, c: float | None = None, f: float | None = None):
Makes sense! I did make a slightly different version that lets the `c` and `f` be a bit more permissive allowing `int | float | None`, which means we don't need `cc` and `ff`. Thoughts?

2023-08-09 14:06 UTC, ncloudioj commented
@taddes sorry, #392 introduced a couple of more things to this migration. Especially, I used `parse_obj_as()` in v1, looks like we can do `model_validate_json()` instead in v2 ([link](https://docs.pydantic.dev/latest/usage/models/#helper-functions)).

2023-08-09 14:40 UTC, taddes commented
Hey @ncloudioj , no worries, I can do the rebase and make those changes. If I have any questions, I'll ping you, but seems pretty straightforward.

2023-08-10 23:40 UTC, linabutler reviewed
Thank you so much for powering through this, @taddes! You're almost there!

2023-08-10 23:40 UTC, linabutler commented on merino/utils/log_data_creators.py
> +        dt: datetime = TypeAdapter(datetime).validate_python(v)
It's interesting for sure! I tend to think about advertised performance gains like that as a ballpark guideline—because it's very tough to reduce performance down to a single number.

It could still be that the more common paths in Pydantic are faster overall, but this specific one isn't—maybe it was a shorter, pure-Python code path before, but now involves trampolining into Rust through more methods and types.

Investigating if this validation is needed at all is a great next step—especially since we're [already constructing the `datetime` object in our own code](https://github.com/mozilla-services/merino-py/blob/f3d8efed346e17008f95cc589b72bda413c73d39/merino/middleware/logging.py#L43), as @ncloudioj says. The fastest code is code that doesn't have to run at all! 😊

2023-08-10 23:40 UTC, linabutler commented on merino/web/api_v1.py
> +    # https://docs.pydantic.dev/latest/usage/serialization/#serializing-subclasses
```suggestion
```

suggestion (non-blocking): Let's drop this comment, since you already explain it very well—and link to the same docs—in `SuggestResponse`.

2023-08-10 23:40 UTC, linabutler commented on merino/web/models_v1.py
> +    # SerializeAsAny required to ensure subclassed attributes serialized and emitted as expected.
```suggestion
    # `SerializeAsAny` ensures that all fields of `BaseSuggestion` and its subclasses are included when converting this model to a dictionary. 
```

suggestion (non-blocking): This is an excellent comment—it calls attention to a subtle behavior! I wonder if we can be just a bit more precise in the wording, to something like this? (Please feel free to tweak as you like!)

Specifically, let's call out _which_ subclasses we're referring to, and let's not rely on Pydantic's terminology in our explanation. As their docs note, "serialization" generally refers to converting data structures to strings or bytes, but "serialization" in the Pydantic world means something slightly different, which might be confusing or ambiguous to someone just skimming this code.

2023-08-11 21:33 UTC, taddes commented on merino/web/api_v1.py
> +    # https://docs.pydantic.dev/latest/usage/serialization/#serializing-subclasses
Good call @linabutler ! Thanks!

2023-08-11 21:40 UTC, taddes commented on merino/web/models_v1.py
> +    # SerializeAsAny required to ensure subclassed attributes serialized and emitted as expected.
That's a good call @linabutler , I especially agree with the section about calling out the "serialization" terminology in particular. Thanks for adding clarity to the comment, it's easier to follow.  I added one small blurb in parenthesis to go off what you said about what subclasses, what do you think?

```suggestion
    # `SerializeAsAny` ensures that all fields of `BaseSuggestion` and its subclasses
    # (ex. provider-specific Suggestion classes) are included when converting this model
    # to a dictionary.  See Pydantic docs for context:
```

2023-08-14 23:10 UTC, linabutler requested changes
This is looking wonderful, @taddes; great job! I wouldn't mind seeing it one more time—you're gonna be a pro at `git rebase` after you're done with this PR—but all I have are nits 😊

Let's see how the load test goes, and then we can get this landed!

2023-08-14 23:10 UTC, linabutler commented on merino/providers/weather/backends/protocol.py
> +    c: int | None = None
nitpick: For extra credit (meaning, please feel free to push back 😊), I'd love to see the `Temperature` changes split out into their own commit, before this one.

Having this commit separate from the Pydantic migration one already makes your PR _so_ much easier to skim, to the point where I wouldn't mind leaving the `Temperature` changes here—but it does go a bit beyond the `Option` -> `| None` conversion, since `c` and `f` change types from floats to integers (even though the behavior stays the same).

2023-08-14 23:24 UTC, quiiver commented on merino/featureflags.py
> +    enabled: confloat(ge=0.0, le=1.0)  # type: ignore [valid-type]
I would recommend using the 3.9+ `Annotated` type here. It is what `confloat` uses now and is recommended for describing type constraints. You should also be able to drop the mypy type ignore comment.

```suggestion
    enabled: Annotated[int, Field(gt=0.0, lte=1.0)]
```

https://docs.pydantic.dev/latest/usage/types/custom/

2023-08-15 15:51 UTC, ncloudioj commented on merino/providers/weather/backends/protocol.py
> +    def __init__(self, c: float | None = None, f: float | None = None):
Thanks for your comments, Lina!

Just wanted to add a bit of color here: This model is only used in the API response, and we have decided to show integer temperatures (rounded) in Firefox. That's why I recommended using `int | None` instead of `int | float | None` as the latter doesn't convey what exactly the type is and API consumers might presume that they will need to do rounding again to convert them into integers. Looks like Firefox assumes rounding is already done in Merino and uses temperature values as is (see source [here](https://searchfox.org/mozilla-central/source/browser/components/urlbar/UrlbarProviderWeather.sys.mjs#263-267)) from the API response.

As you mentioned, JSON doesn't distinguish the two. So alternatively, we can stick to `float | None` and convert all `c` and `f` into floats after rounding. Python will serialize them e.g. `23.0` in JSON, I guess JSON deserialization will drop the decimal bits automatically and we still get `23` eventually.

What do you think? @linabutler @taddes

2023-08-15 17:03 UTC, taddes commented on merino/featureflags.py
> +    enabled: confloat(ge=0.0, le=1.0)  # type: ignore [valid-type]
Thanks for the suggestion @quiiver !

2023-08-15 17:05 UTC, taddes commented on merino/jobs/csv_rs_uploader/__init__.py
> +from pydantic import BaseModel, HttpUrl, field_validator
Hmm. Very odd the linter didn't catch this... 🕵️

2023-08-15 17:10 UTC, taddes commented on tests/integration/api/v1/suggest/test_suggest_top_picks.py
> -    assert actual_suggestions == expected_suggestion
Yup, you got it @linabutler ! It's to align with `test_top_picks_short_domains`, didn't seem to make sense to have 2 similar functions doing a different thing to get a relatively similar result. I wanted to do some double duty on these tests by instantiating a `Suggestion` from the result data, which I feel robustly ensures we're getting what we expect.  Good call on checking, though, I know what you mean by unexpected test changes.

2023-08-15 17:11 UTC, linabutler commented on merino/providers/weather/backends/protocol.py
> +    def __init__(self, c: float | None = None, f: float | None = None):
Oooh, I like your point about using `int | None` to communicate that the temperature is already rounded! Let's leave it the way it's written now (`int | None`, and keep the `cc` and `ff` logic).

I didn't think about how including decimals in the response, or using `int | float | None`, might actually be more confusing about the expected precision. In JS, `23` and `23.0` are the same, but if you look at the raw JSON response and see `23.0` or `57.0`, you might wonder if you'll ever see a fractional temperature.

2023-08-15 17:14 UTC, taddes commented on merino/providers/weather/backends/protocol.py
> +    def __init__(self, c: float | None = None, f: float | None = None):
Yeah, good points above. I like the delineation about the types based on the creation of the `Temperature` class and then what it passes back, makes for it to be very clear. Thank you both for the insights on this @ncloudioj & @linabutler .

2023-08-15 17:47 UTC, mtbottle commented on merino/utils/log_data_creators.py
> +        dt: datetime = TypeAdapter(datetime).validate_python(v)
> IIUC, it looks like the (only?) reason LogDataModel.time is a string and not a datetime is to work around Pydantic 1.x's lack of custom per-field serializers. Does that sound right to you, @hackebrot and @mtbottle?

Yes! I believe that was the reason. The example looks good too!

2023-08-15 17:53 UTC, taddes commented on merino/utils/log_data_creators.py
> +        dt: datetime = TypeAdapter(datetime).validate_python(v)
Excellent! Glad Pydantic supports this feature now and we won't need workarounds in the future!

2023-08-15 19:43 UTC, quiiver commented on merino/featureflags.py
> +    enabled: confloat(ge=0.0, le=1.0)  # type: ignore [valid-type]
oh yes that's right

2023-08-18 18:48 UTC, taddes commented
Thanks for the excellent coaching in aligning the commits with the work done @linabutler , you're a master at this, appreciate it!

2023-08-18 18:51 UTC, linabutler approved these changes
Perfect! Thanks again, @taddes! :shipit:

2023-08-18 19:48 UTC, merged

2023-08-18 19:48 UTC, taddes commented
Closes #390