[DISCO-2534] Update to mypy 1.4.1 & Handle regressions and deprecatated types
mozilla-services/merino-py pull request #404
Opened 2023-08-19 21:27 UTC by taddes

## References

JIRA: [DISCO-2534](https://mozilla-hub.atlassian.net/browse/DISCO-2534)

## Description
Update outdated dependencies like mypy, black, flake8, etc

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-09-01 21:02 UTC, linabutler requested changes
Great work overall! Let's see if we can get rid of those straggling `#type: ignore`s, and then I think we should be all set to land!

2023-09-01 21:59 UTC, taddes commented on tests/load/locustfiles/locustfile.py
> +            top_picks_file_path=MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH,  # type: ignore
Hey @linabutler ! Thanks for looking everything over! Happy to change this, but I had a few thoughts I wanted to discuss on the approach!

This was a pickle because at the start of the locustfile, we [import all configurations](https://github.com/mozilla-services/merino-py/blob/6922fbc0f5ab0b335db701002002de20fb9eab79/tests/load/locustfiles/locustfile.py#L65-L93) using `os.getenv("KEY"), so  we have the following: 

```python
MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH: str | None = os.getenv(
    "MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH"
)
...
```
The `getenv` is what returns `str | None`. Are you saying we replace all instances of `os.getenv` with `os.environ`? I have tended to use `os.environ.get` as it's a safer way of getting the env vars without crashing, but it too returns `str | None`.  But in this case, is your thought that a` KeyError` being raised is better?  Hypothetically, earlier in the Merino CI checks, if these configs were invalid, Merino itself wouldn't start up, since the load tests optionally use them down the chain.  

The problem that I ran into is that we instantiate the provider-specific classes with the same default values, however the types of these arguments don't match the classes, which don't support `None`. I was concerned about changing the logic to the load tests to appease the mypy checker, hence the ignore statements, as the `get_<provider)_queries` methods don't match the signatures of the classes they create.  

Let me know your thoughts and if indeed I just change to `os.environ`, I'll do that! Thanks again

2023-09-01 22:16 UTC, linabutler commented on tests/load/locustfiles/locustfile.py
> +            top_picks_file_path=MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH,  # type: ignore
> But in this case, is your thought that a` KeyError` being raised is better?

I'd love to hear others' thoughts, too, but yes, exactly—my thinking is that it's better to raise a `KeyError` early, than to try and run with incomplete configuration, and crash somewhere else later.

> the `get_<provider)_queries` methods don't match the signatures of the classes they create.

That's what made me wonder about switching to `os.environ`. `type: ignore` doesn't prevent the type mismatch; it prevents the type checker from complaining about the mismatch.

If you accidentally forget to set `MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH`, the test will still crash, because it's missing that required setting. But instead of crashing right away with a `KeyError`, it might raise an `AttributeError` from an unrelated portion of code, like when it tries to create a `kinto_http.AsyncClient` or an `Elasticsearch` client, and fails because it's trying to call string methods on `None`.

2023-09-01 22:37 UTC, taddes commented on tests/load/locustfiles/locustfile.py
> +            top_picks_file_path=MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH,  # type: ignore
Makes perfect sense to me @linabutler , let's let the `KeyError` or `AttributeError` do the work of crashing should the settings have a problem. I'll push up the changes!

2023-09-01 23:02 UTC, linabutler commented on tests/load/locustfiles/locustfile.py
> +            top_picks_file_path=MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH,  # type: ignore
Thanks—and thanks for discussing it, too! 😄 I think your instincts about preferring safer APIs are great, and deciding which one to use when is a bit of a judgment call. If you're curious, here's how I like to go about deciding!

In general, I totally agree with you; `dict.get` or `os.getenv` are great choices for when a key is optional, or has a sensible default value. But when there isn't a good default, or the absence of the key really is unexpected—I usually go for failing as fast as possible.

If you forget to set an environment variable, and your test crashes with `KeyError: 'MERINO_PROVIDERS__TOP_PICKS__TOP_PICKS_FILE_PATH'`—you'll know which variable is missing, and what to fix right away! 👀

But using the safe API in this case might end up passing `None` to a call that isn't expecting it. In that case, the test might still crash, but with an error like `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'` or `AttributeError: 'NoneType' object has no attribute 'replace'`. That exception tells you something's `None` that shouldn't be—but what? It can take a bit more sleuthing to figure out that these errors really mean you forgot to set an environment variable.

2023-09-05 16:19 UTC, linabutler approved these changes
Perfect!

2023-09-05 16:23 UTC, linabutler commented
Love the incremental commits, by the way; they made the reviewing experience great!

2023-09-05 16:42 UTC, merged