[DISCO-2525] Merino: Common Task Runbook, How to add to Blocklist
mozilla-services/merino-py pull request #413
Opened 2023-09-01 16:21 UTC by taddes

## References

JIRA: [DISCO-2525](https://mozilla-hub.atlassian.net/browse/DISCO-2525)

## Description
Merino support some providers that have a broad range of potential suggestions. Although we’ve done our best with ensuring that we don’t show anything offensive or questionable to users, we should have some mechanism to ensure that specific instances can be removed or blocked from being displayed. So, this task is to have runbook for us when we need to block specific entries from either 1. being displayed to users by Merino’s API and 2. blocked at the data ingestion level, so during the Merino job that processes these data.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-09-05 19:36 UTC, mtbottle requested changes
2 main points:
1. Let's have 2 runbooks for modifying blocklists: one for Wikipedia and one for Nav Suggestions
2. Runbooks are procedural documentation, so we should make them more like step-by-step instructions. So, there's a place for more "conceptual" stuff, which I think can be the "content-moderation.md" page. This can talk more about how our various content moderation systems look like (i.e. job level filtering vs. runtime level filtering). Conceptual documentation will also do well with more diagrams to illustrate how the system works (if they make sense).

2023-09-05 19:36 UTC, mtbottle commented on docs/operations/blocklists.md
> +Because Merino supports several providers that have a broad range of potential suggestions, often from different sources, we require the ability to remove certain suggestions from being displayed.
nit: newline 

```suggestion
Because Merino supports several providers that have a broad range of potential suggestions, 
often from different sources, we require the ability to remove certain suggestions from being displayed.
```

2023-09-05 19:36 UTC, mtbottle commented on docs/dev/content-moderation.md
> -# Content Moderation
Let's leave this documentation (and maybe move some stuff from the Runbooks over to this). I think we can use this page as more "conceptual" documentation and maybe link the runbooks. Runbooks are procedural documentation, so we want to remove explanation "fluff". But it's still useful to include some of the extra knowledge in other pages so that users can get a better understanding of how our content moderation system works (just have to link them this in the runbook and have this document link to procedural runbooks where necessary).

2023-09-05 19:36 UTC, mtbottle commented on docs/operations/blocklists.md
> +   In this case, suggestions are compared to a static list in the code that blocks out these suggestions.
This can be a bit confusing what we mean by _"category"_ here. Wikipedia has category filtering (i.e. articles tagged with category of "violence" or something will be filtered out). This "category blocklist" currently doesn't get manually updated.

I _think_ you're referring to some sort of string matching filtering. Both Wikipedia and Navigational Suggestions have different ways of matching the stuff in the blocklist. I would actually separate this Runbook into 2 separate runbooks for Wikipedia and Nav Suggestions. They're different enough that our instructions on how to add to block list should be separate.

2023-09-05 20:03 UTC, taddes commented
You read my mind @mtbottle ! I was gonna ask about us splitting them out. I'll make the change to have the conceptual aside and make the step by step changes as requested, good suggestion.

2023-09-07 20:00 UTC, mtbottle requested changes
Just a note on the purpose of a runbook: Runbooks are a set of clear instructions and steps (i.e. procedural documentation) that helps use achieve a specific goal. If we think about modifying a blocklist, the actual thing that we're trying achieve is not returning a bad result to our user. So, we need to include _all_ the steps to make it so that users don't see the suggestion we're trying to "block", which means that we need to consider how to get this out to production and potentially adding a verification step to ensure that it works.

2023-09-08 18:42 UTC, mtbottle reviewed
Almost there! Just a few more comments and an example.

2023-09-11 16:29 UTC, taddes commented
Hey @mtbottle ! Made all the requested changes we discussed for clarity. 

One think I'll leave up to you, whether we want it in or not is the last section of the `blocklist-wikipedia.md` file. I removed the steps for the Indexer Job, as the newly added blocked title will not be included the next time the job runs. Just check out that section. Based on our discussion, let me know if you like it or just want it taken out. Since we describe the provider level and job level blocking, I thought some insight on stating there is no need to re-run the job was valuable, with additional context at the very end as you requested.

2023-09-12 15:53 UTC, mtbottle approved these changes
Generally looks good! Just one confusing step (which can do with a bit more clarification) and a nit for referencing things that haven't been written. Once you've made the changes, feel free to merge!

2023-09-12 15:53 UTC, mtbottle commented on docs/operations/blocklist-nav-suggestions.md
> +5. After image has been built, re-run the Airflow job [here](https://workflow.telemetry.mozilla.org/dags/merino_jobs/graph). To rerun jobs, see [WIP: THIS OTHER RUNBOOK ON HOW TO RE-TRIGGER AIRFLOW]
nit: If we don't have instructions for it yet, let's remove the reference.

```suggestion
5. After image has been built, re-run the Airflow job [here](https://workflow.telemetry.mozilla.org/dags/merino_jobs/graph). 
```

2023-09-12 15:53 UTC, mtbottle commented on docs/operations/blocklist-nav-suggestions.md
> +6. Add the newly generated `top_picks.json` file to source control, open a PR, merge the branch, and deploy Merino.
Oh, do both `domain_blocklist` and `top_picks` get generated after you `apply`? If this is the case, then should we be specific about _not_ adding `top_picks` in step 4? I'm imagining that someone running these commands might be confused about why there's 2 files generated. and why they need to be merged separately.

2023-09-13 02:48 UTC, merged