[DISCO-2598] Add some extra logging to AMO request errors
mozilla-services/merino-py pull request #418
Opened 2023-09-08 14:27 UTC by mtbottle

## References

JIRA: [DISCO-2598](https://mozilla-hub.atlassian.net/browse/DISCO-2598)

## Description
This is to help us hopefully get more information on what is causing the errors for AMO requests.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-09-08 16:53 UTC, taddes requested changes
Hey @mtbottle ! Great addition of the second try/except arm, I think that should help clarify exactly which error is at the root of thigns!  I just added two comments regarding `e.__class__` not necessarily being that useful given that context is provided in `e`. More in the comments.

This should help narrow things down in Sentry for sure, great stuff 👍

2023-09-08 16:53 UTC, taddes commented on merino/providers/amo/backends/dynamic.py
> +
Great addition to determine whether it's the API request or the key!

In looking at this, I'm not sure I see the value in `e.__class__`.  We will get the class as a part of `e`, so in the case of the tests, we get:
 `TimeoutException('timedout!')` for `e`
 `<class 'httpx.TimeoutException'>` for `e.__class__`. 

Given it's kind of the same I'm not sure we need it, since the except statements will trigger from something that's a descendant of `httpx.HTTPError`, so I don't know if it would help all that much. What do you think? 

```suggestion
        except httpx.HTTPError as e:
            logger.error(
                f"Addons API failed request to fetch addon: {addon_key}, {e}"
            )
            return None

```

2023-09-08 16:53 UTC, taddes commented on merino/providers/amo/backends/dynamic.py
> +            )
Same as above. 
`HTTPStatusError("Client error '400 Bad Request' for url 'https://addons.mozilla.org/api/v5/addons/addon/video-downloadhelper'\nFor more information check: https://httpstatuses.com/400")` for `e`

`<class 'httpx.HTTPStatusError'>` for `e.__class__`


```suggestion
            logger.error(
                f"Addons API could not find key: {addon_key}, {e}"
            )
```

2023-09-08 17:50 UTC, mtbottle commented on merino/providers/amo/backends/dynamic.py
> +
Ah, so the current problem is that our errors are logging empty "e". So currently, the only thing we see in the logs are literally: `Addons API could not find key: read-aloud, ` etc. I was hoping that adding the class will let me know which subclass is causing the error to help with investigating the actual issue (as `HttpError` [is really broad](https://www.python-httpx.org/exceptions/)). The only thing that I'm pretty sure it's not is `HTTPStatusError` (not 100, but that _should_ log something... usually some sort of request code in the message).

2023-09-08 17:54 UTC, mtbottle commented on merino/providers/amo/backends/dynamic.py
> +            )
Same as above. This is mainly logging a sanity check, as this _should_ be `HttpStatusError`. It would be interesting to see if this catches any other types of errors as well.

2023-09-11 13:01 UTC, taddes approved these changes
Hey @mtbottle ! After our discussion on this, I poked around a bit to see if there might be some other useful things to throw at logging. Here might be some interesting possibilities to provide the desired sanity check, so long as we can get an error payload at all from HTTPX. I looked at their docs and there's pretty scant details on error handling in general, aside from all the inherited types. Happy to look at this with you more this week, too!

`e.__repr__()` -> TimeoutException('timedout!') 
Within the `except`, before the log emission, use `e.add_note("note here")` and you can access via `e.__dict__`, providing `{'_request': None, '__notes__': ['test']}`, if it helps provide context as to which error is triggering the issue.

2023-09-11 19:51 UTC, merged