[DISCO-2514] Merino Test Docs Hub
mozilla-services/merino-py pull request #421
Opened 2023-09-14 13:52 UTC by taddes

## References

JIRA: [DISCO-2514](https://mozilla-hub.atlassian.net/browse/DISCO-2514)

## Description
Currently, the test documentation exists in the test directory. This makes sense in the code to keep it near the code that executes the function. However, we should probably move the higher level documentation to mdbook and either link or move the set up documentation as well. 

Other test documentation that we’ll probably want in the centralized docs in GitHub:

    High level strategy for service. Types of tests that are run in CI.

    Instructions on how to run tests locally

    Architecture diagram for more involved tests

    Ensure you can test in situ (e.g. can you easily test a mobile devices using a staging server without using a custom build? How hard is it to use this API with a scripting system or CURL? How secure is it from griefing attacks? etc.)

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2023-09-15 13:23 UTC, mtbottle requested changes
A few suggestions and some of the links are not working.

2023-09-15 13:23 UTC, mtbottle commented on docs/testing/contract-tests/index.md
> +# Contract Tests
I think we can reduce one page (and reduce one click-through) by having the overview in here instead. So, the content in `contract-tests/contract-tests.md` can be moved here.

2023-09-15 13:48 UTC, taddes commented on docs/testing/testing-strategy.md
> +[load_tests_docs]: /docs/testing/load-tests.md
Hmm, what IDE are you using? All these links work fine for me in VSCode and Pycharm.  I was avoiding relative links which look messy and have seen this in our docs, but are you refering to when mdbook creates the files? Does it not support absolute paths?

2023-09-15 13:51 UTC, mtbottle commented on docs/testing/testing-strategy.md
> +[load_tests_docs]: /docs/testing/load-tests.md
I run `make doc-preview` and it creates a local `mdbook` server. That's what gets published to https://mozilla-services.github.io/merino-py/ .

2023-09-19 16:24 UTC, taddes commented
All changes made @mtbottle with links to GitHub. Just note the links in preview are broken for the docs on `index` just because the PR is not yet merged. Once merged, those links will be active.

2023-09-22 13:27 UTC, mtbottle approved these changes
Just one comment about linking documentation: if we're referencing documentation (not code), let's use relative paths so that we stay in the same documentation system. Feel free to merge this once the links have been fixed.

2023-09-22 15:27 UTC, taddes commented on docs/testing/index.md
> +- [load][load_tests] - [documentation][load_tests_docs]
Absolutely, good call. Will make the revisions.

2023-09-22 17:11 UTC, merged