[CONSVC-1935] feat: Parse & log user agent
mozilla-services/merino-py pull request #45
Opened 2022-09-07 20:37 UTC by ncloudioj

This adds the user agent parsing & logging feature to merino-py.

Have tried a couple of UA parsing libs: [python-user-agents](https://github.com/selwin/python-user-agents), [woothee-python](https://github.com/woothee/woothee-python), and [uap-python](https://github.com/ua-parser/uap-python). Picking uap-python as it's the fastest one (10x faster than the other two) and it's actively developed & maintained compared to others.
 
This fixes [CONSVC-1935](https://mozilla-hub.atlassian.net/browse/CONSVC-1935).

2022-09-07 20:39 UTC, ncloudioj commented
@tiftran With this change, is  `accept-english` the only missing field for the suggest API log?

2022-09-07 21:15 UTC, quiiver approved these changes
looks good, just some small comments but non-blocking

2022-09-07 22:24 UTC, quiiver commented on merino/middleware/user_agent.py
> +    def parse(ua_str: str) -> tuple[str, str, str]:
@ncloudioj and i chatted about this and it's probably not worth adding

2022-09-08 12:47 UTC, hackebrot requested changes
Hi @ncloudioj! 👋🏻 

The `UserAgentMiddleware` is really light-weight. I like that!

I don't think `parse`, `_parse_browser`, `_parse_os_family`, and `_parse_form_factor` need to be static methods on the starlette middleware class since they are not specific to an HTTP middleware or request. Instead I would define them as functions on the module and probably drop the leading underscore.

I see you've added a number of test scenarios for `parse()` and the code coverage for `merino/middleware/user_agent.py` is at 100%. That's great! 👍🏻 

For the sake of making it easier to debug user-agent parsing related issues, please also add unit tests for the individual functions. Thanks!

2022-09-08 12:47 UTC, hackebrot commented on merino/middleware/user_agent.py
> +    browser: str
I wonder if we should rename this to `client` given that there may be consumers of the API which are not browsers. 🤔

2022-09-08 12:47 UTC, hackebrot commented on tests/middleware/test_user_agent.py
> +FIXTURE = [
```suggestion
SCENARIO = tuple[str, str, str, str]

SCENARIOS: list[SCENARIO] = [
```

2022-09-08 12:47 UTC, hackebrot commented on tests/web/test_user_agent.py
> +    assert len(caplog.records) == 1
This might break if we add additional logging unrelated to the user-agent middleware.

Should we filter by logger here?

2022-09-08 13:37 UTC, Trinaa commented on merino/middleware/user_agent.py
> +                return "linux"
```suggestion
            case {"family": "Ubuntu" | "Fedora" | "Debian" | "Arch Linux" | "Linux"}:
                # This should cover most of main-stream Linux distros
                return "linux"
```

2022-09-08 13:37 UTC, Trinaa commented on merino/middleware/user_agent.py
> +        for those two platforms.
```suggestion
        It takes an extra argument `os_family` to facilitate parsing for Windows
        and Linux form factors, as the underlying parser doesn't adequately identify
        those two platforms.
```

2022-09-08 14:17 UTC, ncloudioj commented
@hackebrot Thanks for your feedback!

> I don't think parse, _parse_browser, _parse_os_family, and _parse_form_factor need to be static methods on the starlette middleware class since they are not specific to an HTTP middleware or request. Instead I would define them as functions on the module and probably drop the leading underscore.

That's a fair point. I think I will define a utility module for ua parsing instead of putting them here.

> For the sake of making it easier to debug user-agent parsing related issues, please also add unit tests for the individual functions. Thanks!

All unit tests are defined in `tests/middleware/test_user_agent.py`, and you're right that only the `parse()` functions were called there, but they should also cover those helper functions as `parse()` is just a wrapper around those underscore functions.

2022-09-08 15:31 UTC, ncloudioj commented on merino/middleware/user_agent.py
> +        ua = user_agent_parser.Parse(ua_str)
It's not type annotated, but I believe it's of type `dict[str, Any]`

2022-09-08 15:33 UTC, ncloudioj commented on merino/middleware/user_agent.py
> +                return browser
Don't think so. The value of the `family` key is guaranteed to be a string with "Other" as the fallback. This is enforced by a unit test.

2022-09-08 15:36 UTC, ncloudioj commented on merino/middleware/user_agent.py
> +    browser: str
I think `browser` should be fine to use here in this context.

2022-09-08 15:37 UTC, ncloudioj commented on tests/web/test_user_agent.py
> +    assert len(caplog.records) == 1
Good point. I will make the change.

2022-09-08 15:39 UTC, hackebrot commented
Hi @ncloudioj! 👋🏻 

> All unit tests are defined in `tests/middleware/test_user_agent.py`, and you're right that only the `parse()` functions were called there, but they should also cover those helper functions as `parse()` is just a wrapper around those underscore functions.

That's correct. We have test coverage for the helper functions via `test_ua_parsing` in `tests/middleware/test_user_agent.py`. However should there be a bug in any of these functions that test can only detect that `UserAgentMiddleware.parse(ua)` produces an unexpected result. But it cannot say which function specifically is causing that failure.

A fine grained unit test design pays off longer term by identifying specific causes of failure, enabling existing or new project members to diagnose issues more confidently and develop and deploy fixes more quickly.

2022-09-08 17:08 UTC, ncloudioj commented on merino/middleware/user_agent.py
> +            request.headers["User-Agent"]
I believe that Starlette.request.Header ensure that those following headers are always present:

```
    "accept",
    "accept-encoding",
    "accept-language",
    "cache-control",
    "user-agent"
```

But yeah, let's not take any changes. I will do `.get("User-Agent", "")` instead.

2022-09-08 17:22 UTC, ncloudioj commented
> That's correct. We have test coverage for the helper functions via test_ua_parsing in tests/middleware/test_user_agent.py. However should there be a bug in any of these functions that test can only detect that UserAgentMiddleware.parse(ua) produces an unexpected result. But it cannot say which function specifically is causing that failure.

All those static methods are now relocated to their own module. Worth pointing out that only the `parse()` function is exposed but not the case for the rest of the helper functions as they don't mean to be used by other modules.  

> A fine grained unit test design pays off longer term by identifying specific causes of failure, enabling existing or new project members to diagnose issues more confidently and develop and deploy fixes more quickly.

Totally agreed. Though I don't think that'll be a major concern in this case. Should any of those helper functions break, it'll be straightforward to tell what the breakage(s) is as `browser`, `os_family`, and `form_factor` don't overlap with each other. If we expose those helper functions in order to make them easier to test, that doesn't look like a good idea to me either.

2022-09-08 18:41 UTC, Trinaa approved these changes

2022-09-12 13:19 UTC, merged