Docs/migrate and update relevant documentation consvc 1854 [do not deploy]
mozilla-services/merino-py pull request #47
Opened 2022-09-09 16:04 UTC by taddes

2022-09-12 14:21 UTC, taddes commented
Hey @ncloudioj , sorry, this wasn't ready for review yet, so apologies if you spent much time. It is behind by several commits and I have a running doc to point out what we want/don't want from the Rust.

2022-09-12 21:48 UTC, taddes commented
Hi @ncloudioj ! Thanks for taking the time to make these configurations for mdBook, looking forward to looking at that some more. Very useful tool. 

I've staged all changes and will bring your attention to a few things we have to look at as we will likely want to discuss our approach to these docs, what we may still want to clarify, what we want to dispose of, etc. I used my judgement to make modifications to the docs, as far as I could determine with certainty the architectural details, configuration details, and setup.  Much of the old Rust info has been replaced with Python-specific analogues, such as Dynaconf, the use of TOML files, logging details.  

I will highlight a few files that I have left in place that clearly relate to the old Rust Merino. I wanted to leave these for us to discuss, as the way in which logging and telemetry, for example, may be a useful model for merino-py.  That or it simply may not be.  Regardless, I wanted to give what was there the benefit of the doubt.
- `intro.md`: added a table of contents here, as it wasn't that useful a file in the Rust version. Thought it would help to orient a reader.
- `ops.md`: may need some attention in the area of Logging and Metrics. I did my best to modify to what I suppose the merino-py config is, but this may differ from Rust.  Mostly, I wanted to retain the keys in case we are structuing our logging and Sentry in a similar way. 
- `dev/index.md`: this file is a little awkward given it repeats some info, so we may want to consider how we want to structure it. Certainly useful to repeat the basic setup of dev dependencies. I might gently recommend we make it a bit more verbose and specific than the README.md in the root. Repository Structure, Recommended Tools and Recommended Reading are artifacts from the old docs, so it may be that we wish to remove these entirely, or add merino-py specifics. Left this here as a to-do for us to discuss. 
- `dev/test.md`: here I removed specific examples that used to be in Rust. Not sure how much more clarity we'd want to add, but I thought the descriptions were sufficient. 

I also took several liberties to rephrase many paragraphs and unclear wording, correct typos. Please correct me if you catch anything else.  I also want to make sure things are clear, so if you read anything that could be phrased better or may not be the best way to convey a point, let me know.

2022-09-13 03:06 UTC, ncloudioj commented
@taddes Your changes look good to me. Thanks again for migrating those over!

I've updated various docs particularly for `data.md` and `ops.md` to reflect the current settings in this repo. I figured that it'd be easier to do so rather than listing them piece by piece as review comments.

That said, now I am also one of the patch makers, so let's get other folks to review this PR :)

2022-09-15 19:15 UTC, tiftran requested changes
Some consistency issues and a suggestion about `accepts_english`

2022-09-15 19:15 UTC, tiftran commented on docs/ops.md
> +- `remote_settings.bucket` (`MERINO__REMOTE_SETTINGS__BUCKET`) -
Single underscore?

2022-09-15 19:15 UTC, tiftran commented on docs/ops.md
> +  (`MERINO__REMOTE_SETTINGS__COLLECTION`) - The collection to use for
Single underscore?

2022-09-15 19:15 UTC, tiftran commented on docs/ops.md
> +  instance.
There's consistency issues with the underscoring. I went and checked I believe it's `MERINO_ENV` with one underscore so we want to change that [here](https://github.com/mozilla-services/merino-py/pull/47/files#diff-f307db903341db35ddf198cb40920f8ab28fc6ea9a2a97556cde1361544c3d6aR22) and maybe remove "Environment variables that being with `MERINO` and use `__` blurb since we have it again under General

2022-09-15 19:15 UTC, tiftran commented on docs/ops.md
> +- `env` (`MERINO__ENV`) - Only settable from environment variables. Controls
single underscore?

2022-09-15 20:14 UTC, taddes commented on docs/data.md
> +  - `accepts_english` - True if the user's Accept-Language header includes an
Good call, I'll do the WIP and make note of it to make sure we address it at some point.

2022-09-15 20:19 UTC, taddes commented on docs/ops.md
> +- `remote_settings.bucket` (`MERINO__REMOTE_SETTINGS__BUCKET`) -
Yeah, this is a good one @tiftran , you mean between MERINO and the remainder of the string? @ncloudioj , did we want 'dunder-scores' to match what was in Merino-rs, or do we want to use single underscores between the levels? I think I recall in the example when you were testing settings, MERINO and a single `_` underscore were followed by the next index, but then `__` for subsequent levels.  This example you had put in Slack made sense:

`MERINO_ENV=production MERINO_LOGGING__FORMAT=pretty make dev`

2022-09-15 20:19 UTC, taddes commented on docs/ops.md
> +  (`MERINO__REMOTE_SETTINGS__COLLECTION`) - The collection to use for
Yeah, for `MERINO__`, eh?

2022-09-15 20:22 UTC, tiftran commented on docs/ops.md
> +- `remote_settings.bucket` (`MERINO__REMOTE_SETTINGS__BUCKET`) -
yes i meant between merino and the remaining string, should've been more clear, sorry 😅

2022-09-15 20:23 UTC, taddes commented on docs/ops.md
> +  instance.
Good call, made that change, consolodated into one comment and clarified the access levels going past `MERINO_`, being that a single underscore is to go one level deeper in the dict, and then two even farther. I just ignored this as we hadn't decided whether to use 1 or 2, but also because my eyes were likely glossing over...

2022-09-15 20:24 UTC, taddes commented on docs/ops.md
> +  instance.
Good call, made that change, consolodated into one comment and clarified the access levels going past MERINO_, being that a single underscore is to go one level deeper in the dict, and then two even farther. I just ignored this as we hadn't decided whether to use 1 or 2, but also because my eyes were likely glossing over...

2022-09-15 20:26 UTC, taddes commented on docs/ops.md
> +- `env` (`MERINO__ENV`) - Only settable from environment variables. Controls
Got it!

2022-09-15 20:48 UTC, taddes commented on docs/ops.md
> +- `remote_settings.bucket` (`MERINO__REMOTE_SETTINGS__BUCKET`) -
Not at all, glad you caught it all the same!

2022-09-15 21:11 UTC, tiftran approved these changes
lgtm 👍

2022-09-15 21:25 UTC, merged