feat: Add Yelp suggestions uploader
mozilla-services/merino-py pull request #478
Opened 2024-01-18 07:14 UTC by dadaa

## References

JIRA: [SNG-928](https://mozilla-hub.atlassian.net/browse/SNG-928)

## Description
We are planning to support Yelp suggestions. This pull request adds an uploader for its dataset.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [x] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-01-18 19:36 UTC, mtbottle commented on merino/jobs/csv_rs_uploader/row_major_base.py
> +class RowMajorBaseSuggestion(BaseSuggestion):
Hmm... this class is missing documentation and should fail linter. Can you try running `make lint` locally? I just turned on the CI to allow it to build from forked repos, but I think you will need to push a new update for them to run.

2024-01-18 21:04 UTC, 0c0w3 requested changes
Thanks @dadaa! This is a pretty good way of adding column-major support to the uploader. A potential improvement in the future is to bypass the chunked uploader for column-major data, since it doesn't really make sense in that case. That would also include not storing the single "suggestion" object in an array in the output JSON but instead storing the object by itself as the top-level object.

As @mtbottle said, please run `make lint` before submitting. That will run a format check plus [mypy](https://mypy-lang.org/), a static type checker for Python that we use.

2024-01-18 23:51 UTC, dadaa commented on merino/jobs/csv_rs_uploader/row_major_base.py
> +class RowMajorBaseSuggestion(BaseSuggestion):
Oh, I found the linting errors. I will fix them. Thank you so much!

2024-01-18 23:53 UTC, dadaa commented on merino/jobs/csv_rs_uploader/yelp.py
> +                    )
Oh, I didn't know that we could do this. Thanks!

2024-01-19 00:03 UTC, dadaa commented on merino/jobs/csv_rs_uploader/row_major_base.py
> +    def csv_to_suggestions(cls, csv_reader) -> dict[str, str]:
Ah, indeed, thanks

2024-01-19 00:10 UTC, dadaa commented on merino/jobs/csv_rs_uploader/base.py
> +    def field_map(cls) -> dict[str, str]:
As this method needs only for row-major-based suggestions, I will remove this.

2024-01-19 00:18 UTC, dadaa commented on docs/operations/jobs/csv-remote-settings.md
> +called `field_map()`. It should return a `dict` that maps from field
Yeah, it will be clearer 👍 Thanks!

2024-01-19 01:13 UTC, dadaa commented on merino/jobs/csv_rs_uploader/row_major_base.py
> +    def csv_to_suggestions(cls, csv_reader) -> dict[str, str]:
Or should use `Self`?
`from typing import Self`

2024-01-19 01:34 UTC, dadaa commented on tests/unit/jobs/csv_rs_uploader/model.py
> +    def field_map(cls) -> dict[str, str]:
Oh, I forgot to update this. I will fix it now.

2024-01-19 01:49 UTC, 0c0w3 commented on merino/jobs/csv_rs_uploader/row_major_base.py
> +    def csv_to_suggestions(cls, csv_reader) -> dict[str, str]:
You can use `list["BaseSuggestion"]` with quotes. That works for me. Does `Self` also work?

2024-01-19 02:23 UTC, dadaa commented on merino/jobs/csv_rs_uploader/row_major_base.py
> +    def csv_to_suggestions(cls, csv_reader) -> dict[str, str]:
Oh, with quotes! I will change it.

> Does Self also work?
Ah, no, I tried it, but it does not work..

2024-01-22 23:28 UTC, 0c0w3 approved these changes
Thanks!

2024-01-22 23:28 UTC, merged