[CONSVC-1963] refactor: Refactor providers to load enabling toggle from config
mozilla-services/merino-py pull request #49
Opened 2022-09-13 21:08 UTC by ncloudioj

This allows us to enable/disable providers via settings.

This fixes [CONSVC-1963](https://mozilla-hub.atlassian.net/browse/CONSVC-1963).

2022-09-13 21:38 UTC, quiiver commented
Based on my understanding of how the way the API is designed to work, we should be able to have providers that can be initialized at application startup but are not enabled by default. This change makes it so that enabling and initialization are intrinsically linked which breaks that design.

2022-09-14 14:20 UTC, ncloudioj commented
> Based on my understanding of how the way the API is designed to work, we should be able to have providers that can be initialized at application startup but are not enabled by default.

Correct, that's indeed part of the API design.

> This change makes it so that enabling and initialization are intrinsically linked which breaks that design.

I don't think this is the case. It still allows us to have providers initialized but not enabled by default. As you can see [here](https://github.com/mozilla-services/merino-py/pull/49/files#diff-7fe7d6e70f4aca4c64c129832043c299b8ff27ab517c08b94cc0f8defa9921a9R50-R53), it initializes all the providers regardless of whether or not it's enabled by default. For example, let's say we have providers: A, B, and C. And we'd like to have A and B enabled by default, and have C not enabled by default. We could do it by using the following configuration:

```
[production.providers.A]
enabled = true

[production.providers.B]
enabled = true

[production.providers.C]
enabled = false
```

All of them will be initialized, but only A and B will be added to the default provider list. One thing I could do is to rename `enabled` to `enabled_by_default` to make it less confusing.

Does that make sense to you?

2022-09-14 17:13 UTC, ncloudioj commented
Alright, renamed the flag from `enabled` to `enabled_by_default`. Also added a unit test for `init_providers()`.

2022-09-15 14:00 UTC, hackebrot requested changes

2022-09-15 19:31 UTC, ncloudioj commented on merino/providers/__init__.py
> +                raise TypeError(f"Unknown provider type: {type}")
> Have you considered defining custom exceptions for Merino? That might make it easier to distinguish between TypeError exceptions raised by Python itself and this specific custom error.

For this one? No, I haven't. It's a "type" error anyway, isn't it :)? But I agree with you a dedicated type error is perhaps clearer.

> We are calling providers.init_providers() in the startup event handler for the FastAPI app. How does FastAPI deal with errors during these handlers?

Any exceptions raised inside of those handlers will make Merino exit, so FastAPI won't intercept those and proceed. I think that's the expected behavior in this case (at application startup). If we were to load providers from other sources at runtime, then we'd need to handle these `TypeError` exceptions for sure.

Re: the test coverage, sure, I can add one for that.

2022-09-15 19:32 UTC, ncloudioj commented on merino/providers/adm.py
> +        return self._enabled_by_default
Yeah, i like the idea about using a property.

2022-09-16 17:50 UTC, hackebrot commented on tests/providers/test_init_providers.py
> +    mocker.patch("merino.providers.adm.Provider._fetch", return_value=future)
Ideally we'd want to set a fake Remote Settings backend for the adm provider in unit tests, so we don't have to mock out the `_fetch` method.

2022-09-16 17:52 UTC, hackebrot commented on tests/web/util.py
> +    @property
Since these inherit from `BaseProvider` we could set `_enabled_by_default = False` on the class and inherit the `enabled_by_default` property from the base class.

2022-09-20 19:35 UTC, ncloudioj commented on merino/providers/wiki_fruit.py
> +    def __init__(self, enabled_by_default: bool = True):
Meant to drop the default value. Nice catch, thanks!

2022-09-20 19:38 UTC, ncloudioj commented on tests/providers/test_init_providers.py
> +    mocker.patch("merino.providers.adm.Provider._fetch", return_value=future)
Agreed. Having to remember to mock this in every test would be annoying. I think we can make the backend configurable to resolve this annoyance.

2022-09-23 13:37 UTC, merged