[DISCO-2777] Add merino job to upload relevancy data to RS
mozilla-services/merino-py pull request #498
Opened 2024-04-09 04:01 UTC by tiftran

## References

JIRA: [DISCO-2777](https://mozilla-hub.atlassian.net/browse/DISCO-2777)

## Description

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-04-09 07:18 UTC, tiftran commented on merino/jobs/relevancy_uploader/__init__.py
> +    "Government": Category.Government,
Took this list from the interest-classification repo and mapped it with the AS classification categories.
Thoughts on how I mapped them, we can def get rid of the inconclusive ones later after the mapping is finalized?

2024-04-11 07:28 UTC, tiftran commented on merino/jobs/relevancy_uploader/__init__.py
> +            suggestion_score_fallback=0,
this is icky... will need to make changes to `ChunkedRemoteSettingsUploader` to remove this

2024-04-11 14:36 UTC, ncloudioj requested changes
Looks good, just a few comments on data processing.

2024-04-11 14:36 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +                            ).hexdigest()
Per spec, I believe we want to base64 encode the MD5 hash digest rather than use the hex digest.

2024-04-11 14:36 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +                                row["origin"].encode(), usedforsecurity=False
Let's use the `domain` field rather than `origin`.

2024-04-11 14:36 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +            categories = row["categories"].strip("[]").split(",")
Looks like the `categories` field could be quoted if it has multiple values. Could you verify whether the csv reader would automatically unquote? If not, we will have to strip those quotes as well.

2024-04-11 14:36 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +    Inconclusive = 19
SERP has `inconclusive` set as 0, let's make it the 1st enum variant as well here.

2024-04-11 14:36 UTC, ncloudioj commented on merino/jobs/utils/chunked_rs_uploader.py
> +    """A class that uploads data to remote settings. Data is
```suggestion
    """A class that uploads data (e.g. suggestions or relevancy inputs) to remote settings. Data is
```

2024-04-11 14:41 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +    Health = 10
Per legal's request, let's drop `Health` for now.

2024-04-11 14:51 UTC, bendk approved these changes
Looks great to me, although I don't understand everything that's going on here.  I mostly just had some suggestions for the docstrings/comments.  I'll mark this approve, because I don't think I need to re-review those changes.

2024-04-11 14:51 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +    "Ecommerce": Category.Inconclusive,
Maybe this could be `Finance`

2024-04-11 14:51 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +MAPPING: dict[str, Category] = {
Nit: Could you what the keys mean?  Maybe the name could be something like `FOO_CATEGORY_TO_R2D2_CATEGORY` or something like that (filling in the blank for FOO, I've already forgotten where we're getting the categories from :rofl: )

2024-04-11 14:51 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +    """Pydantic base model for remote settings relevancy data."""
I think there should be a Pydantict schema here.

2024-04-11 14:51 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +            categories = row["categories"].strip("[]").split(",")
Also, maybe you could use `json.loads` to parse the categories field.  Just a suggestion, I'm not sure if that simplifies things or not.

2024-04-11 14:51 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +            suggestion_score_fallback=0,
Some ickiness seems fine for now.  Could you make a bug for the change and add a comment?

2024-04-11 14:51 UTC, bendk commented on tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py
> +"""Unit tests for chunked_rs_uploader.py."""
Nit: I don't think this has the unit tests, is it support code?  In any case, please clarify what's here.

2024-04-11 15:16 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +    "Ecommerce": Category.Inconclusive,
Hmm, "Ecommerce" is more around online commerce / shopping (amazon, ebay, etc.), whereas "Finance" is more general?

Thinking this again, I think we perhaps could leave those inconclusive categories as is and no need to map them if there are no obvious counterparts? Also, we could collect metrics about the inconclusive interest (as opposed to not collect as we planed) from client so that we could get some ideas about those inconclusive interests as well. So this means we could record one of the three types of metrics for each URL:
- A hit with a conclusive interest, which measures the "power" of the conclusive interests. 
- A hit with an inconclusive interest, which measures the "power" of the inconclusive interests. If it's too strong, we could extract more conclusive interests from this group. 
- A miss meaning that this domain is not on the classification list, The complement of this measures the "power" of the entire classification dataset.

Does that make sense?

2024-04-11 15:21 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +            categories = row["categories"].strip("[]").split(",")
I know that'll be great. But I generated this csv from BigQuery and it didn't serialize the array in JSON but just into a string (or quoted). e.g. either `[Search Engines]` or `"[Search Engines,Information Technology]"`. So I had to do the above hack 😅

2024-04-11 15:38 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +    "Ecommerce": Category.Inconclusive,
So, if we're thinking in terms of counters and vectors, this would mean we now track two inconclusive-style counts:
  - Inconclusive: we know that the URL doesn't fall into any of our categories
  - Unknown/Miss: we don't know if the URL falls into any of our categories

Also, you convinced me that ecommerce should map to inconclusive.

2024-04-11 15:40 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +            categories = row["categories"].strip("[]").split(",")
Ahh, that makes sense.  Nevermind about this one.

2024-04-11 16:12 UTC, tiftran commented on tests/unit/jobs/relevancy_uploader/test_chunked_relevancy_rs_uploader.py
> +"""Unit tests for chunked_rs_uploader.py."""
oopsies typo lemme fix

2024-04-11 17:48 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +    "Ecommerce": Category.Inconclusive,
Yup, two inconclusive counts. Take the 4K dataset as an example,

* Inconclusive (Others): the domain is on the 4K list, but it doesn't fall into any known categories
* Unknown: the domain is not on the list. This can be derived by (`total_input_urls - total_inconclusive_urls - total_conclusive_urls`)

This requires us to send all 4K domains to the client. Whereas if we don't care about the inconclusive count, we don't need to do that.

I am leaning towards including `total_inconclusive_urls`.

WDYT?

2024-04-11 19:02 UTC, bendk commented on merino/jobs/relevancy_uploader/__init__.py
> +    "Ecommerce": Category.Inconclusive,
I like it it, let's to it.  For one thing, I think it will lead to better metrics.

2024-04-15 07:08 UTC, tiftran commented on merino/jobs/relevancy_uploader/__init__.py
> +MAPPING: dict[str, Category] = {
went with `UPLOAD_CATEGORY_TO_R2D2_CATEGORY`

2024-04-15 07:10 UTC, tiftran commented on merino/jobs/relevancy_uploader/__init__.py
> +    """Pydantic base model for remote settings relevancy data."""
I believe there should be in the future when/if things get more complex, but considering we only have domains at the moment, it seemed a little too heavy handed to me. Currently the class only houses the csv -> data conversion method. I could have it not inherit the Pydantic base model?

2024-04-15 14:06 UTC, ncloudioj approved these changes
r+wc! Thanks!

2024-04-15 14:06 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/__init__.py
> +    for category in data:
Nit: at a first glance, I thought `data` was a `list` but it was actually a `defaultdict`. We could do the good old dict iteration here. 

```
for category, domains in data.items():
    # replace all the `data[category]` below with `domains`
```

2024-04-15 14:06 UTC, ncloudioj commented on tests/unit/jobs/relevancy_uploader/test_relevancy_data.csv
> +2,sports.com,sports2.sports.com,https://sports2.sports.com,com,[Sports]
Can we add a few more test records to cover the cases of:
- A multi-category domain, e.g. `[Sports,News]`
- A domain of the `Inconclusive` category

2024-04-17 03:27 UTC, merged