[DISCO-2795] fix: relevancy job to delete records by category
mozilla-services/merino-py pull request #502
Opened 2024-04-17 07:17 UTC by tiftran

## References

JIRA: [DISCO-2795](https://mozilla-hub.atlassian.net/browse/DISCO-2795)

## Description
I accidentally edited `delete_existing_records` default config value by accident
and delete records wasn't deleting properly since I didn't override it for relevancy specifically

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-04-17 13:40 UTC, ncloudioj requested changes

2024-04-17 13:40 UTC, ncloudioj commented on merino/jobs/relevancy_uploader/chunked_rs_uploader.py
> +                and record_details.get("version") == CURRENT_VERSION
Shouldn't we add a CLI argument for version and default to `CURRENT_VERSION` if not specified? Imagine if we bump the version from 1 to 2 later, this won't be able to delete version 1 records.

2024-04-17 15:46 UTC, tiftran commented on merino/configs/default.toml
> +delete_existing_records = true
true was the original default, i swapped it to false while testing and accidentally committed the change

2024-04-17 15:47 UTC, tiftran commented on merino/jobs/relevancy_uploader/chunked_rs_uploader.py
> +                and record_details.get("version") == CURRENT_VERSION
yes, this makes sense will do

2024-04-24 18:32 UTC, ncloudioj approved these changes
LGTM!

2024-04-24 22:46 UTC, merged