feat(cacheHeader): [DISCO-2781] set http cache-control header for weather response
mozilla-services/merino-py pull request #505
Opened 2024-04-18 21:15 UTC by Herraj

## References

JIRA: [DISCO-TODO](https://mozilla-hub.atlassian.net/browse/DISCO-TODO)

## Description

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-04-18 21:26 UTC, Herraj commented on merino/providers/weather/backends/accuweather.py
> +
This is script is very similar to the above `bulk_fetch` script. It returns an integer. Depending on the keys, it could be `-2`, `-1`, or the `TTL`.

2024-04-18 21:26 UTC, Herraj commented on merino/providers/weather/backends/accuweather.py
> +
This method is also very similar to the above `get_weather_report` method. Returns an `int` or `None` depending on what the script returns.

2024-04-18 21:26 UTC, Herraj commented on merino/providers/weather/backends/protocol.py
> +
implemented in `accuweather.py`

2024-04-19 03:04 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +
How about we move this ttl bit over to `bulk_fetch` and add a new return value for ttl?

2024-04-19 03:13 UTC, ncloudioj commented on merino/web/api_v1.py
> +    if len(search_from) == 1 and search_from[0].name == ProviderType.ACCUWEATHER:
Or you could try pattern matching :)

```py
match search_from:
    case [AccuweatherProvider()]:  # A single element list with a particular provider
        #...
    case _:
        # other providers
```

2024-04-23 21:07 UTC, ncloudioj requested changes

2024-04-23 21:07 UTC, ncloudioj commented on merino/providers/weather/provider.py
> +        print(f"*********** IN QUERY: {srequest}")
Forgot to remove the debugging printouts?

2024-04-23 21:07 UTC, ncloudioj commented on merino/web/api_v1.py
> +        response_headers = {"Cache-Control": f"public, max-age={weather_report_ttl}"}
What do you think about using a default TTL (e.g. 300 seconds) if `weather_report_ttl` is None? If you agree, we can add a configuration for this to default.toml.

2024-04-23 21:07 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +        0: "Error getting TTL. Location Key not found.",
It will return an empty array if the location key is missing. So I guess it shouldn't be possible to have a 0 ttl?

2024-04-23 21:07 UTC, ncloudioj commented on merino/web/api_v1.py
> +    print(f"----> response: {response}")
Let's clean up those debugging artifacts.

2024-04-29 17:28 UTC, Herraj commented on merino/providers/weather/backends/accuweather.py
> +                ttl=min(current_conditions.ttl, forecast.ttl),
This addresses the use case where we have to make a new accuweather request on a cache miss. This `ttl` value will always be set to `1800` given our current config values i.e:
```
current_condition_ttl_sec = 1800 # 1/2 hr

forecast_ttl_sec = 3600 # 1 hr
```

This is because when store the newly requested data in the cache, we do a `max()` of our default^ values and the `reponse_expiry` received from accuweather. The result is the default value for both ttls. And then we `min()` those two values here i.e 1800 vs 3600. 

We also set a default of ttl for the reponse of `300` seconds (see above `default.toml`) for cases when the ttl that is bubbled up is returned as `None` for reason / error.

Thoughts on this?

2024-04-29 17:29 UTC, Herraj commented on merino/web/api_v1.py
> +        response_headers = {"Cache-Control": f"public, max-age={weather_report_ttl}"}
Good suggestion! I've added a comment below regarding that.

2024-04-29 19:01 UTC, ncloudioj reviewed
It looks great, would like to take another look at it once the tests turn green :)

2024-04-29 19:01 UTC, ncloudioj commented on merino/web/api_v1.py
> +                "Cache-control": f"public, max-age={default_weather_report_ttl}"
```suggestion
                "Cache-control": f"private, max-age={default_weather_report_ttl}"
```

Let's do private here as the weather suggestion may be customized (for specific locations) for the user.

2024-05-07 00:51 UTC, Herraj commented on merino/configs/default.toml
> +
Do we need to add this to the the `cloudops-infra` repo?

2024-05-07 13:09 UTC, ncloudioj approved these changes
r+wc.

Thanks, this looks great!

2024-05-07 13:09 UTC, ncloudioj commented on merino/web/api_v1.py
> +        response_headers["Cache-control"] = f"private, max-age={ttl}"
Let's always set this header to be consistent. Alternatively, we can replace all the `None`s in `get_ttl_for_cache_control_header()` so it'll always retrun a valid TTL.
```suggestion
    ttl = get_ttl_for_cache_control_header(search_from, suggestions) or DEFAULT_CACHE_CONTROL_TTL
    response_headers["Cache-control"] = f"private, max-age={ttl}"
```

2024-05-07 18:35 UTC, merged