[CONSVC-1947] test: align contract test tech stack with application
mozilla-services/merino-py pull request #52
Opened 2022-09-14 00:17 UTC by Trinaa

## Description
* update contract-tests client and kinto-setup from python 3.8 to 3.10
* merge 'tests' and 'test-engineering' directories
* align mypy checks
* migrate contract-tests client and kinto-setup from pip-tools to poetry

## Issue(s)
[CONSVC-1947](https://mozilla-hub.atlassian.net/browse/CONSVC-1947)

2022-09-14 17:15 UTC, Trinaa commented
@taddes There may be some overlap with your mypy work in the following files:
- .pre-commit-config.yaml
- Makefile
- pyproject.toml

2022-09-15 11:38 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

I like the new structure! It makes a lot of sense to me. 👍🏻 

I've added a few comments inline.

2022-09-15 11:38 UTC, hackebrot commented on tests/contract/client/Dockerfile
> +RUN poetry export --no-interaction --dev --output requirements.txt --without-hashes
TIL! 💡

2022-09-15 11:38 UTC, hackebrot commented on tests/contract/client/pyproject.toml
> +build-backend = "poetry.core.masonry.api"
How did you choose this backend?

2022-09-15 11:38 UTC, hackebrot commented on tests/contract/client/tests/conftest.py
> +    def fetch_icon_url(suggestion_title: str) -> str:
The `*` is so that the method only accepts keyword arguments.

Do you think we should change that?

2022-09-15 11:38 UTC, hackebrot commented on tests/contract/client/tests/test_merino.py
> +    kinto_step: Callable[[Step], None], merino_step: Callable[[Step], None]
We could use a `typing.Protocol` or type alias for this:

```python
StepFunction = Callable[[Step], None]

@pytest.fixture(scope="session", name="step_functions")
def fixture_step_functions(
    kinto_step: StepFunction, merino_step: StepFunction
) -> dict[Service, StepFunction]:
    pass
```

2022-09-15 11:38 UTC, hackebrot commented on tests/contract/kinto-attachments/.gitignore
> +main
I believe we have this here so that we can have an empty directory in the repo. What is this change for?

2022-09-15 11:38 UTC, hackebrot commented on tests/load/tests/locustfile.py
> +from client_info import DESKTOP_FIREFOX, LOCALES
What this order determined by isort?

2022-09-15 11:38 UTC, hackebrot commented on tests/load/tests/locustfile.py
> +    headers: Dict[str, str] = {  # nosec
What does `# nosec` do?

2022-09-15 13:56 UTC, ncloudioj commented on pyproject.toml
> +types-PyYAML = "^6.0.11"
Are these two deps for mypy?

2022-09-15 14:07 UTC, Trinaa commented on tests/contract/client/pyproject.toml
> +build-backend = "poetry.core.masonry.api"
This must be the default. This file was generated with `poetry init`. Is there a value that would be better?

2022-09-15 14:07 UTC, Trinaa commented on tests/contract/client/tests/conftest.py
> +    def fetch_icon_url(suggestion_title: str) -> str:
It's that mypy raises the following error. I find the suggestion verbose and opted for less specificity. Perhaps there is another way?
<img width="463" alt="image" src="https://user-images.githubusercontent.com/3422688/190422906-e43a4046-3b85-4aa2-b46e-cc4a5190ffbd.png">

2022-09-15 14:10 UTC, Trinaa commented on tests/contract/client/tests/test_merino.py
> +    kinto_step: Callable[[Step], None], merino_step: Callable[[Step], None]
This is much better.

2022-09-15 14:10 UTC, Trinaa commented on tests/contract/kinto-attachments/.gitignore
> +main
That's a good catch! ty! I didn't change this explicitly, an IDE side-effect possibly.

2022-09-15 14:11 UTC, Trinaa commented on tests/load/tests/locustfile.py
> +from client_info import DESKTOP_FIREFOX, LOCALES
Yes.
<img width="758" alt="image" src="https://user-images.githubusercontent.com/3422688/190424352-c9598e9e-b7ab-48f2-9e56-829e872d6ec0.png">

2022-09-15 14:11 UTC, Trinaa commented on tests/load/tests/locustfile.py
> +    headers: Dict[str, str] = {  # nosec
It quiets bandit.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3422688/190425151-de71e762-f579-4c59-ac6a-fbec627f3155.png">

2022-09-15 14:15 UTC, Trinaa commented on pyproject.toml
> +types-PyYAML = "^6.0.11"
Yes that's right. Without them we get 'Library stubs not installed' errors.

2022-09-15 14:40 UTC, hackebrot commented on tests/contract/client/pyproject.toml
> +build-backend = "poetry.core.masonry.api"
I don't have a lot of experience with poetry myself. Looks like we're using the same backend for the merino package. So that seems reasonable to me! 👍🏻

2022-09-15 14:41 UTC, hackebrot commented on tests/contract/client/tests/conftest.py
> +    def fetch_icon_url(suggestion_title: str) -> str:
Ok, got it! Let's go with your suggest change then!

2022-09-15 14:43 UTC, hackebrot commented on tests/load/tests/locustfile.py
> +from client_info import DESKTOP_FIREFOX, LOCALES
Okay! 🤖

2022-09-15 16:51 UTC, hackebrot approved these changes
It's possible I've missed something in this 70 files diff, but the updated revision looks good to me. Let's merge it! 🚀

2022-09-15 17:02 UTC, ncloudioj approved these changes
:shipit:

2022-09-15 18:52 UTC, merged