[MC-1270] feat: Handle curated-corpus-api GraphQL errors
mozilla-services/merino-py pull request #573
Opened 2024-07-18 10:05 UTC by nina-py

## References

JIRA: https://mozilla-hub.atlassian.net/browse/MC-1270

## Description

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-07-19 04:46 UTC, mmiermans reviewed
Good call on getting feedback early. I now realize the Jira ticket was ambiguous on several aspects. Hopefully these comments clarify what I think the desired behavior is. 🙏

2024-07-19 04:46 UTC, mmiermans commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +                logger.exception(error)
My bad.. I realize the Jira ticket is ambiguous about what I think should happen.

I don't think this response will have (partially) useful data if there is a GraphQL error, so I think it's better to raise an exception here, and not continue execution of the function.
```suggestion
            raise BackendError("curated-corpus-api returned GraphQL error(s) {data["errors"]}")
```
You can import `BackendError` using `from merino.exceptions import BackendError`.

In `_revalidate_cache` I would catch this BackendError along with the HTTPError, by changing `except BackendError as e:` to `except (HTTPError, BackendError) as e:`.

2024-07-19 04:46 UTC, mmiermans commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +            curated_recommendations = []
These changes can be reverted. This method should raise an exception if recommendations can't be updated. It is called by `_revalidate_cache`, which will continue to serve recommendations from the stale cache when exceptions happen.

2024-07-19 04:46 UTC, mmiermans commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +        assert response.status_code == 200
We don't want a 200 code to be returned when a fatal exception happens. Firefox clients are designed to gracefully handle 5xx errors from our endpoint, and returning clear error status codes improves our observability.

Instead, I would modify `test_single_request_multiple_failed_fetches` as follows, to confirm that we can recover from temporary GraphQL errors:
```python
    @freezegun.freeze_time("2012-01-14 00:00:00", tick=True, tz_offset=0)
    @pytest.mark.parametrize("error_type", ["graphql", "http"])
    @pytest.mark.asyncio
    async def test_single_request_multiple_failed_fetches(
        self,
        corpus_http_client,
        fixture_request_data,
        fixture_response_data,
        fixture_graphql_200ok_with_error_response,
        caplog,
        error_type,
    ):
        """Test that only a few requests are made to the curated-corpus-api when it is down."""
        async with AsyncClient(app=app, base_url="http://test") as ac:
            start_time = datetime.now()

            def temporary_downtime(*args, **kwargs):
                # Simulate the backend being unavailable for 0.2 seconds.
                if datetime.now() < start_time + timedelta(seconds=0.2):
                    if error_type == "graphql":
                        return Response(
                            status_code=200,
                            json=fixture_graphql_200ok_with_error_response,
                            request=fixture_request_data
                        )
                    elif error_type == "http":
                        return Response(status_code=503, request=fixture_request_data)
                else:
                    return Response(
                        status_code=200,
                        json=fixture_response_data,
                        request=fixture_request_data,
                    )

            corpus_http_client.post = AsyncMock(side_effect=temporary_downtime)

            # Hit the endpoint until a 200 response is received.
            while datetime.now() < start_time + timedelta(seconds=1):
                try:
                    result = await fetch_en_us(ac)
                    if result.status_code == 200:
                        break
                except HTTPStatusError:
                    pass

            assert result.status_code == 200

            # Assert that we did not send a lot of requests to the backend
            # call_count is 400+ for me locally when CorpusApiBackend._backoff_time is changed to 0.
            assert corpus_http_client.post.call_count == 2

            # Assert that a warning was logged with a descriptive message.
            warnings = [r for r in caplog.records if r.levelname == "WARNING"]
            assert len(warnings) == 1
            if error_type == "graphql":
                # TODO: Assert the expected warning is logged.
                assert (
                    "Could not find Scheduled Surface with id of \"NEW_TAB_EN_UX\"."
                ) in warnings[0].message
            elif error_type == "http":
                assert (
                    "Retrying CorpusApiBackend._fetch_from_backend once after "
                    "Server error '503 Service Unavailable'"
                ) in warnings[0].message
```
(untested code.)

Alternatively or additionally, you could assert that the right error was sent to Sentry, but I don't think that's necessary, and it's not done anywhere else in Merino. Recommendation-api does have examples of Sentry tests.

2024-07-19 08:34 UTC, nina-py commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +        assert response.status_code == 200
Updated, thank you @mmiermans! ⭐

2024-07-19 11:06 UTC, mmiermans commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +    async def test_single_request_multiple_failed_fetches_with_graphql_error(
This was meant to replace `test_single_request_multiple_failed_fetches` below.

2024-08-01 11:16 UTC, nina-py commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +    async def test_single_request_multiple_failed_fetches_with_graphql_error(
Done!

2024-08-01 14:16 UTC, efixler commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +            raise BackendError(f"curated-corpus-api returned GraphQL error(s) {data["errors"]}")
Aren't these errors already logged in Sentry at the corpus step? Just wondering if it's really wothwhile to insert them again.

2024-08-01 14:21 UTC, efixler commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +            except (BackendError, HTTPError, ValueError) as e:
cc @katerinachinnappan : I'm not clear here how these changes interact with the recent changes you've made to error handling and caching in the endpoint, probably worth a close look from you.

2024-08-01 14:25 UTC, efixler commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +            raise BackendError(f"curated-corpus-api returned GraphQL error(s) {data["errors"]}")
Also, is GraphQL error catching (e.g. the 200 status that is an error) new to this PR? If that's the case, I'm inferring that we were only catching Gateway errors before but that these errors were passing through. (which I think would explain why all of the errors we do we from the GraphQL layer are 502s)

2024-08-01 14:29 UTC, efixler commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +                except (BackendError, HTTPError, ValueError) as e:
Why are we raising these as backend Errors and not HTTPErrors? I think (please confirm @katerinachinnappan ) that we are currently catching Apollo-sources errors as HTTPErrors. This seems appropriate since the Apollo/GraphQL is _not_ the backend here, it's a service that's being consumed. 

This may be an appropriate error, but I want to double check. Let's please be consistent about how we're raising errors that come from the corpus.

2024-08-01 14:32 UTC, efixler requested changes
Please make sure to insert Corpus errors into the appropriate StatsD metric so they make their way into the [Grafana dashboard](https://earthangel-b40313e5.influxcloud.net/d/nqIyrq%5FSk/merino-py-curated-recommendations?orgId=1&var-environment=stagepy&var-canary=All&from=1721076381565&to=1721077470717).

You will need to insert at a fabricated code since 200 will look like an OK. 500 is probably fine.

2024-08-02 03:21 UTC, katerinachinnappan reviewed
@nina-py ty for reminding us with this PR that graphql errors return 200 + error message. PR looks good, I would only suggest to create a corpus api backend error specific class, derived from Merino `BackendError`. & would prob be good to check that [graphql errors are tracked in StatsD metrics](https://github.com/mozilla-services/merino-py/blob/main/tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py#L591)

2024-08-02 03:21 UTC, katerinachinnappan commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +            except (BackendError, HTTPError, ValueError) as e:
we missed that corpus API / graphql sub-graphs mask errors, returns a 200 status code with an error message. In this case `HTTPError` would only get caught on the gateway level, the 502 we have seen. that also explains why [these errors](https://mozilla.sentry.io/issues/5623243151/?project=6622434&referrer=project-issue-stream) in Merino were not handled, because they weren't treated as `HTTPErrors`. I think we should still catch `HTTPError`, `ValueError`. Handling GraphQL errors with `BackendError` seems ok, though I would instead make a derived class `CorpusAPIBackendError` from `BackendError`:

`class CorpusAPIBackendError(BackendError)`. Merino does this already for another backend I think. & would raise & catch `CorpusAPIBackendError` to be a bit more specific.

2024-08-02 03:27 UTC, katerinachinnappan commented on merino/curated_recommendations/corpus_backends/corpus_api_backend.py
> +                except (BackendError, HTTPError, ValueError) as e:
we haven't been catching graphql errors yet, only `httperrors`, so the `httpError` would not get caught if corpus API responded with a 200 + error message.

2024-09-10 00:48 UTC, nina-py commented
Closing in favour of https://github.com/mozilla-services/merino-py/pull/621

2024-09-10 00:48 UTC, closed without merging