[MC-1201] feat: Ensure preferred topic is in top 2
mozilla-services/merino-py pull request #576
Opened 2024-07-18 21:04 UTC by katerinachinnappan

## References

JIRA: https://mozilla-hub.atlassian.net/browse/MC-1201

## Description
Find first item with topic in `preferred_topics` & move it to the 2nd slot in list of returned recs.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [x] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-07-19 03:43 UTC, mmiermans reviewed
Thanks! Awesome to see both you and Jonathan implement ranking code. I think this is almost there.

2024-07-19 03:43 UTC, mmiermans commented on merino/curated_recommendations/provider.py
> +    ):
```suggestion
    ) -> list[CuratedRecommendation]:
```

2024-07-19 03:43 UTC, mmiermans commented on merino/curated_recommendations/provider.py
> +                recommendations, curated_recommendations_request.topics
A preferred topic should only be boosted up if the top 2 don't already contain a preferred topic.
```suggestion
            if not any(r.topic in curated_recommendations_request.topics for r in curated_recommendations_request[:2]):
                recommendations = self.boost_preferred_topic(
                recommendations, curated_recommendations_request.topics
```
^ Just meant to convey the basic idea. You can extract that logic into a method to improve readability. You may also want to extract 2 into a variable to avoid magic numbers.

2024-07-19 03:43 UTC, mmiermans commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +
Could you add tests that assert the order is not changed if the first or second recommendation is already preferred? Could be a parameterized test.

2024-07-19 03:43 UTC, mmiermans commented on merino/curated_recommendations/provider.py
> +        # condition for boostable item: check if an item has a topic in the preferred_topics list.
```suggestion
        # get the first item from the list with a preferred topic starting after the boostable_slot
```
I would refer to `boostable_slot` instead of 3rd, because the argument that may be given a different value in the future.

2024-07-22 14:47 UTC, jpetto requested changes
nothing blocking except removing the `print` statements, but also added some suggestions for small improvements.

nice work!

2024-07-22 14:47 UTC, jpetto commented on merino/curated_recommendations/provider.py
> +        top_two_recs = recs[:2]  # slice operator, get the first two recs (index 0 & 1)
`2` here might be nice to have in a config, or even as a parameter with a default like in `boost_preferred_topic` below.

2024-07-22 14:47 UTC, jpetto commented on merino/curated_recommendations/provider.py
> +        """Check if top 2 recommendations already have the preferred topics.
would be nice to have a little more context here - why are we checking?

2024-07-22 14:47 UTC, jpetto commented on merino/curated_recommendations/provider.py
> +            recs = copy(recs)  # Don't change the input, make a temp copy
but isn't this changing the input by using the same variable name? it's making a copy of itself and storing it in the same container. 😅

2024-07-22 14:47 UTC, jpetto commented on tests/unit/curated_recommendations/test_provider.py
> +        print(reordered_recs)
can we drop this? guessing a debug statement...

2024-07-22 14:47 UTC, jpetto commented on tests/unit/curated_recommendations/test_provider.py
> +        print(reordered_recs)
same - can we remove this?

2024-07-22 14:47 UTC, jpetto commented on tests/unit/curated_recommendations/test_provider.py
> +        print(reordered_recs)
and one more 😀

2024-07-22 14:47 UTC, jpetto commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +            )  # noqa
instead of digging in to the returned array, what do you think about just making sure that `is_boostable` and `boost_preferred_topic` have been called?

you've got unit tests for those functions below that verify specific behavior - could be good enough in this test (and the one below) just to make sure those boost functions were/were not called as expected.

2024-07-22 17:44 UTC, katerinachinnappan commented on merino/curated_recommendations/provider.py
> +            recs = copy(recs)  # Don't change the input, make a temp copy
@jpetto this comes from recs api and from my understanding, this creates a shallow copy of the `recs` list. Any changes made to `recs` within this function do not affect the original input list.

2024-07-22 17:45 UTC, katerinachinnappan commented on merino/curated_recommendations/provider.py
> +            recs = copy(recs)  # Don't change the input, make a temp copy
the comment might be confusing, I will change it

2024-07-22 18:08 UTC, katerinachinnappan commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +            )  # noqa
good call, I will update the test

2024-07-22 19:40 UTC, jpetto commented on merino/curated_recommendations/provider.py
> +            recs = copy(recs)  # Don't change the input, make a temp copy
oh yes, because python passes by reference and not by value. this might read confusing to me as i'm used to javascript passing by value.

2024-07-22 21:03 UTC, jpetto approved these changes
nice work!

2024-07-22 21:12 UTC, merged