[DISCO-2945]: Handle get location by geolocation exceptions
mozilla-services/merino-py pull request #597
Opened 2024-08-12 12:01 UTC by Herraj

## References

JIRA: [DISCO-2945](https://mozilla-hub.atlassian.net/browse/DISCO-2945)

## Description
We are seeing SSLErrors, EndOfStream and other errors for location endpoints for Accuweather. These errors are recent and unexpected. I've also reinforced the `current conditions` and `forecast` try-excepts too. These two aren't erroring out for now but I've added them as a precaution.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-08-12 16:12 UTC, tiftran commented on merino/providers/weather/backends/accuweather.py
> +            ) from exc
because I made the mistake last time.... do we know what `exc` could spit out? specifically could it spit out the url path with the api key?

2024-08-12 18:37 UTC, ncloudioj requested changes
Looks good. A few minor changes are requested.

2024-08-12 18:37 UTC, ncloudioj commented on tests/unit/providers/weather/backends/test_accuweather.py
> +from anyio import EndOfStream
I believe that `EndOfStream` is unintentionally leaked by `httpx`. Also, `anyio` is an indirect dependency from httpx, which might get dropped by `httpx` in the future. Let's not use it in our code, feel free to fake another exception (it's okay to use the ones not observed in prod) for testing.

2024-08-12 18:37 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +            ) from exc
Nice catch, Tif. To avoid that, I think we can only include the error class type for now, wdyt?

2024-08-12 18:37 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +                f"Failed to get location completion from Accuweather: " f"{http_error}"
The `http_error` is likely to include the credentials, let's be extra mindful here as well.

2024-08-12 18:37 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather.py
> +        except Exception as exc:
Looks like those catch-all branches are not being tested, can you please check the test coverage report and fix them accordingly. Alternatively, I think it's fine to opt out the coverage check here as just intentionally catch all unexpected errors and convert them into `AccuweatherError`s.

2024-08-13 17:16 UTC, ncloudioj approved these changes
Looks great, thanks!

2024-08-13 17:43 UTC, merged