[DISCO-3003] Add Accept-Language header
mozilla-services/merino-py pull request #635
Opened 2024-09-23 21:14 UTC by tiftran

## References

JIRA: [DISCO-3003](https://mozilla-hub.atlassian.net/browse/DISCO-3003)

## Description
Suggest endpoint to parse the Accept-Language header and filter out languages to only the ones it support

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|warn)]` keywords are applied (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-09-23 21:14 UTC, tiftran commented on merino/configs/default.toml
> +default_languages  = ["de", "en-CA", "en-GB", "en-US", "es-ES", "fr", "it", "pl", "pt-BR", "ru", "zh-CN"]
I thought our "tier 1" locales would be a good start.

2024-09-23 21:16 UTC, tiftran commented on merino/web/api_v1.py
> +    _ = get_accepted_languages(accept_language)
since it's not being currently used.

2024-09-24 14:08 UTC, gruberb commented on merino/web/api_v1.py
> +    _ = get_accepted_languages(accept_language)
Then why calling it? Or at least, add a comment why it's not being used and still  being called here?

2024-09-24 15:26 UTC, ncloudioj requested changes

2024-09-24 15:26 UTC, ncloudioj commented on merino/web/api_v1.py
> +    if languages:
Some notes:
- Let's wrap the parsing block inside a try..except block to protect against malformed inputs
- Let's parse all the accept languages and leave the default_languages filtering to individual downstream consumers
- Optionally, we can decorate this parser with `@functools.lru_cache(maxsize=1000)` for memorization

2024-09-24 20:11 UTC, tiftran commented on merino/web/api_v1.py
> +    _ = get_accepted_languages(accept_language)
gah, sorry i didn't finish my thought above. I was planning to have it consumed/used in a follow up PR. Yes agreed, was going to put it into SuggestionRequest, wanted to keep this PR tiny 😅

2024-09-24 22:36 UTC, tiftran commented on merino/web/api_v1.py
> +    if languages:
Agreed that we should wrap the block in a try/except block, but not sure what exceptions that could pop up. `split` returns a list even if the split string does not exist. quality logic also handles an index error if the quality value doesn't exist.

2024-09-26 16:46 UTC, ncloudioj approved these changes
Looks good, r+wc.

2024-09-26 16:46 UTC, ncloudioj commented on merino/web/api_v1.py
> +    accept_language: Annotated[str | None, Header()] = None,
```suggestion
    accept_language: Annotated[str | None, Header(max_length=HEADER_CHARACTER_MAX)] = None,
```

2024-09-26 16:46 UTC, ncloudioj commented on merino/web/api_v1.py
> +def get_accepted_languages(languages: str) -> list[str]:
```suggestion
def get_accepted_languages(languages: str | None) -> list[str]:
```

2024-09-26 16:46 UTC, ncloudioj commented on tests/unit/web/test_api_v1.py
> +def test_get_accepted_languages(languages, expected_filtered_languages):
Let's add a test case for the exception handling path.

2024-09-26 20:39 UTC, tiftran commented on tests/unit/web/test_api_v1.py
> +def test_get_accepted_languages(languages, expected_filtered_languages):
("en-CA;q=invalid", ["en-US"]), should technically cover the exception path?

2024-09-26 20:42 UTC, ncloudioj commented on tests/unit/web/test_api_v1.py
> +def test_get_accepted_languages(languages, expected_filtered_languages):
Right, sorry, I didn't realize that.

2024-09-26 20:53 UTC, merged