[DISCO-3086] weather: add city skip list
mozilla-services/merino-py pull request #719
Opened 2024-11-26 00:43 UTC by tiftran

## References

JIRA: [DISCO-3086](https://mozilla-hub.atlassian.net/browse/DISCO-3086)

## Description
There are cities that accuweather does not provide weather for. Instead of constantly requesting them, we should skip them. Cities are from taken from logs.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [ ] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|skip|warn)]` keywords are applied to the last commit message (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-11-26 05:10 UTC, tiftran commented on merino/providers/weather/backends/accuweather/backend.py
> +                if not is_in_skip_cities_list(country, city):
We should do something like the successful_regions_mapping, to automatically input cities into the skip list, but I'm going hold off until we have the distance calculation in place, so that we still have logs for those cases.

2024-11-26 21:28 UTC, ncloudioj requested changes

2024-11-26 21:28 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/pathfinder.py
>              case ("US" | "CA", _):
Maybe we simplify this by:

```py
        match (country, city):
            case ("US" | "CA", _) if (country, regions[0], city) not in SKIP_CITIES_LIST:
                yield country, regions[0], city  # use the most specific region
            case ("US" | "CA", _):
                return
            ...
```

Then you don't need `if any((country, region, city))` in `explore()` b/c the generator is empty and it will enter the loop.

2024-11-26 21:28 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/backend.py
> +        if not is_in_skip_cities_list(country, city):
How about we add a boolean to `explore()`'s return value indicating whether or not the exploration was skipped? Then we don't need to check that again here.

2024-11-26 21:28 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/pathfinder.py
> +        ("CA", "QC", "Montreal West"),
Those are good candidate for `CITY_NAME_CORRECTION_MAPPING`:
  "Montreal West" => "Montreal";
  "Kleinburg Station" => "Kleinburg";

2024-11-26 21:28 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/pathfinder.py
> +def is_in_skip_cities_list(country: str | None, city: str | None) -> bool:
Looks like this is only used by the weather beckend, see my previous comment. If we return a `is_skipped` boolean from `explore()`, this should be unneeded.

In case of you need it anyway, I'd recommend generating another set based on the original one rather than doing it for every call.

```py
SKIP_LOCATION_LIST = [
    ("", "", ""),
    ...
]

SKIP_LOCATION_SET: frozenset = frozenset(SKIP_LOCATION_LIST)

SKIP_COUNTRY_CITY_SET: forzenset = frozenset(coutry, city for country, _, city in SKIP_LCOATION_LIST)


```

2024-11-27 19:36 UTC, tiftran commented on merino/providers/weather/backends/accuweather/backend.py
> +        if is_skipped:
I realized there's no need to continue, if we know the tuple is in the skip list

2024-11-27 19:41 UTC, tiftran commented on merino/providers/weather/backends/accuweather/backend.py
> +            return None
I realized that if we know city, region, country is in the skip list, there's no need to continue from this point

2024-11-27 20:46 UTC, ncloudioj approved these changes
r+wc.

2024-11-27 20:46 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/backend.py
> +
```suggestion
```

2024-11-27 20:46 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/backend.py
> +                location, _ = await pathfinder.explore(
There is a logging statement down below, shall we check `is_skipped` for conditional logging?

2024-11-27 20:46 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/pathfinder.py
> +def is_in_skip_cities_list(country: str | None, city: str | None) -> bool:
This can be dropped now.

2024-11-27 20:46 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/pathfinder.py
> +            return None, True
```suggestion
            return None, is_skipped
```

2024-11-27 20:46 UTC, ncloudioj commented on merino/providers/weather/backends/accuweather/pathfinder.py
> +            case ("US" | "CA", _) if (country, regions[0], city) not in SKIP_CITIES_LIST:
Just realized that this check is only applied to "US" and "CA" locations here, what if we move the skip-city check from here to "explore()" instead so `compass` doesn't need to worry about this any more?

```py
    for country, region, city in compass(location):
        if (country, region, city) in SKIP_CITIES_LIST:
            return None, True
       ...
```

2024-11-27 21:24 UTC, tiftran commented on merino/providers/weather/backends/accuweather/pathfinder.py
> +            case ("US" | "CA", _) if (country, regions[0], city) not in SKIP_CITIES_LIST:
oh that makes things much nicer

2024-11-27 22:01 UTC, merged