HNT-260: Hardcode localized topic section titles for US & Germany
mozilla-services/merino-py pull request #721
Opened 2024-11-27 21:28 UTC by katerinachinnappan

## References

JIRA: https://mozilla-hub.atlassian.net/browse/HNT-260

## Description

Created a `LOCALIZED_TOPIC_SECTION_TITLES` dictionary in `corpus_backends/protocol` to hold the localized topic section titles for `new_tab_en_us` & `new_tab_de_de`.

EN-US strings: https://searchfox.org/mozilla-central/source/browser/locales/en-US/browser/newtab/newtab.ftl#392
DE-DE strings: https://github.com/mozilla-l10n/firefox-l10n/blob/main/de/browser/browser/newtab/newtab.ftl#L407

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/merino-py/blob/main/CONTRIBUTING.md)
- [x] The PR title starts with the JIRA issue reference, format example `[DISCO-####]`, and has the same title (if applicable)
- [ ] `[load test: (abort|skip|warn)]` keywords are applied to the last commit message (if applicable)
- [ ] [Documentation](https://github.com/mozilla-services/merino-py/tree/main/docs) has been updated (if applicable)
- [ ] [Functional and performance test](https://github.com/mozilla-services/merino-py/blob/main/docs/dev/testing.md) coverage has been expanded and maintained (if applicable)

2024-11-27 22:21 UTC, mmiermans requested changes
Thanks for pulling this together! I've got a few (hopefully small) changes I think we should make.

2024-11-27 22:21 UTC, mmiermans commented on merino/curated_recommendations/corpus_backends/protocol.py
> +
Given that some sections (Popular today, In the News) don't correspond to a topic, would it make sense to move this data to a separate file, for example `merino/curated_recommendations/localization.py`? Or do you think it would be better you keep localized topics separate from section titles not based on topics?

2024-11-27 22:21 UTC, mmiermans commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +            assert data["feeds"]["arts"]["title"] == "Arts"
Could you add a test asserting that we have a translation for every section title? Something like the following. (Untested code.)

```python
@pytest.mark.parametrize("surface_id", [
    ScheduledSurfaceId.NEW_TAB_EN_US,
    ScheduledSurfaceId.NEW_TAB_DE_DE,
])
def test_section_translations(surface_id):
    # Get all fields in CuratedRecommendationsFeed of type Section
    section_fields = [
        field_name
        for field_name, field_type in CuratedRecommendationsFeed.model_fields.items()
        if field_type.annotation is Section
    ]
    
    # Get the localized titles for the current surface_id
    localized_titles = LOCALIZED_TOPIC_SECTION_TITLES[surface_id]
    
    # Assert that each section field has a translation
    for field in section_fields:
        assert field in localized_titles, f"Missing translation for '{field}' in {surface_id}"
```

2024-11-27 22:21 UTC, mmiermans commented on merino/curated_recommendations/provider.py
> +                            formatted_topic, formatted_topic.capitalize()
`replace("_", " ")` was meant to be temporary code to generate a human-readable title from identifiers. I think we should stop doing that as part of this PR, when we have actual strings. The keys of `LOCALIZED_TOPIC_SECTION_TITLES` should be section or topic identifiers without any string formatting.

2024-11-27 22:31 UTC, mmiermans commented on tests/integration/api/v1/curated_recommendations/test_curated_recommendations.py
> +    async def test_curated_recommendations_with_sections_feed_de(self):
I can reproduce the failure locally by repeating the test a couple times:
```suggestion
    @pytest.mark.asyncio
    @pytest.mark.parametrize('repeat', list(range(10)))
    async def test_curated_recommendations_with_sections_feed_de(self, repeat):
```

The order and presence of sections is not deterministic, so you can't make an assumption that they're there. I would evaluate the assertion only if the section is present. You might want cover a few more sections in addition to `arts` to ensure at least one assertion is evaluated.
```python
if data["feeds"]["arts"] is not None:
    assert data["feeds"]["arts"]["title"] == "Unterhaltung"
```

2024-12-02 19:03 UTC, katerinachinnappan commented on merino/curated_recommendations/corpus_backends/protocol.py
> +
I think moving this to a separate file makes more sense especially if we end up using pontoon path we will need separate files anyways

2024-12-02 19:59 UTC, katerinachinnappan commented on merino/curated_recommendations/provider.py
> +                            formatted_topic, formatted_topic.capitalize()
shouldn't we still use `rec.topic.replace("_", " ")` as a default in the case there is no key/value found in the dict? we should cover the case where we fallback to english titles but the key/value is not available in the dict for whatever reason so we should work with `rec.topic`

2024-12-02 22:47 UTC, katerinachinnappan commented on merino/curated_recommendations/corpus_backends/protocol.py
> +}
Amy said she will try getting US and DE tmr (12.02), so will update this PR once that is established.

2024-12-03 00:02 UTC, mmiermans reviewed
I only have one more comment. Besides that, it all looks good to me. 👍

2024-12-03 16:56 UTC, mmiermans commented on merino/curated_recommendations/localization.py
> +LOCALIZED_TOPIC_SECTION_TITLES: LocalizedTopicSectionTitles = {
top-stories is not a topic section, so a better name might be:
```suggestion
LOCALIZED_SECTION_TITLES: LocalizedSectionTitles = {
```
I can also do this when adding the News Section later this week.

2024-12-03 18:29 UTC, katerinachinnappan commented on merino/curated_recommendations/localization.py
> +LOCALIZED_TOPIC_SECTION_TITLES: LocalizedTopicSectionTitles = {
updated this in my PR along with the German string for top-stories

2024-12-03 19:03 UTC, merged