feat: add current conditions to accuweather response
mozilla-services/merino-py pull request #88
Opened 2022-10-22 00:59 UTC by 0c0w3

Closes CONSVC-2049

2022-10-24 17:30 UTC, ncloudioj commented on merino/providers/accuweather.py
> +        match unit:
Using an enum against which the `unit` matches may silence the mypy warning. E.g

```py
from enum import Enum, unique

@unique
class Unit(str, Enum):
    CELCIUS = "C"
    FAHRENHEIT = "F"

try:
    unit = Unit(unit.upper())
except ValueError:
    logger.warning("Unexpected temperature unit")
    return None

match unit:
    case Unit.CELCIUS:
        ...
    case Unit.FAHRENHEIT:
        ...
    # no need to use `case _:` any more

```

2022-10-24 19:12 UTC, ncloudioj commented on merino/providers/accuweather.py
> +    f: Optional[float] = None
Q: not sure how useful it would be, shall we automatically do the conversion and populate the other field if only one of `c` or `f` is provided?

2022-10-24 19:16 UTC, ncloudioj commented on merino/providers/accuweather.py
> +                return Temperature(c=value, f=None)
Nit: since both `f` and `c` use "None" as the default value, `f=None` and `c=None` can be omitted here.

2022-10-24 19:27 UTC, ncloudioj commented on merino/providers/accuweather.py
> +    f: Optional[float] = None
Also noticed down below that in the API response, we provide both `c` and `f` for current conditions, but only one of them for the high & low temperatures for forecasts, which feels a little bit inconsistent to me.

2022-10-24 19:29 UTC, ncloudioj requested changes
Looks good. Just a few comments on temperature handling.

2022-10-25 01:18 UTC, 0c0w3 commented on merino/providers/accuweather.py
> +        match unit:
Unfortunately it didn't -- the problem seems to be that `data` is `Any`. The list structure in the pattern might also be part of the problem because mypy doesn't have a problem with the other pattern in this file that does not include a list, and the pattern in the [linked mypy issue](https://github.com/python/mypy/issues/12770) also uses a list.

So for now I kept this `_parse_forecast_temperature()` implementation the way it is since it seems a little simpler.

2022-10-25 01:24 UTC, 0c0w3 commented on merino/providers/accuweather.py
> +                    "Metric": {
AFAICT yes, the [doc](http://apidev.accuweather.com/developers/currentConditionsAPIParameters#responseParameters) includes both and doesn't say one or the other might be absent, and in my testing both are returned. Do you think it makes sense to be defensive and check? IMO it doesn't because I'm not sure where we would draw the line -- if we're defensive here then we should be defensive everywhere and not trust what their docs say. (That's kind of what I was doing in my original accuweather patch, where I wasn't using pattern matching.)

2022-10-25 01:30 UTC, 0c0w3 commented on merino/providers/accuweather.py
> +    f: Optional[float] = None
Yeah, AccuWeather provides [both for current conditions](http://apidev.accuweather.com/developers/currentConditionsAPIParameters#responseParameters) but [only one for forecasts](http://apidev.accuweather.com/developers/forecastsAPIParameters#dailyforecast). For forecasts, they include a `Unit` property. It's a weird inconsistency.

We may well want to do the conversion ourselves at some point. In my testing the forecasts temperature is in F, I'm guessing since my IP is in the U.S. Of course another option is to do it on the client. Since this feature will roll out in only the U.S. at first, I think we can leave that to later if necessary.

2022-10-25 01:36 UTC, ncloudioj commented on merino/providers/accuweather.py
> +    f: Optional[float] = None
Makes sense. Let's leave it as is for now. The conversion can be done at a later time somewhere if necessary. I'd guess that we will let Firefox users pick whatever unit they prefer to use.

2022-10-25 01:38 UTC, ncloudioj commented on merino/providers/accuweather.py
> +                    "Metric": {
Agreed, no need to be defensive here as long as their API says both will be provided in the response.

2022-10-25 01:40 UTC, 0c0w3 commented on merino/providers/accuweather.py
> +    f: Optional[float] = None
We would probably choose the unit appropriate for the user's current Firefox locale. If it's en-US, then F, and otherwise use C even if the user's region is the U.S. I guess that's something we could do even for the initial rollout since we'll likely target all en-* locales in the U.S. region like we've done before. So I'm definitely open to doing the conversion ourselves right now -- I just don't think it's a high priority ATM.

2022-10-25 01:42 UTC, ncloudioj commented on merino/providers/accuweather.py
> +        match unit:
Hmm, I am seeing `data` here, did I miss anything?

Anyhow, mypy could be confused in certain cases. I think your current implementation is fine, let's keep it as is then.

2022-10-25 01:43 UTC, ncloudioj approved these changes
Looks good. Thanks!

2022-10-25 01:45 UTC, 0c0w3 commented on merino/providers/accuweather.py
> +        match unit:
The mypy warning happens [on this line](https://github.com/mozilla-services/merino-py/pull/88/files#diff-4d942cadca923e41129b9530a95b09919c151aa1b3632127d0104de197c2d281R227) in `_parse_forecast()`, which has the `data` param. It doesn't seem to be related to parsing the unit.

2022-10-25 02:07 UTC, merged