WIP CONSVC-2008/feat-add nav query top pick provider
mozilla-services/merino-py pull request #89
Opened 2022-10-25 20:48 UTC by taddes

2022-10-26 02:30 UTC, ncloudioj commented on dev/top_picks.json
> +    "domains": {
Per the schema defined in [DENG-406](https://mozilla-hub.atlassian.net/browse/DENG-406), it should look like this:

```json
{
  "domains": [
    {
      "rank": 1,
      "title": "Mozilla",
      "domain": "mozilla",
      "url": "https://www.mozilla.org/",
      "icon": "chrome://devtools/skin/images/globe.svg",
      "categories": ["web-browser"],
      "similars": [
        "mozzilla",
        "mozila"
      ]
    }
  ]
}
```

N.B.:
* I was using the TLD (Top-Level Domain) for `domain` as we will get any queries from Firefox that contains `.`
* I was using the internal globe SVG icon in Firefox as an example

2022-10-26 02:31 UTC, ncloudioj commented on merino/configs/default.toml
> +top_pick_file_path = "merino/providers/top_picks.json"
```suggestion
top_pick_file_path = "./dev/top_picks.json"
```

2022-10-26 02:33 UTC, ncloudioj commented on merino/configs/default.toml
> +is_top_pick = true
Why having this boolean here? Do we have any case in which suggestions of this provider will not be served as Top Picks?

2022-10-26 02:36 UTC, ncloudioj commented on merino/configs/default.toml
> +[default.providers.top_pick]
To be consistent, let's use "Top Picks" in Merino.
 
```suggestion
[default.providers.top_picks]
```

2022-10-26 02:36 UTC, ncloudioj commented on merino/providers/__init__.py
> +    TOP_PICK = "top_pick"
```suggestion
    TOP_PICKS = "top_picks"
```

2022-10-26 02:41 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    icon: Optional[HttpUrl] = None
We might need to use an internal icon URI (e.g. "chrome://devtools/skin/images/globe.svg"), which won't be a valid `HttpUrl`. So let's do `icon: str` for now. Also this field should be required per the schema.

2022-10-26 02:42 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    impression_url: HttpUrl
Both `impression_url` and `click_url` are not needed for this provider, let's drop them.

2022-10-26 02:45 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    icon: Optional[HttpUrl] = None
In fact, `BaseSuggestion` already defines the following fields:
```py
    title: str
    url: HttpUrl
    provider: str
    is_sponsored: bool
    score: float
    icon: str | None = None
```
No need to redefine those here.

2022-10-26 02:45 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    full_keyword: str
We don't need `full_keyword` for this provider either.

2022-10-26 02:47 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    icons: dict[int, str] = {}
Icons are already stored in the suggestions, no need to store them separately here.

2022-10-26 02:48 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    domain_list: dict[str, Any] = {}
I don't think we need to store this list once the indices are built. Let's drop it.

2022-10-26 02:51 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    last_fetch_at: float
I believe we only load this domain list once at application startup, until we move this file to remote, we don't need this field.

2022-10-26 02:54 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            return e
Perhaps you want to re-throw the exception here instead of returning it?

2022-10-26 02:56 UTC, ncloudioj commented on merino/providers/top_pick.py
> +        domains: list[dict[str, Any]] = domain_list["domains"]["items"]
As mentioned above, `domain_list["domains"]` should be a list, there is no such property `items` in it.

2022-10-26 03:04 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            for chars in range(QUERY_CHAR_LIMIT, len(domain) + 1):
Be mindful of the case when `len(domain) < QUERY_CHAR_LIMIT`, this will insert no keys into the index while appending the `domain` onto `results`, which would leave this domain unused. I think in that case, we can just skip this domain as a whole.

2022-10-26 03:50 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            results.append(domain)
I'd recommend building both the primary index and the second index within a single loop here, e.g.

```py
    for record in domains_list["domains"]:
        index_key = len(results)
        suggestion = { ... }  # create the suggestion based on `record`
        
        # insert keys into the primary index
        domain = record["domain"]
        for chars in range(QUERY_CHAR_LIMIT, len(domain)):
             primary_index[domain[:chars]].append(index_key)

        # insert keys into the secondary index
        for variant in record.get("similars", []):
             for chars in range(QUERY_CHAR_LIMIT, len(variant)):
                  secondary_index[variant[:chars]].append(index_key)

        results.append(suggestion)

    return {
         "primary_index": primary_index,
         "second_index": secondary_index,
         "results": results
    }
```

2022-10-26 03:52 UTC, ncloudioj commented on merino/providers/top_pick.py
> +    def build_indices() -> Any:
To make this more cohesive and testable, we can move all those static methods into a separate utility module.

2022-10-26 03:55 UTC, ncloudioj commented on merino/providers/top_pick_schema.json
> +            "items": [
FWIW, `items` are not the field of this array but only a term used by the JSON schema to describe the "items" of this array.

2022-10-26 16:08 UTC, ncloudioj commented on merino/providers/top_pick.py
> +class TopPickCategory(str, Enum):
Looks like this never gets used anywhere, let's drop it for now.

2022-10-26 16:09 UTC, ncloudioj commented on merino/providers/top_pick.py
> +                "block_id": res.get("rank"),
Let's use `0` as the dummy value for `block_id`.

2022-10-26 16:15 UTC, taddes commented on merino/providers/top_pick.py
> +class TopPickCategory(str, Enum):
I'm actually planning on using that as a payload response in the suggestion. I thought it wise for telemetry purposes if the suggestion was flagged as primary or secondary, hence the enum. I hadn't yet implemented it in the code as I wanted to recommend it in our discussion.

2022-10-26 16:15 UTC, taddes commented on merino/providers/top_pick.py
> +                "block_id": res.get("rank"),
Sounds good!

2022-10-26 16:22 UTC, ncloudioj commented on merino/providers/top_pick.py
> +        if (id := self.primary_index.get(q)) is not None:
`self.primary_index.get(q)` will return a list, rather than a single index. So you'd do (assuming that we only return the first one (i.e. the highest ranked one)):
```py
    if (ids := self.primary_index.get(q, [])):
        res = self.primary_results[ids[0]]
```
The same applies to secondary_index.

2022-10-26 16:23 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            Suggestion(**suggestion_dict)
```suggestion
            return [Suggestion(**suggestion_dict)]
```

2022-10-26 16:24 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            res = self.secondary_results[id]
```suggestion
            res = self.secondary_results[id]
            return Suggestion(..)
```

2022-10-26 16:24 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            res = None
```suggestion
            return []
```

2022-10-26 16:49 UTC, taddes commented on dev/top_picks.json
> +    "domains": {
Got it, updating that now

2022-10-26 19:37 UTC, taddes commented on merino/providers/top_pick.py
> +class TopPickCategory(str, Enum):
Dropped!

2022-10-26 19:39 UTC, taddes commented on merino/providers/top_pick_schema.json
> +            "items": [
🤦‍♂️ yup, my bad. Never took that out when making test files from schema. Duh

2022-10-27 00:17 UTC, ncloudioj commented on merino/providers/top_pick.py
> +            primary, secondary = await asyncio.to_thread(Provider.build_indices())
```suggestion
            primary, secondary = await asyncio.to_thread(Provider.build_indices)
```

2022-10-27 00:58 UTC, taddes commented on merino/providers/top_pick.py
> +            primary, secondary = await asyncio.to_thread(Provider.build_indices())
Thank you for that. Classic mistake instead of passing ref.

2022-10-27 01:55 UTC, taddes commented on merino/providers/top_pick.py
> +    def build_indices() -> Any:
Will do, great idea. I can make the changes, or we can merge this in after the PR is reviewed and I can then extract them out to a utility module.

2022-10-27 02:24 UTC, taddes commented on merino/providers/top_pick.py
> +                "block_id": res.get("rank"),
Just need to ask you about icon again tomorrow, was passing an empty string and saw in another provider a Final was set with the value of -1, so wondering if we should do that until we have something, though I see we set the icon values to be typed as str.

2022-10-27 13:59 UTC, ncloudioj commented on dev/top_picks.json
> +            "icon": -1,
Per schema, I believe that `icon` is of type `string`

2022-10-27 14:04 UTC, ncloudioj commented on merino/configs/default.toml
> +score = 0.2
Firefox also assigns 0.2 to Remote Settings suggestions (see [here](https://searchfox.org/mozilla-central/source/browser/components/urlbar/UrlbarQuickSuggest.sys.mjs#62)). Let's use a higher score for this provider. 0.25 should be fine.

2022-10-27 14:04 UTC, ncloudioj commented on merino/configs/testing.toml
> +score = 0.2
Ditto.

2022-10-27 14:16 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            self.query_char_count_dict = index_results_dict["char_count_dict"]
Let's make `char_count_dict` a tuple `(min_char_count, max_char_count)` and rename it to `index_char_range`.

2022-10-27 14:18 UTC, ncloudioj commented on merino/providers/top_picks.py
> +        primary_index: defaultdict = defaultdict(list)
Could you add some docs to briefly describe the structure of those instance variables. You can reference [here](https://github.com/mozilla-services/merino-py/blob/main/merino/providers/adm.py#L161-L165)

2022-10-27 14:21 UTC, ncloudioj commented on merino/providers/top_picks.py
> +        if len(q) < self.query_char_count_dict["min"]:
```suggestion
        if not (self.query_char_count_dict["min"] <= len(q) <= self.query_char_count_dict["max"]):
```

2022-10-27 14:22 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            logger.warning(res)
```suggestion
```

2022-10-27 14:26 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            suggestion = {
Instead of creating a dict here, we can directly create a `Suggestion` object here, such as
```py
suggestion = Suggestion(
    block_id=0,
    title= record["title"],
    ...
)
```

So in the `query()`, it doesn't need to create a Suggestion object over and over again.

2022-10-27 14:28 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    rank: int
Both `domain` and `rank` are irrelevant to the API consumers, no need to be included in the response.

2022-10-27 14:30 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    score: float
Both `score` and `is_sponsored` are already defined in `BaseSuggestion`, no need to redefine them again here.

2022-10-27 14:33 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            if len(record["domain"]) < QUERY_CHAR_LIMIT:
I don't think we need this check here, as it also needs to check all the entries in `similars`.

2022-10-27 14:36 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            for chars in range(QUERY_CHAR_LIMIT, len(record["domain"]) + 1):
Nit: let's define a variable `domain = record["doamin"]` instead of repeating it multiple tiles in this block.

2022-10-27 14:37 UTC, ncloudioj commented on merino/providers/top_picks.py
> +                    min_max_chars["max"] = chars
You will also need to track the minimal index length. It's possible that it's greater than `QUERY_CHAR_LIMIT`.

2022-10-27 14:38 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            # Insertion of keys into primary index.
```suggestion
            # Insertion of keys into seconary index.
```

2022-10-27 14:44 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +        "items": [
Drop `items`.

2022-10-27 14:46 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +    assert type(domain_list) == dict
The next assert already verifies it's a `dict`.
```suggestion
```

2022-10-27 14:47 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +        "items": [
Hmm, how come this didn't break the tests? 🤔

2022-10-27 14:54 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +    with pytest.raises(FileNotFoundError):
Nice, looks like you already have this covered. Could you split this into two unit tests since the former tests the failure case and the latter checks the happy one?

2022-10-27 14:56 UTC, quiiver approved these changes
This looks good, I have 1 minor comment in the code. 

Generally I'm curious about the naming/structure of the provider. `TopPick` is a UX feature on the client which could have many sources of data, we're just starting with domains. How would we evolve this provider to account for more `TopPick` data sources? In my mind there's two options when we get to that:

1. We take a per-source provider approach and move this provider to a more specific name like `domains_top_pick` and the second source would follow the same convention of `<source>_top_pick`. This would be easy to split experiment traffic across providers by using the `providers` query param but is probably the less DRY of the solutions.
2. We keep a single provider for the `top_pick` feature and encapsulate the indexes into their own modules. This is probably the most DRY of the solutions but leaves the question about how you bring up new sources.

Anyway, some food for thought. I don't think any immediate changes are necessary in this regard just wanted to plant the seed.

2022-10-27 14:56 UTC, quiiver commented on merino/providers/top_picks.py
> +        super().__init__(**kwargs)
I don't think we need this line since there's no `__init__` defined on BaseProvider

2022-10-27 14:57 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +    assert "exa" not in source_dict["primary_index"]
this would break if we update `QUERY_CHAR_LIMIT` in the future. You can do `example[:max(QUERY_CHAR_LIMIT - 1, 0)] not in source_dict...`

2022-10-27 14:58 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +    source_dict["primary_index"]
Did you forget to assert?

2022-10-27 15:02 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +    assert type(top_picks.primary_index) == defaultdict
Those assertions won't verify anything as you expected as those are all instance variables, their types won't change even if you call `initialize()` here. Perhaps you need to check what's inside them.

2022-10-27 15:06 UTC, ncloudioj commented on tests/unit/providers/test_top_picks.py
> +        top_picks.initialize(0)
Hmm, I don't think this is the best way to simulate an exception inside `initialize()`, as we won't call it with this argument and w/o `await` for it. I think as you've already had some test cases to check exceptions raised in those helper functions, we don't need to do that again here at the provider level.

2022-10-27 15:23 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            return Suggestion(**res)
```suggestion
            return [Suggestion(**res)]
```

2022-10-27 15:23 UTC, taddes commented on dev/top_picks.json
> +            "icon": -1,
Of course @ncloudioj . This came from looking at how the other providers handled icons not being present, so I implemented it the same way. I know the schema dictated strings. Can you comment on how we handle icons not being present? For the time being, I know we don't have that part sorted out so I was trying to stay ahead of it. Thanks!

2022-10-27 15:24 UTC, taddes commented on merino/configs/default.toml
> +score = 0.2
You got it!

2022-10-27 15:25 UTC, taddes commented on merino/configs/testing.toml
> +score = 0.2
Got it!

2022-10-27 15:25 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            return Suggestion(**res)
I was surprised that this didn't cause any test failures. Can you add some tests to actually send some queries to this privider? Like what we have in [test_api_v1.py](https://github.com/mozilla-services/merino-py/blob/main/tests/unit/web/test_api_v1.py)

2022-10-27 15:30 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    def read_domain_list(file: str) -> Any:
Could you replace all the `Any` types in this module with their actual types? I think the function input and ouputs are pretty well-defined, shouldn't be too hard to fill them out. Thanks!

2022-10-27 15:31 UTC, ncloudioj requested changes
I think it's now in good shape, we're getting closer. Just a few more review comments.

2022-10-27 16:08 UTC, taddes commented on merino/providers/top_picks.py
> +            logger.warning(res)
Debug! Removed.

2022-10-27 16:14 UTC, taddes commented on merino/providers/top_picks.py
> +            suggestion = {
Good point!

2022-10-27 16:19 UTC, taddes commented on tests/unit/providers/test_top_picks.py
> +        "items": [
I had altered the test that originally used this, I had a note of this as I have a few more tests to write.

2022-10-27 17:28 UTC, taddes commented on merino/providers/top_picks.py
> +            self.query_char_count_dict = index_results_dict["char_count_dict"]
My only concern with this is that as we iterate through the collection of domains when building indexes, we update the values for these min and max values, so I can assign to separate int variables for min and max and then pass them into a tuple at the end, but it results in three declarations opposed to one, which is why I opted for a dictionary for the start, which requires fewer vars. It is very explicit, since they key describes what the value is, opposed to accessing the index of a tuple which in a check may be confusing. Happy to still make it a tuple, just wanted to provide my rationale. I implemented the previous indices as tuples in the last review and it was opted they change to a dict for clarity, so I was trying to follow that pattern.

2022-10-27 17:53 UTC, taddes commented on merino/providers/top_picks.py
> +    def read_domain_list(file: str) -> Any:
You bet, I mentioned I'd be doing that in the Jira ticket. It became onerous with all the updates to manage pertaining to some of the type hints, appease the linter and commit. All the type annotations will now be updated.

2022-10-27 18:42 UTC, taddes commented on merino/providers/top_picks.py
> +            return Suggestion(**res)
I actually do have the `test_query` function and it was successful, as I'd check the first position of the index to test that the suggestion data was the same. I changed the return type from this to just `res`, so a constructed `Suggestion` as you recommended, so that a new obj doesn't have to be made every time query is called. Should be good!

2022-10-27 18:51 UTC, taddes commented on merino/providers/top_picks.py
> +        super().__init__(**kwargs)
That's a very good point @quiiver  and indeed worth keeping in mind. I suppose we can definitely take either approach, though for where we are at option 2 seems most sensible for where we are at, so long as you feel confident it provides the adequate extensibility desired for future provider sources and data.

2022-10-27 19:11 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            self.query_char_count_dict = index_results_dict["char_count_dict"]
I think that's fine. We can have any number of declarations as long as they make sense. For better readability, you can also do `min_len, max_len = index_char_range` before using it, or you can just use two instance variables to store them. Using a dict in this case just feels a bit odd to me.

2022-10-27 19:19 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    async def query(self, q: str) -> Any:
Let's stick to the abstract method defined in providesr/base.py.
```suggestion
    async def query(self, srequest: SuggestionRequest) -> list[BaseSuggestion]:
:
```

2022-10-27 19:20 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    def read_domain_list(file: str) -> dict[str, Union[str, int, list[str]]]:
```suggestion
    def read_domain_list(file: str) -> dict[str,Any]:
```

2022-10-27 19:21 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    def build_index(domain_list: dict) -> dict[str, Union[list, dict]]:
```suggestion
    def build_index(domain_list: dict[str, Any]) -> dict[str, Any]:
```

2022-10-27 19:21 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    def build_indices() -> dict[str, Union[list, dict]]:
```suggestion
    def build_indices() -> dict[str, Any]:
```

2022-10-27 19:41 UTC, taddes commented on tests/unit/providers/test_top_picks.py
> +    with pytest.raises(FileNotFoundError):
Good call!

2022-10-27 19:48 UTC, taddes commented on merino/providers/top_picks.py
> +                    min_max_chars["max"] = chars
Because of how the logic is structured with the following check:
`            if len(record["domain"]) < QUERY_CHAR_LIMIT:
                continue
`
a record under that char limit as set in the config will not be appended, hence the minimum value will match the minimum value set in config. This way we don't deal with the logic here making that determination based on what domain lists we get. Thoughts? That's why I kept it this way, so 2 checks aren't necessary

2022-10-27 19:55 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    async def query(self, srequest: str) -> list[BaseSuggestion]:
The abstract method is defined [here](https://github.com/mozilla-services/merino-py/blob/main/merino/providers/base.py#L45). It's implemented by all other providers.

2022-10-28 00:36 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    score: float
Forgot dropping `score`? Also, no need to redefine `is_sponsored` here, you can set it to `False` later upon the object instantiation.

2022-10-28 00:36 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    results: list[dict[str, Union[str, list, int]]]
```suggestion
    results: list[dict[str, Any]
```

2022-10-28 00:38 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            return []
Don't forget to add the length range check here.

2022-10-28 00:39 UTC, ncloudioj commented on merino/providers/top_picks.py
> +                provider="top_picks",
```suggestion
                provider=self.name,
```

2022-10-28 00:40 UTC, ncloudioj commented on merino/providers/top_picks.py
> +                icon="",
```suggestion
                icon=record["icon"],
```

2022-10-28 00:40 UTC, ncloudioj commented on merino/providers/top_picks.py
> +                score=settings.providers.top_picks.score,
```suggestion
                score=SCORE,
```

2022-10-28 00:42 UTC, ncloudioj commented on tests/unit/web/test_top_picks.py
> +            "wiki_fruit": TopPicksProvider(name="top_picks", enabled_by_default=True),
```suggestion
            "top_picks": TopPicksProvider(name="top_picks", enabled_by_default=True),
```

2022-10-28 16:18 UTC, taddes commented on merino/providers/top_picks.py
> +            return []
Yep, took  original out when I was refactoring

2022-10-28 16:21 UTC, taddes commented on merino/providers/top_picks.py
> +                provider="top_picks",
This won't work was the `build_index` method is `@staticmethod`, so it doesn't have access to the instance, same issue with using `Provider` as the class isn't instantiated. Can I leave it as a str or do we do something else? I can set it as a setting in the `toml` file.

2022-10-28 16:28 UTC, taddes commented on merino/providers/top_picks.py
> +    score: float
Thanks @ncloudioj . So in each individual suggestion that is appended to the list in the `build_index` method, I set `is_sponsored` to `False`. That work?

2022-10-28 16:57 UTC, taddes commented on merino/providers/top_picks.py
> +            return []
Hm, so again with the min range, perhaps I'm just missing something, but if we have the query limit set to say 4, it will always iterate through a domain string when building the index, meaning it will always, at minimum, be 4 characters.

Originally, when I had the check whether to index the suggestion or not, my thought was that if for some reason, a domain (and also its similars) could in a rare case be lower, causing an index error when iterating through the string. So, that's why I didn't add it. Edge case, but do you think for that reason alone I should add it back? It would be a silly reason for the indexing operation to fail.

As far as querying is concerned, the max is easy, based on the longest domain string in the collection of indexes. However, for the min, if the spec of the provider is to, at minimum, trigger a lookup at 4 characters, is it really worthwhile updating the min? Doesn't that essentially bypass the trigger limit of 4.   Perhaps I'm just confused on this point. We certainly won't update min any lower, but in terms of updating it higher, doesn't the char limit also set that no matter what, a query will at least yield a result so long as it hits the character limit, and if we are indexing using that same limitation, won't those values be the same? Thanks for discussing this.

2022-10-28 17:04 UTC, taddes commented
@ncloudioj Ready for review, though I know we need to add the new `base.py` changes @pjenvey landed and then I need to update the code to implement `SuggestionRequest`, so once final reviews are done (I responded in a few comments), I can rebase onto master. Thoughts? Thanks again!

2022-10-28 17:57 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    score: float
Exactly. Also, can you remove `score` as well, it's already defined in the base class, no need to repeat that again here.

2022-10-28 17:58 UTC, ncloudioj commented on merino/providers/top_picks.py
> +    index_char_range = dict[str, int]
Let's not waste two dict lookups for each query call for this. Please use two variables instead `index_char_min` and `index_char_max`.

2022-10-28 18:04 UTC, ncloudioj commented on merino/providers/top_picks.py
> +            return []
You're right. I was wrong about the minimum, sorry about that. Let's just track maximum then.

2022-10-28 18:08 UTC, ncloudioj approved these changes
Looks good. r+ with comments.

Thanks!

2022-10-28 18:43 UTC, taddes commented on merino/providers/top_picks.py
> +    index_char_range = dict[str, int]
You got it, artifact from removing the original test and dict lookup. Thx

2022-10-28 18:43 UTC, taddes commented on merino/providers/top_picks.py
> +    index_char_range = dict[str, int]
Union above was removed in another commit, fyi. Must have not hit when commented on.

2022-10-28 18:44 UTC, taddes commented on merino/providers/top_picks.py
> +                provider="top_picks",
👍

2022-10-28 18:44 UTC, taddes commented on merino/providers/top_picks.py
> +    score: float
Thx. I took score out in a subsequent commit, so by the time you commented I had removed. Thx for confirming.

2022-10-28 18:55 UTC, taddes commented on merino/providers/top_picks.py
> +            return []
Ok, thx!

2022-10-28 21:07 UTC, taddes commented on merino/providers/top_picks.py
> +        if srequest.startswith("http"):
Always a good  to add some context

2022-10-28 21:09 UTC, taddes commented on merino/providers/top_picks.py
> +    block_id: int
Yeah, it'll have a purpose later which is why we're keeping it, but I am not 100% sure.

2022-10-28 22:29 UTC, pjenvey requested changes

2022-10-28 22:29 UTC, pjenvey commented on merino/providers/top_picks.py
> +    results: list[dict[str, Any]]
Noticed a few type mismatches as well, I'm surprised mypy didn't catch any of them?

```suggestion
    results: list[Suggestion]
```

2022-10-28 22:29 UTC, pjenvey commented on merino/providers/top_picks.py
> +            self.secondary_index: list = index_results_dict["secondary_index"]
```suggestion
            self.primary_index: defaultdict = index_results_dict["primary_index"]
            self.secondary_index: defaultdict = index_results_dict["secondary_index"]
```

2022-10-29 16:13 UTC, taddes commented on merino/providers/top_picks.py
> +        elif ids := self.secondary_index.get(srequest, []):
Good point, walrus operator would be falsy either way.

2022-10-29 16:14 UTC, taddes commented
Thanks for the comments @pjenvey ! If you're ok with approving this now or adding another review so I can merge, that'd be great, merging currently blocked due to requested changes.

2022-10-29 22:30 UTC, pjenvey approved these changes

2022-10-30 13:45 UTC, merged