feat: add full keyword to merino response
mozilla-services/merino-py pull request #90
Opened 2022-10-26 04:27 UTC by tiftran

closes [CONSVC-2070](https://mozilla-hub.atlassian.net/browse/CONSVC-2070)

2022-10-26 20:25 UTC, ncloudioj commented on merino/providers/adm.py
> +                full_keywords = suggestion.pop("full_keywords")
Just a note that since Remote Settings records currently do not have this `full_keywords` field, this PR cannot be merged until we upload the new records to RS.

2022-10-26 20:26 UTC, ncloudioj commented on merino/providers/adm.py
> +                kw_id = len(results)
Does `kw_id` stands for "keyword id"? I think `result_id` or just `id` is more accurate.

2022-10-26 20:31 UTC, ncloudioj commented on merino/providers/adm.py
> +                        begin += n
Incrementing `begin` within the inner loop would be catastrophic 😁 

```suggestion
                    begin += n
```

2022-10-26 20:32 UTC, tiftran commented on merino/providers/adm.py
> +                        begin += n
eek

2022-10-26 20:33 UTC, quiiver commented on merino/providers/adm.py
> +                full_keywords = suggestion.pop("full_keywords")
This is the kind of scenario where feature flags can be useful:

* have a downstream dependency
* branch in code with feature flags to account for downstream dependency
* merge the branched code with confidence that you won't currently break anything and you can move on
  * this is generally good because you don't want PRs sitting around and bit rotting
* downstream dep gets resolved
* push a config change to flip the new path on (either for a % or 100%)
* validate that it works as expected
* remove branch in code and clean up flag

2022-10-26 20:34 UTC, tiftran commented on merino/providers/adm.py
> +                full_keywords = suggestion.pop("full_keywords")
yup understood!

2022-10-26 20:34 UTC, quiiver commented on merino/providers/adm.py
> +                full_keywords = suggestion.pop("full_keywords")
(i'm not saying we have to use feature flags here, just calling out that this is a good use case for them)

2022-10-26 20:35 UTC, tiftran commented on merino/providers/adm.py
> +                kw_id = len(results)
i think `id` is reserved in python, was trying to not use it, result_id makes more sense you're right

2022-10-26 20:38 UTC, ncloudioj commented on merino/providers/adm.py
> +                        begin += n
Hmm, did this break anything in the contract tests? If not, I think we should add some tests to cover it.

2022-10-26 20:39 UTC, ncloudioj commented on tests/contract/volumes/kinto/data-02.json
> +           [ "coffee",1],
```suggestion
           ["coffee",1],
```

2022-10-26 21:02 UTC, ncloudioj commented on merino/providers/adm.py
> +    suggestions: dict[str, Tuple[int, str]] = {}
Throwing this idea for discussion: alternatively, we can keep all the full keywords in a separate list (like what we do for suggestions with `results`), then we don't need to save a copy for each query, rather we just need an index that points to an element of the full keyword list (i.e. `Tuple[int, str] -> Tuple[int, int]`). Doing so could save some memory for Merino as most full keywords are pretty long.

2022-10-26 21:19 UTC, tiftran commented on merino/providers/adm.py
> +                        begin += n
had the same thinking

2022-10-27 05:01 UTC, tiftran commented on merino/providers/adm.py
> +                        begin += n
tests didn't pick up on this since all the tuples had values of 1, so the loop only go through once, changed contract test data for [this](https://github.com/mozilla-services/merino-py/pull/90/files#diff-39fd904b576c25a9c97637fd95124f3dab01b928e759b621930a33fde9d711d0R104-R107)

2022-10-27 10:34 UTC, hackebrot commented on merino/providers/adm.py
> +                full_keywords = suggestion.pop("full_keywords")
I second this! Would be great to use this as an opportunity for all of us to test out feature flags in Merino. 🚀 

(FWIW my PR for integrating feature flags in metrics will be up later today)

2022-10-27 14:54 UTC, Trinaa commented on merino/providers/adm.py
> +                        begin += n
This kind of logical coverage should be done in unit tests ideally. Could some be added?

2022-10-27 15:38 UTC, ncloudioj commented on merino/providers/adm.py
> +                        begin += n
Yes, I think we can add some unit tests to `tests/unit/providers/test_adm.py` with some changes to the `FakeBackend` defined in there.

2022-10-27 18:14 UTC, ncloudioj commented on merino/providers/adm.py
> +                full_keywords_list.append(full_keywords_tuples[0][0])
Hmm, why insert the first full_keyword to the list over here? I think we can just do everything inside the loop below.

```py
fkw_index = 0
for full_keyword, n in full_keywords_tuples:
    for query, fkw in zip(...):
        suggestion[query] = (result_id, fkw_index)
    begin += n
    full_keywords_list.append(full_keyword)
    fkw_index += 1
results.append(suggestion)
```

2022-10-28 04:46 UTC, tiftran commented on merino/providers/adm.py
> +                        begin += n
okie doke, made some changes to `test_adm.py` for more realistic scenarios

2022-10-31 14:21 UTC, ncloudioj commented on merino/providers/adm.py
> +        full_keywords_list: list[str] = []
Nit: to be consistent with other variables, let's drop the suffix `list`.
```suggestion
        full_keywords: list[str] = []
```

2022-10-31 14:23 UTC, ncloudioj commented on merino/providers/adm.py
> +                keywords = suggestion.pop("keywords")
```suggestion
                keywords = suggestion.pop("keywords", [])
```

2022-10-31 14:23 UTC, ncloudioj commented on merino/providers/adm.py
> +                full_keywords_tuples = suggestion.pop("full_keywords")
```suggestion
                full_keywords_tuples = suggestion.pop("full_keywords", [])
```

2022-10-31 14:30 UTC, ncloudioj commented on merino/providers/adm.py
> +            fkw_id = suggest_look_ups[1]
Nit: result_id, fkw_id = suggest_look_ups

2022-10-31 14:34 UTC, ncloudioj approved these changes
LGTM, r+ with comments.

The changes in quicksuggest-rs are ready to land as well, so we don't need to wrap this inside a featureflag, let's get that landed first, and then merge this one.

2022-11-02 05:34 UTC, pjenvey requested changes

2022-11-02 05:34 UTC, pjenvey commented on merino/providers/adm.py
> +                    ):
`fkw` isn't used so I don't think the `zip` necessary? also `keywords` should always be a list so do we need `islice`?
```suggestion
                    for query in keywords[begin : begin + n]:
```

2022-11-02 23:39 UTC, pjenvey approved these changes

2022-11-03 00:02 UTC, merged