[CONSVC-1970] test: fix remote_settings__refresh failure
mozilla-services/merino-py pull request #91
Opened 2022-10-26 18:19 UTC by Trinaa

## Description
* fix for flake issue in `remote_settings__refresh`
* suspect that the issue was caused by using different record IDs when posting attachments
* verified for flake by executing tests 100x consecutively on local and [CI](https://app.circleci.com/pipelines/github/mozilla-services/merino-py/377/workflows/19cdaad0-1251-436d-a23a-2c08cde488a7/jobs/1209) without error

## Issue(s)
[CONSVC-1970](https://mozilla-hub.atlassian.net/browse/CONSVC-1970)

2022-10-26 19:33 UTC, pjenvey approved these changes

2022-10-26 20:08 UTC, ncloudioj approved these changes
Nice detective work 🕵️‍♀️

2022-10-27 07:33 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

Awesome work!

For the sake of consistency and ergonomics, I recommend updating fixture and variable names to match the types that they return and hold: `record -> attachment`.

2022-10-27 07:33 UTC, hackebrot commented on tests/contract/client/tests/test_merino.py
> +        record: KintoRequestAttachment = kinto_records[step.request.filename]
```suggestion
        attachment: KintoRequestAttachment = kinto_attachments[step.request.filename]
```

2022-10-27 07:33 UTC, hackebrot commented on tests/contract/client/tests/conftest.py
> +def fixture_kinto_records(request: Any) -> dict[str, KintoRequestAttachment]:
```suggestion
def fixture_kinto_attachments(request: Any) -> dict[str, KintoRequestAttachment]:
```

2022-10-27 07:33 UTC, hackebrot commented on tests/contract/client/tests/conftest.py
> +        kinto_records[data_file.name] = KintoRequestAttachment(
See above

2022-10-27 07:33 UTC, hackebrot commented on tests/contract/client/tests/kinto.py
> +    record: KintoRequestAttachment,
```suggestion
    attachment: KintoRequestAttachment,
```

2022-10-27 14:36 UTC, Trinaa commented
Hi @hackebrot 👋🏻,

I agree the `attachment` makes more sense than `record`. Code should be ready for another look!

2022-10-28 14:35 UTC, hackebrot approved these changes
LGTM! 🥳

2022-10-28 14:46 UTC, merged