Test/integration layer consvc 2059
mozilla-services/merino-py pull request #98
Opened 2022-11-01 15:29 UTC by Trinaa

## Description
* Create tests/integration directory
* Move tests\unit\web tests to test\integration and organize modules according to API path
* Refactor unit and integration utilities and globals into conftest modules
* Update Make commands to better leverage test metric reporting and insights
* Include integration tests in mypy scope
* Update CI to execute unit and integration tests as individual parallel steps
* Update documentation to include integration tests and their role in the merino-py test strategy

## Issue(s)
[CONSVC-2059](https://mozilla-hub.atlassian.net/browse/CONSVC-2059)

2022-11-02 15:13 UTC, hackebrot requested changes
Hi @Trinaa! 👋🏻 

I'm seeing many great improvements here. Great job! 🚀 

I've added more comments inline.

2022-11-02 15:13 UTC, hackebrot commented on tests/integration/api/v1/suggest/test_metrics.py
> +    setup_providers(providers)
We could use `indirect` here to inject the dict of providers to the `inject_providers` fixture.

I wrote about this some time ago, but I expect this to still work: https://raphael.codes/blog/pytest-parametrize-with-indirect/

The benefit of doing this is separation of test set up from the test item itself.

2022-11-02 15:13 UTC, hackebrot commented on tests/integration/api/v1/suggest/test_suggest.py
> +    setup_providers(providers)
See `indirect` comment above.

2022-11-02 15:13 UTC, hackebrot commented on tests/unit/conftest.py
> +def fixture_suggestion_request() -> SuggestionRequestFixture:
The name of the function `fixture_suggestion_request` does not really matter to pytest if you specify `name`, but for the sake of consistency I suggest renaming this to `fixture_srequest`.

2022-11-02 16:47 UTC, Trinaa commented on tests/contract/client/README.md
> +      pytest tests/contract/client/tests/test_merino.py -vv -k remote_settings__refresh
yeah ... 🤦🏻‍♀️

2022-11-02 17:11 UTC, Trinaa commented on docs/dev/testing.md
> +directory, using the same organizational structure as the merino source code.
Change applied [6df5a74](https://github.com/mozilla-services/merino-py/pull/98/commits/6df5a742c4ea4d99507eee4c99fd33bada021d67)

2022-11-02 17:11 UTC, Trinaa commented on docs/dev/testing.md
> +the FAST API TestClient to send requests to specific merino endpoints and verify
Change applied [6df5a74](https://github.com/mozilla-services/merino-py/pull/98/commits/6df5a742c4ea4d99507eee4c99fd33bada021d67)

2022-11-02 17:53 UTC, Trinaa commented on tests/conftest.py
> +def fixture_filter_caplog() -> FilterCaplogFixture:
They do pass with `make lint`; however, the _pydocstyle_ is not configured to verify the test directories.

I've addressed the one-line doc strings in this PR. Change applied [c312086](https://github.com/mozilla-services/merino-py/pull/98/commits/c3120866c8796de4082dec51f2bd938fdcb3b447)

I opened a task [CONSVC-2086](https://mozilla-hub.atlassian.net/browse/CONSVC-2086) to include test directories in _pydocstyle_ linting.

2022-11-02 17:54 UTC, Trinaa commented on tests/integration/api/test_heartbeat.py
> +    Test that the heartbeat endpoint is supported to conform to dockerflow
Change applied [c312086](https://github.com/mozilla-services/merino-py/pull/98/commits/c3120866c8796de4082dec51f2bd938fdcb3b447).

See comment for [follow-up](https://github.com/mozilla-services/merino-py/pull/98#discussion_r1012118324).

2022-11-02 18:07 UTC, Trinaa commented on tests/integration/api/conftest.py
> +@pytest.fixture(name="client")
Change applied [02aa07a](https://github.com/mozilla-services/merino-py/pull/98/commits/02aa07aa7c8ad9b9712b65b8b86e77ee5d36f2d6).

Is there a use case for `client_with_events`? (I'm thinking YAGNI, because in this PR it's unused)

2022-11-02 18:15 UTC, Trinaa commented on tests/integration/api/test_heartbeat.py
> +    assert "country" not in record.__dict__["args"]
Yes. Change applied [96da102](https://github.com/mozilla-services/merino-py/pull/98/commits/96da1021f6dabaf5b85f430648bf1a92af3e6f8f)

2022-11-02 19:08 UTC, Trinaa commented on tests/unit/conftest.py
> +def fixture_suggestion_request() -> SuggestionRequestFixture:
Change applied [14ab2ef](https://github.com/mozilla-services/merino-py/pull/98/commits/14ab2ef376ba78c484c5726126a1a7c6604ac4da)

2022-11-02 19:16 UTC, Trinaa commented on Makefile
> +.PHONY: test
Change applied [19fb627](https://github.com/mozilla-services/merino-py/pull/98/commits/19fb627f80f469d9c39f5e2090d827a39f23361b).

2022-11-02 19:52 UTC, Trinaa commented on tests/integration/api/v1/providers/test_providers.py
> +from tests.integration.api.v1.conftest import (
Change applied [b1d82c1](https://github.com/mozilla-services/merino-py/pull/98/commits/b1d82c150e55c0bfb1dbd9dba7202b309249262a).

See [comment](https://github.com/mozilla-services/merino-py/pull/98#discussion_r1012234660) for follow-up.

2022-11-02 20:56 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_metrics.py
> +    setup_providers(providers)
TIL about indirect!

I'm not sure how indirect can be applied in this use case, since this dict is not used for parameterization? I don't know if it's relevant, but the providers dict look fairly static in this PR, but I don't expect that going forward.

2022-11-02 20:57 UTC, Trinaa commented on tests/integration/api/v1/conftest.py
> +    def setup_providers(providers: dict[str, BaseProvider]) -> None:
I'm not really sure how to apply ParamSpec here?

2022-11-02 20:59 UTC, Trinaa commented
@hackebrot thank you for the review.

I have left follow-ups on comments and still have questions about `ParamSpec` and `indirect`

2022-11-03 00:46 UTC, ncloudioj commented on docs/dev/testing.md
> +and load level testing.
```suggestion
and load testing.
```

2022-11-03 00:46 UTC, ncloudioj commented on docs/dev/testing.md
> +service.
```suggestion
service.

```

2022-11-03 00:59 UTC, ncloudioj commented on tests/integration/api/conftest.py
> +    Note that this will NOT trigger event handlers for the app, see:
```suggestion
    Note that this will NOT trigger event handlers (i.e. `startup` and `shutdown`) for the app, see:
```

2022-11-03 01:00 UTC, ncloudioj commented on tests/integration/api/conftest.py
> +@pytest.fixture(name="client")
We only have one use case in `test_init_providers.py`.

2022-11-03 01:19 UTC, ncloudioj approved these changes
This is awesome. It makes me want to write more tests :)

2022-11-03 13:53 UTC, Trinaa commented on docs/dev/testing.md
> +and load level testing.
Change applied [1468f00](https://github.com/mozilla-services/merino-py/pull/98/commits/1468f006270bc01818fcb9d3b007da710fc3628e)

2022-11-03 13:53 UTC, Trinaa commented on docs/dev/testing.md
> +service.
Change applied [1468f00](https://github.com/mozilla-services/merino-py/pull/98/commits/1468f006270bc01818fcb9d3b007da710fc3628e)

2022-11-03 13:53 UTC, Trinaa commented on tests/integration/api/conftest.py
> +    Note that this will NOT trigger event handlers for the app, see:
Change applied [1468f00](https://github.com/mozilla-services/merino-py/pull/98/commits/1468f006270bc01818fcb9d3b007da710fc3628e)

2022-11-03 17:04 UTC, hackebrot commented on tests/conftest.py
> +def fixture_filter_caplog() -> FilterCaplogFixture:
Thanks! 👍🏻

2022-11-03 18:49 UTC, Trinaa commented
@ncloudioj following up from the engineering meeting. I've added some details about fixtures to the testing portion of the docs, see [3c5c991](https://github.com/mozilla-services/merino-py/pull/98/commits/3c5c991ce1fc47c0da1e5f0087f5e00e426fcbd2).

2022-11-03 19:22 UTC, ncloudioj commented
> @ncloudioj following up from the engineering meeting. I've added some details about fixtures to the testing portion of the docs, see [3c5c991](https://github.com/mozilla-services/merino-py/pull/98/commits/3c5c991ce1fc47c0da1e5f0087f5e00e426fcbd2).

Excellent, thanks! @Trinaa

2022-11-04 08:46 UTC, hackebrot commented on Makefile
> +.PHONY: test
Awesome! 🥳

2022-11-04 09:17 UTC, hackebrot commented on tests/integration/api/conftest.py
> +@pytest.fixture(name="client")
Thank you, @Trinaa!

I don't think it's obvious that one needs to use the `TestClient` as a `contextmanager` in order to trigger event handler for the FastAPI app. @ncloudioj shared a link to the documentation with me that explained it well, but I think it's a good idea to put this in code here and make it ergonomic to use.

2022-11-04 09:19 UTC, hackebrot commented on tests/integration/api/test_heartbeat.py
> +    assert "country" not in record.__dict__["args"]
Okay! That's unfortunate. Thanks! 👍🏻

2022-11-04 11:48 UTC, hackebrot commented on tests/integration/api/v1/conftest.py
> +    def setup_providers(providers: dict[str, BaseProvider]) -> None:
I just pushed https://github.com/mozilla-services/merino-py/pull/98/commits/cb24e1695c307505bc6b4e878be3606fdde732df which uses a type alias instead. A `ParamSpec` wasn't necessary here.

2022-11-04 11:56 UTC, hackebrot commented on tests/integration/api/v1/suggest/test_metrics.py
> +    setup_providers(providers)
I just pushed https://github.com/mozilla-services/merino-py/commit/cb24e1695c307505bc6b4e878be3606fdde732df that demonstrates how we can use a single `inject_providers` fixture together with local `providers` fixtures and `@pytest.mark.parametrize("providers, [{...}], indirect=True`.

This removes duplication of the `inject_providers` code for different parameters from test modules in `integration/api/v1`.

2022-11-04 16:26 UTC, hackebrot requested changes

2022-11-04 16:26 UTC, hackebrot commented on docs/dev/testing.md
> +For a breakdown of fixtures in use per test, use: `make test-fixtures`
I'm wondering whether we should have two make targets, one for each sub dir:
```
make make unit-tests-fixtures
```

```
make integration-tests-fixtures
```

2022-11-04 16:26 UTC, hackebrot commented on docs/dev/testing.md
> +def test_with_provider() -> None:
```suggestion
def test_with_provider() -> None:
    pass
```

2022-11-04 16:26 UTC, hackebrot commented on tests/integration/api/v1/models.py
> +class CorruptProvider(BaseProvider):
Hmm 🤔 

I see several `from tests.integration.api.v1.models import NonsponsoredProvider, SponsoredProvider` in many files, but `NonsponsoredProvider` and `SponsoredProvider` are no pydantic models.

Should we rename this module to `providers.py`?

2022-11-04 16:26 UTC, hackebrot commented on tests/integration/api/v1/models.py
> +        ...
Do we need this line with `...`?

2022-11-04 16:26 UTC, hackebrot commented on tests/integration/api/v1/suggest/test_suggest.py
> +    mock_client.host = "216.160.83.56"
I see this IP address is also used in `tests/unit/middleware/test_geolocation.py`.

Should we copy the comment from there over here?
```
# The first two IP addresses are taken from `GeoLite2-City-Test.mmdb`
```

2022-11-04 16:26 UTC, hackebrot commented on tests/unit/providers/test_init_providers.py
> -def test_unknow_providers_should_shutdown_app(mocker: MockerFixture) -> None:
I don't see this test moved to a different file? Is it OK to remove it?

2022-11-05 21:02 UTC, Trinaa commented on docs/dev/testing.md
> +For a breakdown of fixtures in use per test, use: `make test-fixtures`
Change applied [eae58d3](https://github.com/mozilla-services/merino-py/pull/98/commits/eae58d38ac0dc2a340fe6fe2521823aa6422ca23)

2022-11-05 21:02 UTC, Trinaa commented on docs/dev/testing.md
> +def test_with_provider() -> None:
Change applied [51aa671](https://github.com/mozilla-services/merino-py/pull/98/commits/51aa671dff52239159a46b5e57cc9f3049bfebf9)

2022-11-05 21:03 UTC, Trinaa commented on tests/integration/api/v1/models.py
> +class CorruptProvider(BaseProvider):
`providers.py` conflicts with the directory `providers`, which is on the same level. I changed it to `fake_providers.py`

Change applied [6c8f955](https://github.com/mozilla-services/merino-py/pull/98/commits/6c8f9555e421022cc5d152e595cbc3c3c5ab0f67)

2022-11-05 21:03 UTC, Trinaa commented on tests/integration/api/v1/models.py
> +        ...
Change applied [6c8f955](https://github.com/mozilla-services/merino-py/pull/98/commits/6c8f9555e421022cc5d152e595cbc3c3c5ab0f67)

2022-11-05 21:04 UTC, Trinaa commented on tests/integration/api/v1/suggest/test_suggest.py
> +    mock_client.host = "216.160.83.56"
Change applied [dccf10a](https://github.com/mozilla-services/merino-py/pull/98/commits/dccf10ae6452b2203bd09c7413f1cdbf8ef34271)

2022-11-05 21:04 UTC, Trinaa commented on tests/unit/providers/test_init_providers.py
> -def test_unknow_providers_should_shutdown_app(mocker: MockerFixture) -> None:
It was moved to `integration/api/test_setup.py`

2022-11-05 21:08 UTC, Trinaa commented on tests/integration/api/test_error.py
> +from tests.conftest import FilterCaplogFixture
Topic continued [here](https://github.com/mozilla-services/merino-py/pull/98#discussion_r1014726802)

2022-11-07 08:52 UTC, hackebrot commented on tests/unit/providers/test_init_providers.py
> -def test_unknow_providers_should_shutdown_app(mocker: MockerFixture) -> None:
Okay, thanks! 👍🏻

2022-11-07 08:58 UTC, hackebrot commented on tests/integration/api/v1/models.py
> +class CorruptProvider(BaseProvider):
Sounds good! Thanks! 👍🏻

2022-11-07 10:23 UTC, hackebrot requested changes

2022-11-07 15:12 UTC, Trinaa commented on docs/dev/testing.md
> +`types.py` and `models.py` modules respectively. The `conftest.py` modules contain
Change applied: [8331881](https://github.com/mozilla-services/merino-py/pull/98/commits/83318814aace0ecba04ad9e040704551a84d96ab)

2022-11-07 15:12 UTC, Trinaa commented on docs/dev/testing.md
> +the `types.py` and `models.py` modules respectively. The `conftest.py` modules contains
Change applied: [8331881](https://github.com/mozilla-services/merino-py/pull/98/commits/83318814aace0ecba04ad9e040704551a84d96ab)

2022-11-07 15:18 UTC, hackebrot approved these changes
Great work, @Trinaa! LGTM! 📦 🚀

2022-11-07 15:23 UTC, merged